### ISSUE TITLE
half-life theme doesn't reset shell color while using completion

### ISSUE THREAD

**Issue by eze-kiel** [ohmyzsh/ohmyzsh#10085]
### Describe the bug

half-life theme prompt ends with a orange "λ". Under certain circumstances, when using completion, the text typed goes from white to orange.

### Steps to reproduce

1. Enable plugin "half-life" in `.zshrc`
2. Go in a directory with a lot of files (i.e `~/.oh-my-zsh/themes/`
3. Next, you can type the keystroke sequence:
```
$ ls[TAB][ENTER]
```
[TAB] means you type the Tab key, and [ENTER] the Enter (or Return) key.

### Expected behavior

The text color should not change when using completion.

### Screenshots and recordings

Here is the Asciinema version of the instruction above:
https://asciinema.org/a/UukRGYb5tLlv2EvgMDtPSlrYX

### OS / Distro

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Terminator

**Comment by eze-kiel** [comment]
This is probably related to an edge case in the theme code where `%{$reset_color%}` is not called, but I didn't find it.

**Comment by valdaarhun** [comment]
Hi. I was looking at this issue and playing around with the code in the theme file. So basically, there are two problems.
- The colour of the input prompt changes when [TAB] is pressed.
- Pressing [ENTER] immediately after [TAB] also prints the output text in the old shell colour until it hits a part of the output text that requires another colour (eg: all the files in the ouput of `ls` get printed in orange until it prints the name of the directory in cyan. After that the remaining files are printed in the appropriate colour.)

I am not sure if the problem is because of `%{$reset_color%}` or if [TAB] ends up inserting some some special character which results in the colour change. The second problem still persists after removing the reset_color part in the `PROMPT` variable.

I managed to find a solution for the first problem in issue #4042 (this [comment](https://github.com/ohmyzsh/ohmyzsh/issues/4042#issuecomment-114145634) in particular).

In order to solve the second problem, I used the `preexec()` function in which I reset the colour back to normal using `"\033[0m"`.
(Ref: https://www.tutorialspoint.com/how-to-output-colored-text-to-a-linux-terminal).

**Comment by ApexBortz** [comment]
i have copied directories from my old computer on my new computer, but the directories are in yellow and black instead of cyan, new directories that i make on this computer appear in cyan, but the copied ones are yellow. I figure it is because they were not created on this computer, but is there a way to revert them to cyan?
