### ISSUE TITLE
Cannot auto complete absolute path while root directory in path is unreadable

### ISSUE THREAD

**Issue by nukemiko** [ohmyzsh/ohmyzsh#10112]
### Describe the bug

If root directory is unreadable (`ls: cannot open directory '/': Permission denied`), the auto-completion does not work on absolute paths, even of the path are sure to exist (such as `/sdcard/Android`).

### Steps to reproduce

1. Find a Android devices that root directory is unreadable (such as Huawei or Xiaomi devices), install a terminal emulator (such as Termux), then install zsh and ohmyzsh in terminal.
2. Enter a path that you are sure to exist, such as `cd /sdcard/Andr` (/sdcard/Android/), then attempt to trigger auto-completion.
3. Auto-completion does not work (the content entered has not be completed to `cd /sdcard/Android/`)

### Expected behavior

`cd /sdcard/Andr` -> press Tab or Ctrl-D to trigger auto-completion -> `cd /sdcard/Android/`

### OS / Distro

Android (or any OS that root directory is unreadable)

### Zsh version

5.8

### Terminal emulator

Termux

**Comment by bottercode** [comment]
I want to work on this issue. Please assign me

**Comment by mcornella** [comment]
This needs to be fixed by Zsh in the [`_path_files`](https://github.com/zsh-users/zsh/blob/99d915330aa470e5ca723084f54910d82aec444d/Completion/Unix/Type/_path_files) completion function, so that if there are no glob expansion results to check the exact path written. You can bypass this behavior by setting [`accept-exact-dirs`](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-accept_002dexact_002ddirs_002c-completion-style) or [`path-completion`](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-path_002dcompletion_002c-completion-style) zstyle options:
```
zstyle ':completion:*' accept-exact-dirs true
# or
zstyle ':completion:*' path-completion true
```

Related: https://github.com/ohmyzsh/ohmyzsh/issues/9929#issuecomment-922496016
