### ISSUE TITLE
ssh-agent plugin not loading identity

### ISSUE THREAD

**Issue by m1cmac** [ohmyzsh/ohmyzsh#10155]
### Describe the bug

Hi,

My **ssh-agent plugin** stopped working, probably due to latest changes` omz update`

Both `id_rsa` and `id_rsa.pub` are chmod 600.

It was working fine... but it stopped lately.

Thanks for any suggestions!

### Steps to reproduce

1. Configuration in .zshrc:
```
plugins=(
  ...
  ssh-agent
)
zstyle :omz:plugins:ssh-agent identities id_rsa
source $ZSH/oh-my-zsh.sh
```

2. On system startup:
```
Starting ssh-agent...
micmac@dell ~ $ ssh-add -l
The agent has no identities.
`

### Expected behavior

After asking for password, then loading identity is expected.

### Screenshots and recordings

_No response_

### OS / Distro

Linux Mint 20.1

### Zsh version

5.8

### Terminal emulator

Terminal

### If using WSL on Windows, which version of WSL

_No response_

### Additional context

_No response_

**Comment by m1cmac** [comment]
I've reverted `ssh-agent.plugin.zsh `  file from commit **Jun 14**:
https://github.com/ohmyzsh/ohmyzsh/commit/3e7998aec33ff7551d06d4510f9e8769aab5db93#diff-882eb31128f7e6be637cf66e4b7d7e2e47f71b41f4ce510614c8de5c1abbace4

and confirmed that it works.. :heavy_check_mark:

**Comment by alexejk** [comment]
Facing exact same issue

**Comment by alexejk** [comment]
The offending line seemed to be:

`command mkdir "$ZSH_CACHE_DIR/ssh-agent.lock" 2>/dev/null || return`
https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/ssh-agent/ssh-agent.plugin.zsh#L102

After commenting it out - things started working again. 

However, after it worked again - I fully reset ssh-agent plugin to latest `master` and it still makes it work. So I'm confused over what happened.

**Comment by mcornella** [comment]
Looks like the plugin entered the lock but didn't remove the directory when it exited, so the other loads of the plugin weren't able to add identities to the `ssh-agent`.

When you commented the line that checks for the lock directory, the plugin was able to run the rest of the script and then remove the lock directory. That's why it works now for subsequent runs.

So I imagine everyone else that's having this issue should be able to temporarily fix it by running `rm -f "$ZSH_CACHE_DIR/ssh-agent.lock".

I still don't know why the lock wasn't deleted though. Did you maybe CTRL-C when you were asked the ssh identity password?

**Comment by alexejk** [comment]
For me it just replicated again during a reboot.
I recon this is because I've booted into my system (did not input password during prompt in an auto-launch terminal, as my keyboard bugged out) and then rebooted to the solve keyboard issue.

I do not remember seeing this lock before and never had this issue even when keyboard messes up (stupid Corsair). Why is having the lock required? it does not need to be there as if the identity is added, ssh-agent does not re-prompt for password. Or have you seen a different behavior on some system?

**Comment by erakli** [comment]
Hello, I've found the same issue recently. I'm pretty sure that there is nothing about lock problems. 

The issue could be fixed by using absolute paths to identites instead of plain names:

```diff
# ~/.zshrc

plugins=(git yarn nvm ssh-agent)

- zstyle :omz:plugins:ssh-agent identities id_work_ed25519
+ zstyle :omz:plugins:ssh-agent identities ~/.ssh/{id_work_ed25519}
```

No doubt, the issue was introduced after 4a69ee5. @mcornella, could you confirm this?

**Comment by mcornella** [comment]
> No doubt, the issue was introduced after [4a69ee5](https://github.com/ohmyzsh/ohmyzsh/commit/4a69ee575c9a8ec96fb6378fecae7777c7afba84). @mcornella, could you confirm this?

That cannot be the case, you probably ran into a case where the lock directory got removed somehow. Both ways should work correctly, regardless of how the identities are specified (I tested this multiple times).

> I do not remember seeing this lock before and never had this issue even when keyboard messes up (stupid Corsair). Why is having the lock required? it does not need to be there as if the identity is added, ssh-agent does not re-prompt for password. Or have you seen a different behavior on some system?

The lock was added so that the identities are only tried to load once per ssh-agent (i.e. if you open multiple tabs, having multiple password prompts is not ideal). But since that's a corner case and it doesn't seem to be working properly, I might temporarily rollback the changes until I can find the issue.

**Comment by mcornella** [comment]
Reverted in 735808f48d54aabce540f6c90294e21118104cf4. Please reopen if you have issues. If you still have a lock directory it would be a good idea to run `command -rf "$ZSH_CACHE_DIR/ssh-agent.lock"`.
