### ISSUE TITLE
Git stash drop autocomplete fails

### ISSUE THREAD

**Issue by tomasMizera** [ohmyzsh/ohmyzsh#10156]
### Describe the bug

I use autocomplete with <TAB> all the time, when I try to use it with command `git stash drop`, it fails to show me a list of stashes and instead each time I hit <TAB> I get several argument errors in terminal.

### Steps to reproduce

1. Navigate to any git repository
2. Type in:

```
git stash drop <hit TAB> 
```

In the console you will see:
```
_arguments:comparguments:325: invalid argument: _git-notes
_git-stash:88: command not found: (-q --quiet)-q[suppress all output]
_arguments:comparguments:325: invalid argument: _git-notes
_git-stash:88: command not found: (-q --quiet)-q[suppress all output]
_arguments:comparguments:325: invalid argument: _git-notes
_git-stash:88: command not found: (-q --quiet)-q[suppress all output]
```

### Expected behavior

Should show a list of stashes just like when doing `git stash pop <TAB>`

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/22449698/131788033-e9a09857-3129-481b-8fb6-aec0a38f53fc.png)

### OS / Distro

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

GNOME Terminal 3.36.2

### Additional context

git version 2.25.1

**Comment by mcornella** [comment]
The bug was introduced in https://github.com/zsh-users/zsh/commit/8aa84bd5fc4402a4118481388640fd74b0aeb321 (this means only version 5.8 is affected). This was fixed in https://github.com/zsh-users/zsh/commit/754658aff38e1bdf487c58bec6174cbecd019d11 but it hasn't made it yet into the next release. 

As a workaround, you can force loading the `_git` completion and remove the `\_git-notes` string from the `_git-stash` function, like so (**put this at the end of your `.zshrc` file**):
```sh
autoload +X -Uz _git && _git &>/dev/null
eval "_git-stash() { ${functions[_git-stash]//\\_git-notes /} }"
```
