### ISSUE TITLE
[BUG] yarn plugin increase loadtime dramatically!

### ISSUE THREAD

**Issue by qvieth** [ohmyzsh/ohmyzsh#10290]
### Describe the bug

after OMZ auto updated this week, my zsh load time increased.

I found the culprit was the yarn plugin

zsh loadtime when there's no yarn plugin in my config:
![image](https://user-images.githubusercontent.com/71810726/136927950-b0f53c5b-dbe1-4608-bbf4-0c612760b02b.png)

adding yarn back increase the loadtime:
![image](https://user-images.githubusercontent.com/71810726/136928009-1f20a6f6-ee46-46cf-8d16-481824fca1df.png)

### Steps to reproduce

done

### Expected behavior

back

### OS / Distro

fedora 34

### Zsh version

5.8

### Terminal emulator

kitty

**Comment by SimenB** [comment]
@mcornella would it be possible to add an env var or something to skip this call entirely? The `global` command is removed from yarn v2, so if you open a shell in a directory which uses yarn v2, it doesn't even work

```sh-session
$ yarn --version
3.1.1
$ yarn global bin
Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```

Also, on macOS `yarn global bin` returns `/usr/local/bin` (at least when installed through homebrew), so this adds zero features even if it had worked.

**Comment by mcornella** [comment]
> @mcornella would it be possible to add an env var or something to skip this call entirely? The `global` command is removed from yarn v2, so if you open a shell in a directory which uses yarn v2, it doesn't even work
> 
> ```
> $ yarn --version
> 3.1.1
> $ yarn global bin
> Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead
> 
> $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
> ```

`yarn` v1 is still the default global binary when following the instructions, so it should work at least until that is removed.

Also the `yarn global bin` call silences stderr so no errors are seen. Using `yarn --version` to detect support would probably double the plugin load time.

> Also, on macOS `yarn global bin` with yarn v1 returns `/usr/local/bin` (at least when installed through homebrew), so this adds zero features even if it had worked.

The `yarn` install guide specifies using `npm` and macOS is not the sole target of this plugin, so it does make sense to have this feature for the time being.

That said, we could either add a disable setting or remove it entirely. Since `yarn` v1 is still the way to go for the global binary, it doesn't make sense to remove it altogether, so yes, a setting seems like the best popm.

Could you open a feature request issue?

**Comment by SimenB** [comment]
> `yarn` v1 is still the default global binary when following the instructions, so it should work at least until that is removed.

When you use yarn v2 or newer (3 is latest at time of writing), you check in a JS file which the global `yarn` runs instead of "itself", id that makes sense. AFAIK the `yarn` global will remain at v1 forever.

I'll open a feature request for a way to disable though, thanks!

**Comment by SimenB** [comment]
#10641
