### ISSUE TITLE
`plugins/pyenv` always warn `missing pyenv shims in $PATH`

### ISSUE THREAD

**Issue by loynoir** [ohmyzsh/ohmyzsh#10385]
### Describe the bug

`plugins/pyenv` always warn `missing pyenv shims in $PATH`

### Steps to reproduce

Recenlty updated omz. Enable `pyenv`, always got warning.

https://github.com/ohmyzsh/ohmyzsh/blob/9a02515c7c8eee90909fe72d59d2e3169cb5ed28/plugins/pyenv/pyenv.plugin.zsh#L74

### Expected behavior

Not warning everytime.

### OS / Distro

Arch Linux

### Zsh version

5.8

### Terminal emulator

gnome terminal

### Additional context

Recenlty updated omz.

pyenv 2.1.0

**Comment by loynoir** [comment]
@matchaxnb @mcornella @tmoschou

**Comment by loynoir** [comment]
Arch Linux pyenv package installer source code

https://github.com/archlinux/svntogit-community/tree/3cae372d9ca82902c4a547afce917ffa17e94b04/trunk

**Comment by mcornella** [comment]
You need to both change your `.profile` and `.zprofile` files with the suggested lines, and then log out of your graphical session and log back in. Otherwise the changes in `.profile` are not applied (and `.zprofile` is only read if your terminal runs zsh as a login shell).

If you don't want to do any of that, [there is a setting in the plugin that you can enable to turn off the warning](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/pyenv/README.md#settings).
