### ISSUE TITLE
Composer 2.2 release causes composer plugin to make initialization hang

### ISSUE THREAD

**Issue by mglaman** [ohmyzsh/ohmyzsh#10526]
### Describe the bug

I just updated to Composer 2.2. When I rebooted, ohmyzsh just hung. Forever. I finally disabled plugins and narrowed it down to `composer`. The only difference pre-boot and reboot was the fact I updated to 2.2 of Composer

### Steps to reproduce

1. Install Composer 2.2
1. Enable `composer` plugin
2. `source .zshrc`

### Expected behavior

Can use terminal, `.zshrc` sourced

### OS / Linux distribution

macOS 12.1

### Zsh version

5.8

### Terminal emulator

iTerm2

**Comment by tw2066** [comment]
`composer require`     cause the card to death

**Comment by mglaman** [comment]
I think the problem is the new plugin security check. It asks you to add plugins to an allowed list. So if you have any composer plugins globally installed, it can cause ohmyzsh to hang until they're approved.

**Comment by tw2066** [comment]
<img width="436" alt="QQ20211224-111216@2x" src="https://user-images.githubusercontent.com/24579418/147311465-b7b93b7b-4158-471c-a2f5-a9ed4f566e4b.png">
You can't do anything except close the window

**Comment by mcornella** [comment]
The only call to `composer` in the plugin is `composer global config bin-dir --absolute`. Does running that hang or show any prompts?

**Comment by tw2066** [comment]
`composer global config bin-dir --absolute` Don't hang    
`composer global config` there are hints
`bin-dir --absolute` no hint
@mcornella

**Comment by shyuan** [comment]
I don't use composer for a long time, there are some obsolete global packages exist on my ~/.composer/ and hang on initialization also happens to me.
After remove all files in ~/.composer/ it does not hang any more.

**Comment by ocean90** [comment]
This seems to be an issue with the [command completion](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_composer) provided by zsh since the completion of the omz plugin isn't used if the zsh version is >5.7.

As a workaround I have removed the version check [in this line](https://github.com/ohmyzsh/ohmyzsh/blob/c08b925d282e35ea7bd9a8f4c29de2ece0debb49/plugins/composer/composer.plugin.zsh#L3) (or change the version to the output of `zsh --version`) and the autocomplete for `composer require` is now working again.

**Comment by carlosala** [comment]
Good catch! Then it's solved!
