### ISSUE TITLE
Git version in README.md seems incorrect

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#10575]
HI!
In README.md is said that `git` v2.4.11 is recommended, but latest release is v2.34.1.
Seems like a typo!

https://github.com/ohmyzsh/ohmyzsh/blob/9c84c344d762b200de7acc794b9a0e7832144e7a/README.md#L28

**Comment by mcornella** [comment]
A quick review of [current git packages](https://pkgs.org/download/git) shows that the only distributed git version older than v2.4.11 is v1.8.3 in Centos 7 and v1.8.4 in Slackware 14.1. The rest are all in the v2.20+ range. This is only on currently supported distributions; others will have older git versions.

The reason for a suggested minimum version though is that things might break on older versions. I'm not sure why v2.4.11 was chosen, I can't find the reasoning in the PR that changed it, but the previous minimum recommended version [was v1.7.2](https://github.com/ohmyzsh/ohmyzsh/commit/498cd722b39215be04468f291a23b6a76b75b095) because the installer broke without it.

In fact, if there's nothing in the project requiring a higher version, we could go back to changing that back, though this could give the wrong impression that we need to support ancient versions.

The truth is that I don't have an answer here. Maybe we could maintain a Requirements section in the wiki for the most common commands, with minimum versions associated to used `--arguments` and behavior.

**Comment by carlosala** [comment]
Ups sorry, I was always reading 2.41. Sorry Marc, thanks for your answer ;)

**Comment by carlosala** [comment]
Changing topic, I read that you are searching volunteers for labeling issues, assigning PR and that sort of things. Lately I have been really interested on omz and I have been working a little on it. Maybe I could help on that volunteering :)
