### ISSUE TITLE
Why does the directory have this yellow block area

### ISSUE THREAD

**Issue by czqn8** [ohmyzsh/ohmyzsh#10770]
### Describe the bug

Why does the directory have this yellow block area , how to get rid of this warning.

![](https://thumbnail1.baidupcs.com/thumbnail/45854ace4uaa1c76745a93dc4e397989?fid=4011644425-250528-326048104336593&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-Bt8%2bSX1Lq5K%2bwkH9a9Z8ghDhJvI%3d&expires=8h&chkbd=0&chkv=0&dp-logid=482467609553944262&dp-callid=0&time=1647057600&size=c1680_u1050&quality=90&vuk=4011644425&ft=image&autopolicy=1)

### Steps to reproduce

ls

### Expected behavior

ls

### OS / Linux distribution

macos10.15.5

### Zsh version

5.7.1

### Terminal emulator

iterm2

**Comment by carlosala** [comment]
This happens when you have write permissions for `others` in that folder. Probably you get those directories from a Windows system that gives `777` permissions, which means that every user in your system can read and write in that folder. You can get rid of that warning executing `chmod 755 -R <folder_you_want>`. There's a plugin in `omz` to manage that kind of permissions (`perms` plugin). By the way, it's an advanced plugin, so don't use it if you are not sure about what are you doing! 😉

**Comment by czqn8** [comment]
Thx,this file has been resolved
