### ISSUE TITLE
omz update stopped working because unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by cooniur** [ohmyzsh/ohmyzsh#10782]
### Describe the bug

Getting the following error when trying to update oh-my-zsh:

```
[oh-my-zsh] Would you like to update? [Y/n] y
Updating Oh My Zsh
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
There was an error updating. Try again later?
```

### Steps to reproduce

1. Run `omz update` in terminal
2. It should fail with the error message mentioned above.

### Expected behavior

It's expected that the update should finish successfully.

### OS / Linux distribution

MacOS 12.3

### Zsh version

5.8

### Oh My Zsh version

master~70 (a7efd96a)

### Terminal emulator

iTerm2

### Additional context

The oh-my-zsh I used is provided by this repo: https://github.com/atomantic/dotfiles.

**Comment by cooniur** [comment]
Nvm, saw this was already fixed. I need to figure out how to upgrade the oh-my-zsh included in atomatic/dotfiles.

**Comment by mcornella** [comment]
Hi @cooniur, sorry for the confusion.

You should be able to manually update the remote with `git remote set-url origin "https://github.com/ohmyzsh/ohmyzsh.git` assuming `origin` is the remote pointing to this repository (source https://github.com/ohmyzsh/ohmyzsh/issues/10778#issuecomment-1068832240)

Unfortunately since the dotfiles you use are using `git:` in the submodules, you have to use a different command. Provided you have git 2.25 or older, you can run this command to change the URL for ohmyzsh. **Note this is only specific to [the dotfiles used by @cooniur](https://github.com/atomantic/dotfiles/blob/main/.gitmodules)**:
```sh
cd <dotfiles-path>
git submodule set-url -- oh-my-zsh "https://github.com/ohmyzsh/ohmyzsh.git"
```

You should update the rest of the submodules in a similar manner.

Duplicate issue is at #10778.

**Comment by cooniur** [comment]
Hi @mcornella, thank you for the follow up! I also found the change from the source code at [tools/upgrade.sh](https://github.com/ohmyzsh/ohmyzsh/commit/4a988c46609c4c2d32240092899ae0aae45b11a6) and I got the git url fixed. All good now. 

Thank you!
