### ISSUE TITLE
Add zsh-async plugin

### ISSUE THREAD

**Issue by Cyberbeni** [ohmyzsh/ohmyzsh#10799]
### If the feature request is for a plugin or theme, specify it here.

https://github.com/mafredri/zsh-async

### Describe the proposed feature.

zsh-async is often used in custom themes for providing fast prompt and then refreshing it when git status message has been properly composed, it would be nice to have it automatically update with ohmyzsh instead of having to install/update it separately

### Describe alternatives you've considered

brew install zsh-async

**Comment by stephanschielke** [comment]
For anyone else stumbling upon this:

[zsh-async](https://github.com/mafredri/zsh-async) provides the [async.plugin.zsh](https://github.com/mafredri/zsh-async/blob/main/async.plugin.zsh) plugin file which does nothing else but source the real `async.zsh`. You can use it directly with OMZ plugin system by cloning the repo into your `"${ZSH_CUSTOM}/plugins"` (usually `~/.oh-my-zsh/custom/plugins`) but make sure to clone as `async` (and not `zsh-async`) like this:
```bash
git clone git@github.com:mafredri/zsh-async.git "${ZSH_CUSTOM}/plugins/async"
```
_The reason is all entries under your `plugins` directory are added to your `$fpath` if it contains a matching function import. However, the `*.plugin.zsh` uses the the name `async` but the repo is named `zsh-async`._ 

Once the `async` function is in your `$fpath` you can add it to the list of plugins to be loaded. So somewhere in your `$ZSHDOTFILE/.zshrc`
```
plugins=(... async ...)
```

Also:
```
async () {
	async_init
}
```
is starting the init, and you won't have to. Just for scripts make sure they also have a sources `zsh-async` (since usually the plugins are only loaded for interactive shells)
