### ISSUE TITLE
"intheloop" theme lets cursor overwrite prompt on Kitty

### ISSUE THREAD

**Issue by reidevries** [ohmyzsh/ohmyzsh#10917]
### Describe the bug

I'm using the "intheloop" theme, and I noticed often the cursor will overwrite the prompt. I tested with some other themes such as fino-time, and it seems to only affect the intheloop theme out of the ones i tested. I tested with Alacritty, and the bug doesn't seem to occur there, so this might be a Kitty bug, but the fact that most OMZ themes do work on Kitty makes me think it's an issue with the theme itself.

### Steps to reproduce

The easiest way to make this happen is to type a nonexistent command, let zsh error message show, then the cursor will be over the top of the prompt. If you type a valid command like `touch test` then the cursor returns to the expected position.

### Expected behavior

The cursor appears to the right of the prompt no matter what command is executed.

### Screenshots and recordings

![2022-05-08T15:47:00,121592270+09:30](https://user-images.githubusercontent.com/25862413/167284763-e7ef4d0a-762b-455c-b461-9884a14623e1.png)
Here we have intheloop in the top terminal, and fino-time in the bottom terminal

### OS / Linux distribution

Arch Linux

### Zsh version

5.8.1

### Terminal emulator

Kitty

**Comment by mcornella** [comment]
I could not reproduce your issue neither with zsh 5.8 nor 5.8.1. Can you post the kitty version? (`kitty --version`). I was using 0.23.1, for what it's worth.

**Comment by reidevries** [comment]
I'm on Kitty 0.25 and zsh 5.8.1

**Comment by mcornella** [comment]
Can't reproduce with kitty 0.25 either.

Just to recap, this only happens when there's an error displayed, so the arrow is shown in the right prompt. That character is in the UTF-8 range, meaning that you need to have a UTF-8 locale. 

That's probably your issue here, and I did manage to reproduce it with `export LANG=C`. What you need is to set `LANG` to a locale that supports `UTF-8`. See https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-change-my-locale.
