### ISSUE TITLE
Add node_modules/.bin to path

### ISSUE THREAD

**Issue by remcohaszing** [ohmyzsh/ohmyzsh#10924]
### If the feature solves a problem you have, specify it here.

When working with Node.js, it can be useful to run commands from the local `node_modules` folder. So for example instead of `yarn eslint .` or `npx eslint .`, one could simply run `eslint .`

### Describe the proposed feature.

Add `node_modules/.bin` to path. For monorepo support, this should be done for each `node_modules/.bin` folder found up the parent tree of the current working directory. It should also be cleaned up.

### Additional context

I have been using this feature for a while now and I like it. I think it might be useful for others too.

```zsh
function precmd() {
  # Add node_modules/.bin to path
  path=( ${path[@]:#*node_modules*} )
  local p="$(pwd)"
  while [[ "$p" != '/' ]]; do
    if [[ -d "$p/node_modules/.bin" ]]; then
      path+=("$p/node_modules/.bin")
    fi
    p="$(dirname "$p")"
  done
  typeset -U path
}
```

It’s important the local paths are appended, not prepended, so these commands don’t override existing commands. I.e. a malicious package could register the binary `ls`.

This works with both npm and yarn, and any other package managers that store executables in `node_modules/.bin`.

**Comment by diroussel** [comment]
I would like this feature too.  It somehow used to work when I was using yarn (but only to the root node_modules/.bin), but now I'm on pnpm that's not enought, as there is less hoisting going on.

**Comment by Jolg42** [comment]
Also interested into this for `npx` and `pnpm`, it would be a nice DX improvement

**Comment by carlosala** [comment]
Hi!
I'd say it's better to stick to the regular workflow. If you want to execute something from `node_modules/.bin`, you can always do `npm/pnpm/yarn/whatever <binary>`, and it's going to use the `node_modules/.bin` entry, as it's prepended in all package managers to all other entries in the `PATH`.
I imagine the case of someone using `prettier`. In that project, they used the `v2`; in the global path, they installed `prettier` `v3`. I'd expect to execute the `v2` if I'm inside the project, and in this case, it wouldn't be the case since the PATH would be appended.
Executing the `<pkgManager> <binary>` does not seem a significant burden, and this plugin might have some problems like the one mentioned before, leading to non-deterministic execution in different machines.
Thanks for the idea and the comments!

**Comment by remcohaszing** [comment]
Thanks for the feedback! I do have some counter arguments. I don’t expect to change your mind, but I’ll give it a try anyway.

- `npx` / `pnpx` / `yarn` / etc give additional runtime overhead, making the command slower to run. Running the command directly is faster.
- If no package manager is used, ZSH can autocomplete commands.
- If no package manager is used, This integrates with `thefuck`.
- I think linters / formatters / test runners are good examples of what this is useful for. I don’t think users typically install those globally.
- Oh My Zsh plugins are opt-in. The user needs to explicitly enable this.

Let me know if this changes anything. If not, I’ll publish it as an external plugin. :)

**Comment by carlosala** [comment]
That's a great solution! I encourage you to contribute with your external plugin in our [wiki](https://github.com/ohmyzsh/wiki)!

**Comment by remcohaszing** [comment]
It’s available in https://github.com/remcohaszing/zsh-node-bin.
