### ISSUE TITLE
Percent symbol after line execution in "bgnotify" plugin

### ISSUE THREAD

**Issue by riZZZhik** [ohmyzsh/ohmyzsh#10971]
### Describe the bug

If turn on [bgnotify](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/bgnotify) plugin and execute `cd` command very fast then I am getting a command with `%` symbol at the end
Reproduced both in iTerm and default macOS Terminal

### Steps to reproduce

1) Enable "bgnotify"
2) Re-run zsh
3) Run `cd` command very fast

### Expected behavior

Do not see command with `%` symbol after execution

### Screenshots and recordings

https://user-images.githubusercontent.com/21087403/171801696-718dfb31-a7fd-4a96-8691-2f44602d9e83.mov

### OS / Linux distribution

macOS Monterey

### Zsh version

5.8

### Oh My Zsh version

master (e9e8c6b)

### Terminal emulator

iTerm2 and Terminal.app

**Comment by riZZZhik** [comment]
romkatv/powerlevel10k#1885

**Comment by mcornella** [comment]
Was able to reproduce this with macOS. The issue was that `osascript` is taking too long on each command run, and we are executing it on each command run for no reason as the terminal app ID is not supposed to change during the whole shell execution.

I have pushed PR #11256 that should fix it. If you're still interested in the fix, please test it out with `omz pr test 11256` and give your feedback on the PR.

Thanks for reporting this!
