### ISSUE TITLE
completions for oc plugin is broken

### ISSUE THREAD

**Issue by VeitSanner** [ohmyzsh/ohmyzsh#11008]
### Describe the bug

When I try to use autocompletions (TAB) for the OpenShift CLI (oc plugin), I get an error message.

### Steps to reproduce

1. Enable plugin `oc`
2. Enter `oc exec -ti ` and press TAB.
3. Error Message: `(eval):1: command not found: _oc`

### Expected behavior

After pressing TAB the Pod name should be completed.

### OS / Linux distribution

CentOS Stream 8

### Zsh version

5.5.1

### Oh My Zsh version

master (4c82a2e)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

### Additional context

With PR #10973 changes were applied and `_oc` was introduced:

https://github.com/ohmyzsh/ohmyzsh/blob/4c82a2eedf0c43d47601ffa8b0303ed1326fab8f/plugins/oc/oc.plugin.zsh#L5-L8

**Comment by ItTakesTwo** [comment]
Encountered the same behavior in my ZSH environment running inside WSL2 as well. The source of the issue turned out to be the used oc CLI version. I was running v3.11.0 which outputs a completely different completion instruction set when calling `oc completion zsh` compared to e.g. v4.2.0, missing the referenced `_oc` function needed for `compdef _oc oc` to work. Updating my oc CLI fixed it.
If you have to stay on a version that does not provide the `_oc` function in its completion instruction set, you can remove https://github.com/ohmyzsh/ohmyzsh/blob/4c82a2eedf0c43d47601ffa8b0303ed1326fab8f/plugins/oc/oc.plugin.zsh#L7 and the auto completion will work again.

**Comment by carlosala** [comment]
Closing since it's due to an old version of the CLI, and not our issue. Thanks @ItTakesTwo for your contribution!
