### ISSUE TITLE
Define Custom Colors

### ISSUE THREAD

**Issue by MMore** [ohmyzsh/ohmyzsh#1101]
I tried to setup some custom colors in my zsh according to http://www.dawoodfall.net/index.php/custom-zsh-prompts. But it does not work.

```
ugrey="%{^[[01;04;30m%}"
PROMPT="%(!.%{$fg[red]%}.$ugrey%n@)%m:%{$fg_bold[green]%}%c %{$reset_color%}%# "
```

But in my shell this appears: `^[[01;04;30muser@host:~ %`

Anyone?

**Comment by apjanke** [comment]
FYI, current versions of Terminal.app have 256 color support, at least since Lion. (It declares `$TERM` as `xterm-256color` by default.) The setting for what `$TERM` it declares is in Preferences > Settings > Advanced > "Declare terminal as:", and is set on a per-profile basis.

BTW, inside prompts, you can use the more concise `%F/%f` codes. (`%F{color}` to start a color, `%f` to return to the default color.) Your prompt can be rewritten like this, and it works fine for me in Terminal.app on OS X 10.9.5.

PROMPT='%(!.%F{red}.%F{241}%n)@%m:%B%F{green}%c%f%b # '

![screen shot 2015-06-08 at 9 59 48 am](https://cloud.githubusercontent.com/assets/2618447/8036312/1cea385c-0dc5-11e5-999e-1c4673f36717.png)
