### ISSUE TITLE
ssh-agent plugin cache mechanism should use XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by FallenWarrior2k** [ohmyzsh/ohmyzsh#11066]
### If the feature request is for a plugin or theme, specify it here.

ssh-agent plugin

### If the feature solves a problem you have, specify it here.

Currently, the mechanism for caching SSH agents just uses a loose file under `~/.ssh`, which is a bit annoying since it's usually a relatively static config directory.

### Describe the proposed feature.

This [line](https://github.com/ohmyzsh/ohmyzsh/blob/249c708ed3a4a7a63d16a6e911a46b6fb9623cbd/plugins/ssh-agent/ssh-agent.plugin.zsh#L2) should probably use `$XDG_RUNTIME_DIR`. Since the state of a running SSH agent is inherently local to the current machine and to the current boot, that is in my opinion the most fitting location for such information.

### Describe alternatives you've considered

Symlinking the files used to `$XDG_RUNTIME_DIR` manually. Very hacky and needs to be done manually for each machine used.

**Comment by ferdnyc** [comment]
> This [line](https://github.com/ohmyzsh/ohmyzsh/blob/249c708ed3a4a7a63d16a6e911a46b6fb9623cbd/plugins/ssh-agent/ssh-agent.plugin.zsh#L2) should probably use `$XDG_RUNTIME_DIR`.

I'm unsure whether this is really a good idea.

Any SSH-related files are generally kept in `~/.ssh/` because they can contain sensitive data, and the `ssh` tools check the permissions on that directory any refuse to run if they're too lax. That protection seems worthwhile to leverage.

The environment scripts could be stored in a (mode `0700`) _subdirectory_ of `~/.ssh/`, to keep them from polluting the toplevel dir. But I'm not sure the **common** temp/cache areas are really a wise place to store them.

**Comment by carlosala** [comment]
I do agree with @ferdnyc. Everything from ssh should be kept in `~/.ssh`. Closing, thanks to both for the contribution!
