### ISSUE TITLE
The installation environment check invalid in my situation.

### ISSUE THREAD

**Issue by aaftio** [ohmyzsh/ohmyzsh#11157]
### My environment:
- Windows 11
- Cygwin64: CYGWIN_NT-10.0-22000
- Git for Windows: Git-2.37.2.2-64-bit
- zsh 5.8 (x86_64-pc-cygwin)

### Describe the bug
When I try to install ohmyzsh in my Cygwin64, I can‘t get clear information why I encounter this error "git clone of oh-my-zsh repo failed". 
Until I check out the source code and find blow.
https://github.com/ohmyzsh/ohmyzsh/blob/dfa88b4d369f6afc7205af0b399a0ef05a4bef2e/tools/install.sh#L269-L274

I recognize my git variant incompliant with ohmyzsh. So I checkout the `git --version` output.
The latest Git for Windows `git --version` output is `git version 2.37.2.windows.2`, and it doesn't contains `msysgit` anymore.

So can we add `windows` to the environment check script then make the correct error message for user?

**Comment by mcornella** [comment]
If I understand correctly, the `git` version you have (Git for Windows) fails when doing a `git clone`, and so you'd like the `grep` check to also look for the `windows` string in the `git --version` output, as this would indicate the error cause properly.

This is a simple fix. However, note that you'll still have to install a `git` version in cygwin that takes precedence over the Git for Windows one.

Thanks for reporting!

**Comment by aaftio** [comment]
@mcornella Yes, you're right.

**Comment by begris** [comment]
Hi, we stumbled upon this during the setup of new machines, as it has worked for us in the past just fine and is only an issue on new installations. Currently the fix applied prevents us from installing oh-my-zsh on Cygwin with only the Windows Git client installed.
Since Git version 2.32.0 using only the windows git client without an additional installation of the cygwin git client works just fine, as the last annoying issue (converting cygwin paths to windows paths) was addressed in the windows git client itself.
We are working with this configuration since the end of 2021 without any git related issues, neither in cygwin nor in windows itself.
This fix now caugth my attention, as we are swapping out our workstations with new ones and the first of my co-workers could not install oh-my-zsh as we were used to.

This 'fix' prevents us from using the windows git client. But I can't see the reason why it was implemented in the first place.
Besides the 'git clone failed' there is no further information what exactly did not work in the first place.
Maybe the windows git client and the cygwin git client were installed in parallel?

@mcornella or @aaftio can you explain why this change was required? I would like to prevent managing two competing git installations on our systems.

I would be happy to help find a solution which supports both usecases - git windows client only and git windows client & cygwin client installed in parallel.
