### ISSUE TITLE
Change directory listing when zoxide is used

### ISSUE THREAD

**Issue by JediMaster25** [ohmyzsh/ohmyzsh#11199]
### Describe the proposed feature.

When using `d` to list directories show the directories given the top score by zoxide.

https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zoxide

**Comment by carlosala** [comment]
Hi!
`d` is just an alias for `dirs` adding `-v` to be able to move from one to each other. This command has nothing to do with `zoxide` I'm afraid!
Thanks for your proposal!

**Comment by rwmitchell** [comment]
I believe the OP was suggesting to use zoxide instead of 'dirs -v' as both give a way if jumping to previously used directories.

zoxide appears to use heuristics to be better at it than a simple stack, but I don't use it and the plugin doesn't indicate what it actually does create in the way of aliases.  The output from ```zoxide init zsh``` isn't shown.

**Comment by mcornella** [comment]
@JediMaster25 you can override the `d` function in your zshrc file to call the zoxide command to list recent directories:

```sh
alias d='zoxide query -ls'
```
or
```sh
function d { zoxide query -ls }
```

---

That said, the purpose of `d` is to know which number to pick when using the number aliases though. For example, with this

```console
$ d
0	~/code
1	~/code/dotfiles
2	~/code/dotfiles/ohmyzsh
3	~
```

I know that running `2` I will jump to the `~/code/dotfiles/ohmyzsh` folder. Because of that, this is out of scope of the `d` function and we won't be implementing the change.

**Comment by JediMaster25** [comment]
> you can override the `d` function in your zshrc file to call the zoxide command to list recent directories

I don't know why you think I want to do that. I've explained it twice already.

https://github.com/ohmyzsh/ohmyzsh/issues/11247

**Comment by rwmitchell** [comment]
That’s not how it works. Write a new d function that uses zoxide instead of dirs.

**Comment by mcornella** [comment]
```sh
function d () {
  if [[ -n $1 ]]; then
    dirs "$@"
  else
    zoxide query -ls
  fi
}
```
