### ISSUE TITLE
Tab completion for docker 

### ISSUE THREAD

**Issue by TanmayPatil105** [ohmyzsh/ohmyzsh#11288]
### Describe the bug

oh-my-zsh doesn't recommend `IMAGE-ID` and `CONTAINER-ID` after pressing `TAB`

## For IMAGE ID
1. Type
```
sudo docker run
```
2.  Press `TAB`

The `IMAGE ID`'s doesn't show up

## For CONTAINER ID

1. Type
```
sudo docker stop
```
2.  Press `TAB`

The `CONTAINER ID`'s doesn't show up

### Expected behavior

The available `IMAGE ID`'s and `CONTAINER ID`'s should be displayed after pressing `TAB`.

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Oh My Zsh version

master (65a1e4e)

### Terminal emulator

GNOME (Terminal)

**Comment by mcornella** [comment]
If you have docker set up so that you need sudo, the completion function will not be able to get the information, as it does not run `sudo`. 

You can try logging as root with `sudo -s` and then completing the command, or setting up docker so it does not need sudo for your user (there are instructions in their docs).

**Comment by nicolasdespres** [comment]
Hi,

Thank you very much for writing such a great script.

I understand that it is not your issue, but maybe documenting how to achieve it could help your user.

I have found that Zsh supports the [gain-privileges](https://zsh-manual.netlify.app/completion-system) style to do exactly that.

I have tried it by adding this line in my `.zshrc`:

```
zstyle ':completion::complete:*' gain-privileges true
```

Unfortunately it does not work. Since, I am not a Zsh expert, I do not know whether I did something wrong or your docker completion script have to do something in particular to support this option.

I am using version `fe4b5659863c388786986d70fa6d1bb66b00afb6` of `_docker` and Zsh 5.9.

Any help would be welcome
