### ISSUE TITLE
Installation is failing

### ISSUE THREAD

**Issue by sivavarma111** [ohmyzsh/ohmyzsh#11410]
### Describe the bug

Getting the below error while trying to install

--2022-12-28 06:58:09--  https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 49.205.171.201
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.205.171.201|:443... connected.
OpenSSL: error:140943E8:SSL routines:ssl3_read_bytes:reason(1000)
Unable to establish SSL connection.

### Steps to reproduce

1. Install zsh
2. run the below command
`sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

### Expected behavior

Install Correctly

### OS / Linux distribution

Ubuntu 20.04

### Zsh version

5.8

### Terminal emulator

Tilix

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
That's some problem with your connection with Github, it's not our issue. You could try googling it to see if there's more people with the same issue (I'm sure about that).
Seeing that is a SSL issue, maybe trying with `http` instead of `https` might help, or try the installer using `curl`.
Good luck finding the problem! 😉
