### ISSUE TITLE
Plugins not being sourced when using a different $ZSH_CUSTOM path 

### ISSUE THREAD

**Issue by mitchellslager** [ohmyzsh/ohmyzsh#11523]
### Describe the bug

I want to use a different directory for `$ZSH_CUSTOM`. According to [the documentation](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#using-another-customization-directory) this should be pretty simple.

But, for some reason my plugins don't immediately work when opening a new shell. It only works after I explicitly `source ~/.zshrc` again. All other customizations (`aliases.zsh`, `functions.zsh`) do work without sourcing.

This happens for all plugins. So not just the custom ones, but even the plugins which `oh-my-zsh` provides like `git` and `yarn`.

I have no clue why this is the case. The `plugins.zsh` file does get loaded when starting a new shell, so that's not the issue. Does anyone know why this does not work?

My `.zshrc` file is:
```
# Path to my oh-my-zsh custom directory
ZSH_CUSTOM="$HOME/.oh-my-zsh-custom"

# Path to my oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Source oh-my-zsh
source $ZSH/oh-my-zsh.sh
```

The structure of my `$ZSH_CUSTOM` directory adheres to the conventional file hierarchy. My plugins reside the `$ZSH_CUSTOM/plugins/` directory, and are loaded in a `$ZSH_CUSTOM/plugins.zsh`. My other customizations do work as expected, so without having to `source ~/.zshrc` each time when opening a new shell.

### Steps to reproduce

1. Copy `$ZSH_CUSTOM` directory to desired path.
2. Override original directory in `~/.zshrc` (`ZSH_CUSTOM="$HOME/.oh-my-zsh-custom"`)
3. Open a new shell

### Expected behavior

I would expect the plugins to immediately work when loading a new shell. So without having to `source ~/.zshrc` each time.

### OS / Linux distribution

macOS 13.2.1

### Zsh version

5.8.1

### Oh My Zsh version

9f9d3b7

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
The only place where `$plugins` can be defined is in `.zshrc`, or any place before `source $ZSH/oh-my-zsh.sh` is reached (.zshenv or .zprofile also work). `$ZSH_CUSTOM/plugins.zsh` is not a supported location where `plugins=()` can be defined.

If you need to do it this way for some reason (e.g. different hosts get different plugins) I suggest you to copy the plugin sourcing logic (from `oh-my-zsh.sh`) directly in the `plugins.zsh` file so that the plugins in `$ZSH_CUSTOM` are sourced by `plugins.zsh`.

If this is not what you are doing please describe fully this statement

> My plugins reside the `$ZSH_CUSTOM/plugins/` directory, and **are loaded in a `$ZSH_CUSTOM/plugins.zsh`**

**Comment by mitchellslager** [comment]
@mcornella thank you for the response. 

That is exactly what I was trying to do yes, but I am fine with just keeping the plugins directly in `.zshrc`.
