### ISSUE TITLE
oh-my size

### ISSUE THREAD

**Issue by massadm** [ohmyzsh/ohmyzsh#11538]
### If the feature request is for a plugin or theme, specify it here.

plugins/zsh-interactive-cd (1.5M), plugins/emoji (1.1M)

### If the feature solves a problem you have, specify it here.

Choosing which plugins to install. Especially for slim docker images.

### Describe the proposed feature.

`--with-plugin=zsh-interactive-cd --with-plugin=emoji, ...`,
or may be `--with-plugin-set=common-set  --with-plugin-set=extended-set`

**Comment by mcornella** [comment]
It is not feasible to move how the project is structured, which is as a full git project, in the short or mid-term. I would suggest you to use something like https://github.com/zplug/zplug.

Another option you have is to manually install [the zip file](https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.zip) and remove the folders you don't need, but that is going to mean updates will not work, as OMZ expects the folder to be a clean git repository without modifications in order to update.
