### ISSUE TITLE
Terminal freeze or not responding when pressing tab in a scp command

### ISSUE THREAD

**Issue by ychen-97** [ohmyzsh/ohmyzsh#11587]
### Describe the bug

Hi, I am currently on mac using oh-my-zsh in iTerm2 with only 2 plugins 
oh-my-zsh will freeze or cause iterm2 not to respond when trying to tab in a scp command for example, when typing the following and then press tab, it will freeze.
	-
	  ```
	  scp abc@xyz:/some/random/path/here
	  ```
	- I did some tests with commenting out `source $ZSH/oh-my-zsh.sh`. it is no longer there. Commenting out plugins like syntax-highlighting and auto-suggestions, it is still there.
	- Even different hostnames/addresses will result in different extents of delay: some are okay, but slightly slow, and some will be frozen for a longer time.
	- You can type without any delay, but as soon as you press tab and try to type, it will delay and become very slow
	-  I tested on both my mac with oh-my-zsh on, and it will reproduce.

### Steps to reproduce

- Type in the command line (don't press enter, and abc@xyz should be a real address, or it will not reproduce)
```
  scp abc@xyz:/some/random/path/here
```
- Press 'Tab'

### Expected behavior

iTerm2 will freeze and become not responding.

### OS / Linux distribution

macOS 13.2.1

### Zsh version

5.8.1

### Oh My Zsh version

master (c08b925)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
The completion function for `scp` calls ssh under the hood to get a list of files under the path specified. For example this is what it would run with `scp user@host:/`:
```
ssh -o 'BatchMode=yes' -a -x user@host command ls -d1FL -- '/\*'
```

This means that there needs to be a SSH connectivity and credentials, and it could freeze because of the ssh connection. You should check that you have good SSH connectivity when attempting to complete scp, or otherwise not use it at all.
