### ISSUE TITLE
Cannot save scratch buffer (fzf plugin)

### ISSUE THREAD

**Issue by greqov** [ohmyzsh/ohmyzsh#11657]
### Describe the bug

Hello there!
I guess there is an issue with fzf plugin. My goal is to edit a file from a fzf list. So I've added a binding `--bind 'ctrl-e:execute(micro {+})'`.

It works as expected for this workflow (without using a fzf plugin):
- type `fzf`, press `Enter`
- select a target file
- hit `Ctrl-E`
- edit a file in `micro` editor, save it

But it doesn't work if I use fzf plugin:

- hit `Ctrl-T` to run `fzf` (<-- the only difference)
- select a target file
- hit `Ctrl-E` to open an editor
- edit a file, save it.

Here at the last "save" step I've got an error `Cannot save scratch buffer`. For vim I will get an error `Vim: Warning: Output is not to a terminal`.
I use only 2 plugins: z, fzf.

### Steps to reproduce

1. Add a binding to edit a file from fzf list. Add `--bind 'ctrl-e:execute(micro {+})'` to `FZF_DEFAULT_OPTS` in `.zshrc`. Feel free to use any editor (`vim`, `$EDITOR`, etc).
2. Hit `Ctrl-T` to run `fzf`
3. Select a file, hit `Ctrl-E` to open it in an editor
4. Make some changes, save the file.

You'll get an error `Cannot save scratch buffer` for `micro` editor, or `Vim: Warning: Output is not to a terminal` from `vim` editor.

### Expected behavior

It should save a file with changes. The same way like it saves if you type `fzf` to call fzf (at the first step).

### OS / Linux distribution

Manjaro Linux

### Zsh version

5.9

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Did you figure this out? I can reproduce the issue, but I think it's because an editor is not supposed to be called within CTRL-T like that, or there must be some other way to do this.

I've seen this binding in [this example](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#log-tailing), but in there a redirection is done, so perhaps some file descriptor thing must be done?

In any case, I can't say this is our doing, the only difference is that CTRL-T is used, so I'd ask on the main repo. Let me know if you figure it out. Thanks!
