### ISSUE TITLE
omz changelog returns nothing

### ISSUE THREAD

**Issue by haabe** [ohmyzsh/ohmyzsh#11899]
### Describe the bug

Calling `omz changelog` returns nothing.

Calling `omz version` returns `master (cdd7dab)`, so I would expect the cdd7dab commit to be visible at least (`ci(installer): remove vc link which generates the wrong project`)

### Steps to reproduce

1. Open terminal
2. Update omz
3. Call omz changelog
4. See that nothing is returned

### Expected behavior

I expected to get a list of the latest commits

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/2988921/d699e51b-0abc-41ae-a171-f9691eb53593)

### OS / Linux distribution

MacOS 13.5.2

### Zsh version

master (cdd7dab)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by larson-carter** [comment]
Coming to chime in. Correct I am experiencing the same thing on macOS.

Oddly, I don't have a exact reason why the CLI is doing this...

I'm assuming the code is breaking here: [if [[ -z "$since" ]]; then](https://github.com/ohmyzsh/ohmyzsh/blob/cdd7dab5db4c668b962f908b57e244aa1ff4b574/tools/changelog.sh#L482), due to me already being up to date, and it trying to pull the last commit.

I haven't had time to do a trace to see where the "bug" is coming from, I'll do some testing and doing commits locally to see if it will pull changes and show me the git change log.

Picture for doc and source:

<img width="682" alt="Screenshot 2023-09-18 at 2 26 07 PM" src="https://github.com/ohmyzsh/ohmyzsh/assets/21244267/29d10714-9e15-4650-a190-9e908b98a275">

**Comment by carlosala** [comment]
It is an expected behaviour. In the changelog, only stuff regarding what affects the user. Only commits with `feat, fix, perf, docs, refactor, style` are shown. `build, chore, ci, test` are not shown since they do not directly affect the user.
Thanks for the report!
