### ISSUE TITLE
fix: kube-ps1 is not on display without touch $PROMPT

### ISSUE THREAD

**Issue by jjangga0214** [ohmyzsh/ohmyzsh#11894]
### Describe the bug

It seems `kube-ps1` plugin works only when `$PROMPT` is manually set.

```sh
PROMPT=$PROMPT'$(kube_ps1) '
```

Is this the intended design?

There was an issue: https://github.com/ohmyzsh/ohmyzsh/issues/7261.
And it's resolved, but the same thing happens again?

### Steps to reproduce

.

### Expected behavior

.

### OS / Linux distribution

macOS Ventura 13.5.2(22G91)

### Zsh version

zsh 5.9 (x86_64-apple-darwin22.0)

### Terminal emulator

Warp

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
The function needs to be added to the theme by the user. Different users might want it to be implemented differently. That [PR that you mentioned](https://github.com/ohmyzsh/ohmyzsh/pull/7269#issuecomment-472846872) was done to enable auto-disable (so that `$(kube_ps1)` prompts nothing) when a file exists in `$HOME/.kube/kube-ps1/disabled`, a file that is created executing `kubeoff`, and is removed executing `kubeon`.
Modifying `$PROMPT was never in the pipeline.
Thanks for the report!
