### ISSUE TITLE
Cannot autocompelete path

### ISSUE THREAD

**Issue by xiaobo-lab** [ohmyzsh/ohmyzsh#12014]
### Describe the bug

when i using "hdiutil detach xx", the path cannot autocomplete, but any other command is ok.

### Steps to reproduce

default theme and have no plugin.

### Expected behavior

should autocomplete path

### OS / Linux distribution

macOS 14.0

### Zsh version

5.9

### Terminal emulator

zsh

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
We do not modify `hdiutil` completion. From [zsh source code](https://github.com/zsh-users/zsh/blob/f36fccbb84e5d36ebdecede0c29e8e0c588336c9/Completion/Darwin/Command/_hdiutil#L5C1-L14), `detach` and `eject` seem only to accept disks, not paths. It is an expected behaviour, even though it's not in ohmyzsh scope.
