### ISSUE TITLE
web-search baidu 你好

### ISSUE THREAD

**Issue by ametoyuki098** [ohmyzsh/ohmyzsh#12061]
Hello Developer, as the title suggests, when I use "web-search baidu 你好" command, it shows y81o2BY29. I suspect this might be due to the lack of support for Chinese characters. I hope this issue could be resolved as soon as possible. This problem was observed while using Termux terminal. Thank you.

**Comment by mcornella** [comment]
I was able to reproduce the same on Termux.

This happens because the `omz_urlencode` function does not work correctly when there are no ASCII locales such as `C`, and Termux [only has a UTF-8 locale](https://github.com/termux/termux-packages/issues/546).

I pushed #12076 to work around this limitation. You can test it out with `omz pr test 12076`, it should work correctly but please confirm otherwise.
