### ISSUE TITLE
Expand command flags on TAB key

### ISSUE THREAD

**Issue by OleksandrKucherenko** [ohmyzsh/ohmyzsh#12107]
### If the feature request is for a plugin or theme, specify it here.

plugin or build-in feature

### If the feature solves a problem you have, specify it here.

decrypt short flags of the *nix commands to human readable names

### Describe the proposed feature.

Most of the *nix command support short and long names for flags, for example "-f" == "--force"

Idea is to provide feature that on specific key (why not TAB) convert prompt command flags from short notation to long names notations (and maybe on second TAB toggle it back to short notation).

```bash
# user input
git pull --prune --tags --rebase --force
# first TAB
git pull -p -t -r -f
# second TAB
git pull -ptrf
# third TAB
git pull --prune --tags --rebase --force
```

**Comment by carlosala** [comment]
That'd be pretty difficult to implement since most of that relies on third-party completion scripts, and not all of them link the two (short and long) versions of it, and not all commands accept joint short options.
It's a great idea, though, but the implementation seems nearly impossible, trying to code it as standard as possible, of course.
Thanks for the idea!

**Comment by OleksandrKucherenko** [comment]
we can start small, just a small POC (Proof of the Concept) for example just for GIT, or something like `find` command.

And after that other people will be able to contribute into such nice feature
