### ISSUE TITLE
Allow symlinked plugins

### ISSUE THREAD

**Issue by bogardon** [ohmyzsh/ohmyzsh#12156]
### If the feature solves a problem you have, specify it here.

I use my system's package manager to install zsh plugins, which by default installs into /usr/share. I tried to symlink to them from $ZSH_CUSTOM/plugins, but it doesn't appear to work.

### Describe the proposed feature.

Allow following symlinks when searching $ZSH_CUSTOM/plugins for plugins

**Comment by bogardon** [comment]
Nevermind I guess the right way is to just source the plugins directly and not do it through oh-my-zsh's custom plugin system.

**Comment by Apreche** [comment]
I ran into this exact problem today. I do not agree with the other user that we should never mind. 
It is desirable to install third party plugins using the system package manager because that will handle auto-updating them.
It is also desirable to configure them with omz for consistency and easier and cleaner configs. 
omz should follow symlinks in the custom folder.

**Comment by bogardon** [comment]
in my case my plugin was installed by my OS' package manager, so it will be kept up to date, just not through oh-my-zsh.
