### ISSUE TITLE
Previous commands (up arrow) only works after a small delay after pressing enter

### ISSUE THREAD

**Issue by marcospgp** [ohmyzsh/ohmyzsh#12197]
### Describe the bug

When pressing enter repeatedly to generate some empty lines in the shell (I do this for whitespace/readability), if one presses the up arrow to see previous commands right away, the command freezes on the first.

One then has to erase the command, after which pressing the up arrow works and goes through previous commands correctly.

If one waits for a small delay, the up arrow also works correctly.

### Steps to reproduce

See above

### Expected behavior

See above

### OS / Linux distribution

MacOS

### Zsh version

5.8.1

### Terminal emulator

?

### If using WSL on Windows, which version of WSL

None

**Comment by marcospgp** [comment]
Also if one holds the enter key, there is inconsistency in the line breaks - some have the shell prompt, some don't:

![image](https://github.com/ohmyzsh/ohmyzsh/assets/3464445/ff142ec0-ce6f-4d10-a008-dd218c71ffb2)

**Comment by marcospgp** [comment]
> Is it reproducible as well if you're not in a git repository? Try in `$HOME`, for example.

Yes, the up arrow being stuck on a single command yes, the incosistency in line breaks, no.

Also it might be a bit harder to reproduce due to the reduced delay when pressing enter, so requires faster timing than when on a git repo it seems.

Also I could not reproduce it with ctrl + c, just enter.

**Comment by carlosala** [comment]
The inconsistency is related to how the prompt is loaded (it checks `git status` before drawing).
That thing of pressing the up arrow, I can reproduce it as well. The problem is that the character sent to the terminal when the prompt is not drawn yet is `^[[A` instead of `^[[OA`, which in my case is the one that matches with `"${terminfo[kcuu1]}"`.
[Here](https://github.com/ohmyzsh/ohmyzsh/blob/43613d7b710f9a06971fac48dea3301bbc15b579/lib/key-bindings.zsh#L34-L51) we're setting that only for "${terminfo[kcuu1]}"`, and not `^[[A`.

**Comment by carlosala** [comment]
@mcornella what do you think about this? Should we bind as well `^[[A` to avoid this behaviour?

**Comment by mcornella** [comment]
I think terminal's application mode (smkx) is not yet ready when the prompt hasn't been drawn. If we bind a specific key sequence without using `$terminfo` we might have issues cross-terminal, i.e. when a different terminal emulator sends a different key sequence or the same for a different key combination.

We might be able to fix this one instance, but let's be vigilant for other issues. ñ
