### ISSUE TITLE
chsh: PAM authentication failed on Ubuntu 12.04

### ISSUE THREAD

**Issue by remyleone** [ohmyzsh/ohmyzsh#1224]
I'm using Ubuntu through travis-ci to test my dotfiles. I got the same error on my 12.04 when I installed oh my zsh after have followed the same steps.

After installing zsh (sudo apt-get install zsh) and change my shell successfully (sudo chsh --shell $(which zsh)), I still get an error from oh my zsh install.sh :
```
Password: chsh: PAM authentication failed
385         __                                     __  
386  ____  / /_     ____ ___  __  __   ____  _____/ /_  
387 / __ \/ __ \   / __ `__ \/ / / /  /_  / / **_/ __ \ 
388/ /_/ / / / /  / / / / / / /_/ /    / /_(**  ) / / / 
389_**_/_/ /_/  /_/ /_/ /_/\**, /    /**_/_**_/_/ /_/  
390                        /____/  
391
392
393 ....is now installed.
394sh: source: not found
395make: **\* [zsh] Error 127
```
The complete error stack is available at : http://travis-ci.org/#!/sieben/dotfiles

**Comment by Rafaelgfirmino** [comment]
Thanks @chrisjlee

**Comment by ldong** [comment]
Try this

```bash
echo $(which zsh) | sudo tee -a /etc/shells
chsh $USER -s $(which zsh);
```

**Comment by eeree** [comment]
@benjamine We can also use whoami to automatically add username to the end of a script:

    curl -L http://install.ohmyz.sh | sed -n '/chsh/!p' | sed -n '/env zsh/!p' | sed -n '/^\. ~\/\.zshrc/!p' > /tmp/oh-my-zsh-install.sh
    sh /tmp/oh-my-zsh-install.sh
    rm /tmp/oh-my-zsh-install.sh
    sudo chsh -s $(which zsh) `whoami`

**Comment by apjanke** [comment]
Hi folks. I think most of these are misdiagnoses. The main problem is that on Linux, `chsh` prompts for password when you're not root, and when installing with the form `curl ... | sh`, the shell's stdin is hooked up to the pipe containing `install.sh`, so when `chsh` prompts for a password, it's reading from the install script instead of the terminal and your keyboard. ([This AskUbuntu answer](https://askubuntu.com/questions/483873/error-password-chsh-pam-authentication-failure-when-try-to-install-oh-my-zsh/483925#483925?newreg=d06d189a70d7449aa0386dbae99d6805) nails it.) So that `chsh` command will work when you type it interactively, but not from within the installer script when invoked the way we do now.

A workaround is to use a temp file instead of a pipe for the install script. This will leave stdin attached to the tty for `chsh` to read from, and will work without changes to the script itself.

    curl -L http://install.ohmyz.sh > install.sh && sh install.sh

**Comment by apjanke** [comment]
Possibly better workaround: `sh -c` and subshell output capturing.

    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

Anyone want to give this a try and see if it fixes the Authentication Errors you were getting?

**Comment by brucardoso2** [comment]
@apjanke worked for me.
```
Linux mate 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zhiyelee** [comment]
`chsh -s $(which zsh) `  works well for me

**Comment by shmcgough** [comment]
@apjanke perfect solution

**Comment by jjgumucio** [comment]
@apjanke Thanks man! That was a flawless solution!
All others were indeed missdiagnoses

**Comment by ericreyes** [comment]
@ryaninhust you are a god

**Comment by rahulkale123** [comment]
ryaninhust's solution worked,tried on latest Ubuntu 16 terminal

**Comment by fulvio-m** [comment]
@ryaninhust solution's works well on Raspbian 8.0 aswell

**Comment by ryuchan00** [comment]
@ryaninhust This sokutions is very good ❗️

**Comment by welkinspring** [comment]
yep, this is a good guide for those who run into zsh disaster
