### ISSUE TITLE
Help me. I can't do anything.

### ISSUE THREAD

**Issue by HwangJS7817** [ohmyzsh/ohmyzsh#12268]
### Describe the bug

![image](https://github.com/ohmyzsh/ohmyzsh/assets/132746621/d148e392-758a-4033-b53f-915fc4709581)

![image](https://github.com/ohmyzsh/ohmyzsh/assets/132746621/4bc7d304-a613-438c-b532-cad628e255ef)

I installed an external theme for oh my zsh(powerlevel10k)
But, ubuntu shows nothing but "~".
And I also can't write simple commands like "cd desktop" cause there is no such directory.
How can I fix this problem?

### Steps to reproduce

I don't know.

### Expected behavior

I want to bring my username and commands back to normal.

### OS / Linux distribution

Ubuntu 22.04.3 LTS, Linux 5.15.146.1-microsoft-standard-WSL2

### Zsh version

5.8.1

### Oh My Zsh version

master (4fca7cc)

### Terminal emulator

Windows Terminal

### If using WSL on Windows, which version of WSL

WSL2

**Comment by mcornella** [comment]
Hi there, please note that powerlevel10k is not related to Oh My Zsh, the proper place to ask is on the official repository. 

However, this is an easy answer. What you are seeing is a prompt without username, and only showing the current directory path. In this case, `~` is shown because you are in your home directory, also abbreviated to a tilde character (`~`).

If you want to customize your powerlevel10k prompt to show other details, such as your username, you can use its configuration wizard: https://github.com/romkatv/powerlevel10k#configuration-wizard
