### ISSUE TITLE
gitfast duplicates the dirty state indicator, duplicated indicator doesn't respect GIT_PS1_SHOWCOLORHINTS

### ISSUE THREAD

**Issue by 13steinj** [ohmyzsh/ohmyzsh#12342]
### Describe the bug

See title, offending lines:

https://github.com/ohmyzsh/ohmyzsh/blob/605d76616aa47b2e5abe25eb26c4c9c1554f93d5/plugins/gitfast/gitfast.plugin.zsh#L9-L10

### Steps to reproduce

1. Set `GIT_PS1_SHOWDIRTYSTATE=1`; [Optional] Set `GIT_PS1_SHOWCOLORHINTS=1`
2. Enable plugin gitfast
3. go to a dir with a dirty git state

### Expected behavior

A single asterisk (or whatever the git-prompt.sh script decides) shown, with color respecting that of `GIT_PS1_SHOWCOLORHINTS`.

I'd argue it's relatively safe to just drop this double asterisk, I assume it was added long before the git/contrib people, and later @felipec  in their fork, added it to the core `git-prompt.sh`.

The only reason why this is an issue and not a PR is because I don't want to step on @felipec 's toes and I don't know how to provide a migration notice in the OMZ update banner/notes.

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/10525230/fd608044-a6e2-4075-983a-42427693bb2a)
The blue ANSI and bold marker was set by me in my theme as suffix (variation of xiong-chiamiov-plus).

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.9

### Terminal emulator

Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by felipec** [comment]
I don't understand what we are supposed to do here.

If the user has selected a theme with `ZSH_THEME_GIT_PROMPT_DIRTY`, then that is supposed to show. And if the user has turned on `GIT_PS1_SHOWDIRTYSTATE`, that's explicitly telling `__git_ps1` to show an asterisk on staged dirty changes:

> if you set GIT_PS1_SHOWDIRTYSTATE to a nonempty value, unstaged (*) and staged (+) changes will be shown next to the branch name.

You could argue `GIT_PS1_SHOWDIRTYSTATE` is superior to zsh's `parse_git_dirty()` because it also shows staged changed: you can have both staged and unstaged changes.

Are we supposed to ignore `ZSH_THEME_GIT_PROMPT_DIRTY`? I don't think so, a user might have selected a theme with a nice marker, or even set it themselves.

Are we supposed to turn off `GIT_PS1_SHOWDIRTYSTATE`? What if the user has disabled `ZSH_THEME_GIT_PROMPT_DIRTY` precisely to show that?

I think it should be up to the user to decide what to show in her prompt.

**Comment by carlosala** [comment]
I agree with Felipe, the user could customize it.
Thanks for the detailed explanation, and @felipec for your detailed response!

**Comment by 13steinj** [comment]
Sure, yes, and that's all fine. I was more-so concerned by the fact that the `gitfast` plugin still explicitly calls `parse_git_dirty` _regardless_, which means even if your theme turns `ZSH_THEME_GIT_PROMPT_DIRTY` off by setting it to an empty string.

When it comes to shaving off time for the prompt, I'd say any amount of time that can be shaved counts; yet at best with a short git config on my top of the line system, `git config --get oh-my-zsh.hide-dirty` takes 3-5ms.

Using the zsh builtins to check a variable  (maybe, that `GIT_PS1_SHOWDIRTYSTATE` is set to non-empty and `ZSH_THEME_GIT_PROMPT_DIRTY`) is empty/unset/set to the omz default is shaves off that time.
