### ISSUE TITLE
Call out during install that you must copy from old .zshrc

### ISSUE THREAD

**Issue by neko-dd** [ohmyzsh/ohmyzsh#12420]
### Describe the bug

The current install process does not make it clear enough that you need to copy anything from your backed-up .zshrc into the new copy that Oh My Zsh makes. Yes, it is mentioned in the documentation, but it is not prominent enough there, and it should appear on the command line (probably with a confirmation step to show that the user understands that this is happening.)

### Steps to reproduce

1. Install Oh My Zsh
2. Don't notice the italicized note in the README that says you have to copy things over
3. Be very sad next time you restart your terminal and a bunch of stuff is broken

### Expected behavior

During installation, Oh My Zsh prompts you to confirm that you understand you need to copy things from the backed-up copy of .zshrc if you want to keep them.

### OS / Linux distribution

all

### Zsh version

all

### Oh My Zsh version

current

### Terminal emulator

all

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hi! We're actually [echoing some messages](https://github.com/ohmyzsh/ohmyzsh/blob/a4424dfefd68e4d23badb2f86087184f9e06fab4/tools/install.sh#L330-L373) warning the user that we're overwriting the `zshrc`. Since `oh-my-zsh` is a framework (and not a library) it makes sense to start from scratch and then the user should append anything else needed.
In case you want to install oh-my-zsh without overwriting zshrc you can [set this variable](https://github.com/ohmyzsh/ohmyzsh/blob/a4424dfefd68e4d23badb2f86087184f9e06fab4/tools/install.sh#L30).
Thanks!
