### ISSUE TITLE
Broken update

### ISSUE THREAD

**Issue by kpeu3i** [ohmyzsh/ohmyzsh#12571]
### Describe the bug

Once I updated the lib using `omz update` I got merging errors in the agnoster theme (.oh-my-zsh/themes/agnoster.zsh-theme).

I decided to fix the issue by replacing the file on my machine with the file from the master branch. And now I have the following:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/1df85279-101b-443f-a234-d68aaffdbeeb">

As you can see `?` is used instead of arrows.

### Steps to reproduce

run `omz update`

### Expected behavior

correct symbols in the path

### OS / Linux distribution

macOS

### Zsh version

5.9

### Terminal emulator

Iterm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment]
Hello, this error message means there are git conflicts within the OMZ folder, perhaps due to code changes you have made yourself. If you don't have anything of value or changes you want to keep, you can remove them by doing the commands below:
```sh
cd "$ZSH"
git status && git diff # CHECK THE GIT CONFLICT CHANGES
```
If everything looks right, or you're unaware of any changes done, just run:
```sh
cd "$ZSH"
git reset --hard HEAD # THIS WILL REMOVE ALL CHANGES
```

**Comment by kpeu3i** [comment]
I resolved the conflicts by replacing the file, as I mentioned above but it won't help. Please reopen the bug
