### ISSUE TITLE
Consider not setting PUSHD_IGNORE_DUPS

### ISSUE THREAD

**Issue by robinovitch61** [ohmyzsh/ohmyzsh#12579]
### If the feature solves a problem you have, specify it here.

Ohmyzsh is awesome and fairly ubiquitous - enough so that on a moderate sized development team, you'll probably have some people using it and others using bare zsh or another shell like bash/fish.

It's also common for a development team to have operational scripts that do something like:

```zsh
#!/usr/bin/env zsh

scriptdir=${0:a:h}
otherdir=/tmp
userdir=$(pwd)

echo "user is in $userdir, script is in $scriptdir"

pushd -q $scriptdir

# ... do some stuff that requires being in the same directory the script lives

pushd $otherdir

# ... do some stuff that requires being in /tmp

popd -q
popd -q

echo "user is back in $(pwd) at script end"
```

This script might edit some environment variables, say PATH, that sets the developer up to use other tooling, so to run it in their current shell so the edits are persisted, they run:
```zsh
source repro.sh
```

But when invoking the script from the directory it lives in and when using ohmyzsh, they find themselves having changed directory unexpectedly after it completes. Other developers not using ohmyzsh do not - they find themselves in the directory they originally invoked the script from, as expected. This discrepancy causes confusion, frustration, and lost developer time.

The reason is because ohmyzsh sets the opt PUSHD_IGNORE_DUPS to true.

This makes the first `pushd -q $scriptdir` not do anything, since pushing the current directory onto the directory stack does nothing since the current directory is always the top entry of the stack.

It's not clear to me why setting PUSHD_IGNORE_DUPS would be desired. [This zsh guide](https://zsh.sourceforge.io/Guide/zshguide03.html#:~:text=Setting%20PUSHD_IGNORE_DUPS%20means%20that%20if,entry%20will%20be%20silently%20removed.) calls it out:

> Setting PUSHD_IGNORE_DUPS means that if you pushd to a directory which is already somewhere in the list, the duplicate entry will be silently removed. This is useful for most human operations --- however, if you are using pushd in a function or script to remember previous directories for a future matching popd, this can be dangerous and you probably want to turn it off locally inside the function.

Later, it gives an example where setting PUSHD_IGNORE_DUPS provides the ability to avoid "trick cycling", but this seems fairly esoteric, and my bet is that the issue I'm describing above is much more common than the issues solved by setting PUSHD_IGNORE_DUPS.

### Describe the proposed feature.

Can you consider not setting PUSHD_IGNORE_DUPS in ohmyzsh by default, and if you choose to keep it set, can you document why this is the choice? Thanks!

### Describe alternatives you've considered

Developers can individually unset the option if/once they know about it, or scripts can check for it, unset it if set, then reset it if it was set at the end, but this seems like a lot of work for something with unclear benefit in the first place.

**Comment by rwmitchell** [comment]
In your scripts you can use:

`setopt localoptions nopushdignoredups`

to get the desired behavior in scripts.

**Comment by robinovitch61** [comment]
> `setopt localoptions nopushdignoredups`

Hey @rwmitchell , thanks for your reply. Thumbs'd down in case others are looking for a quick answer for their scripts as this doesn't work - when the script is `source`'d as I mention above, `nopushdignoredups` is persisted, so the user's environment is changed.

I already mention the option of setting this per-script in `Describe alternatives you've considered` above. I'd like to keep this discussion about the title, why `PUSHD_IGNORE_DUPS` is the default and its benefits, if any, not how to work around it, which each org can (and has to) in its own way.

A colleague mentioned one benefit: when using with `AUTO_PUSHD`, then having `PUSHD_IGNORE_DUPS` set ensures:
* cd pushes every move to the directory stack
* AND popd always takes you somewhere that's not where you are right now

**Comment by robinovitch61** [comment]
As an aside, it looks like one way you can do it in your scripts in a way that preserves the user environment is:
```zsh
#!/usr/bin/env zsh

run() {
    emulate -L zsh  # <----- sets default zsh options for this function scope only
    scriptdir=${0:a:h}
    otherdir=/tmp
    userdir=$(pwd)

    echo "user is in $userdir, script is in $scriptdir"

    pushd -q $scriptdir

    # ... do some stuff that requires being in the same directory the script lives

    pushd $otherdir

    # ... do some stuff that requires being in /tmp

    popd -q
    popd -q

    echo "user is back in $(pwd) at script end"
}
run
```

**Comment by mcornella** [comment]
Hi Leo, thank you for reporting this.

I see the main issue that is causing this is that you are `source`ing your script. This will affect the local shell session, and also be affected by it. The usual method to run a script is directly, by spawning a new process, with `zsh script.sh` or `./script.sh` if execution permission is set.

The suggestion that @rwmitchell gave is almost correct, it becomes fully correct when all the script code is written within a function, such as you did afterwards. `emulate -L zsh` has the same behavior as `setopt localoptions`, and that the rest of options are set to their default. So for your use case, these are equivalent:

```
run() {
   emulate -L zsh
   setopt localoptions nopushdignoredups

   ...
```

If the `setopt ...` line is put at the top level then it does affect the rest of the shell session, as `localoptions` only has effect at a function level.

-----

With that said, the reason we have `pushd_ignore_dups` set is because it makes the most sense for an interactive session. Plugins such as `dircycle` and `dirhistory` allow you to cycle between opened directories, and with having duplicates in the directory stack, having to press the keyboard shortcuts twice because you're still in the same directory is bad UX and difficult to understand the reason for this, as it looks like it's actually broken.

Of course, for scripts this option is not recommended, because of what you've reported and the documentation you shared. However here the issue is that you're running your script within an interactive session. I think it's best you run the script as a script to ensure there are no other side effects, or if that's not possible for some reason, to use the function wrapper method. If you go the second option, make sure you make all variables `local` so as to not pollute the interactive session, and undefine all functions at the end of the script.

Hope this makes sense.

**Comment by mcornella** [comment]
Documented in the FAQ: https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#why-is-pushd_ignore_dups-set-by-default.

**Comment by robinovitch61** [comment]
> I see the main issue that is causing this is that you are `source`ing your script. This will affect the local shell session, and also be affected by it. The usual method to run a script is directly, by spawning a new process, with `zsh script.sh` or `./script.sh` if execution permission is set.

> However, if you are running it via source, which is not recommended

There are valid reasons for running a script with `source`, as an example, what I mentioned above: "This script might edit some environment variables, say PATH, that sets the developer up to use other tooling, so to run it in their current shell so the edits are persisted". You could instead have a script append to their `zshrc` or the like and tell them to restart their shell, but that's not always desirable.

> With that said, the reason we have `pushd_ignore_dups` set is because it makes the most sense for an interactive session. Plugins such as `dircycle` and `dirhistory` allow you to cycle between opened directories, and with having duplicates in the directory stack, having to press the keyboard shortcuts twice because you're still in the same directory is bad UX and difficult to understand the reason for this, as it looks like it's actually broken.

Thanks for explaining and documenting this. It makes sense. I don't use these plugins actively myself, but I'm sure many people do and they would be surprised if they started behaving differently in the case the `pushd_ignore_dups` default setting changed without their knowledge.
