### ISSUE TITLE
Git clone error while installing

### ISSUE THREAD

**Issue by MrSIHAB** [ohmyzsh/ohmyzsh#12578]
### Describe the bug

While I try to install Oh My Zsh, I get this error 

```
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
/home/sihab
Error: git clone of oh-my-zsh repo failed
```

### Steps to reproduce

install zsh, git, curl

run oh my zsh installation command from official website

### Expected behavior

Successfully should install oh my zsh

### OS / Linux distribution

Ubuntu Noble Numbat (24.04)

### Zsh version

latest

### Terminal emulator

GNOME Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment]
Hi Shoaib, thanks for the report.

This issue is outside of our control. What happens is a git error that needs to be fixed on your end. Here are some of the options you have:

- Set `git config --global core.compression 0` temporarily (the rest of the commands are already done by the installer) [^1]
- Check other things such as using a VPN or not, trying different a network, or other suggestions in [^2]

[^1]: https://stackoverflow.com/a/22317479

[^2]: https://github.com/orgs/community/discussions/48568#discussioncomment-5108608
