### ISSUE TITLE
Strange issue with Mac os x Terminal cursor with oh-my zsh

### ISSUE THREAD

**Issue by jagdishadusumalli** [ohmyzsh/ohmyzsh#1602]
I'm using Mac OS X 10.8.2 with commandlinetools xcode46cltools_10_86938131a. zsh 5.0.2 (from Home brew) with oh-my-zsh Ruby 1.9.3, Brew, rvm.

I have been facing a strange issue with terminal where in my cursor behaves strangely. When i do tmux or rails console command the position of cursor on terminal goes a few chars forward (Pls see attached image). The problem with this issue is when i use up key for command history or recursive command search (ctrl+r) the command characters get overlayed on each other confuse it to a wrong command. Causes issues more often when a command crashes or fails.

in rails console, when i press up arrow and go to previous command and the press ctrl+a to go to first character it only moves back upto 2nd character

I tried removing the zsh from homebrew and switched to system zsh v.4.3.11 but problem still persists.

The problem goes away when i disable the oh-my-zsh plugin in .zshrc file i need to use oh-my-zsh for many reasons...

please help.
![before](https://f.cloud.github.com/assets/1783043/148033/324e7b4c-74eb-11e2-8221-52dbdbdf9455.png)
![after in tumx](https://f.cloud.github.com/assets/1783043/148034/38978ec6-74eb-11e2-8e51-9a17773e27c5.png)
![rails console issue](https://f.cloud.github.com/assets/1783043/148036/4299b610-74eb-11e2-872e-5877f2b246ef.png)

**Comment by Akrasia** [comment]
This saved me so many headaches.. THANK YOU!

F.Y.I. ZSH uses .zprofile if anyone is looking to place the fix in their .profile

**Comment by olliebaum** [comment]
It might just be worth mentioning that if you still have the problem of a jumping cursor after exporting LANG and LC_ALL, some of your history entries may have a return character saved to them from before you made the change. This was the case for me. A quick edit of .zsh_history to remove the extra return characters fixed this.

**Comment by pmourelle** [comment]
Usign iTerm2 (osX), this fix didn't solve the issue (as I already had lang settings already in place).
Poking around in settings I got to uncheck "Use Unicode Version 9 Widths" and that made the trick. In case you find it worth it.
![image](https://user-images.githubusercontent.com/844554/36709201-66783528-1b55-11e8-9aff-97f7bd3f3607.png)

**Comment by JXDM** [comment]
If using gnu-screen, you may fix it with screen -U -S <name>. screen will use UTF-8 mode with -U option.

**Comment by EmandM** [comment]
Also adding my solution here as this took me an annoying amount of time to fix.

Turns out it was an issue with my custom prompt and an error I made when I ported my setup from bash to zsh.

Bash and Zsh both need to know the width of the command prompt to render things correctly. Anything in the prompt that doesn't result in text being printed needs to be escaped so bash/zsh knows not to count this piece as part of the prompt text length (this applies for any [`$(tput ... )`](https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html) commands or any [zsh visual modifiers](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Visual-effects)). An incorrect prompt length can lead to the weird prompt behaviours.

In Bash, the escape characters are `\[...\]` (e.g. `\[$(tput sgr0)\]` rather than `$(tput sgr0)` directly) [[More Info](https://mywiki.wooledge.org/BashFAQ/053)]

In Zsh, the escape characters are `%{...%}`. [[More Info](https://unix.stackexchange.com/a/90876/319716)]

When switching from bash, the new zsh prompt will print the square brackets that marked the escape characters in the bash prompt, and the non-text commands are no longer being escaped.

I fixed the issue by going through and ensuring all the non-text commands on my prompt were escaped correctly.
