### ISSUE TITLE
"title:8: parse error" when running $(some_command)

### ISSUE THREAD

**Issue by kerrickstaley** [ohmyzsh/ohmyzsh#2182]
Example session:

```
➜  ~  $(echo echo echo)
title:8: parse error
echo
➜  ~ 
```

**Comment by spacecowboy** [comment]
I am seing this exact error today with the current master.

**Comment by mcornella** [comment]
Can you please post the exact command that triggers this, as well as the
output of `which omz_termsupport_preexec` ?
—
Marc

**Comment by spacecowboy** [comment]
Forget what I said... It's all my fault. I rebased on master to fix this issue right now and incorrectly thought that opening new terminal windows would take this into account... Still using old code.

Starting an entirely new TTY uses the new code and the issue is fixed.

Thanks for the quick response!

**Comment by mcornella** [comment]
Cool. Cheers!
—
Marc
