### ISSUE TITLE
git completion fails when complete_aliases option is set

### ISSUE THREAD

**Issue by slhck** [ohmyzsh/ohmyzsh#2394]
I'm running zsh 5.0.4 on OS X 10.8 with oh-my-zsh `a38af27` with the `git` plugin. When I type `gco <TAB>`, I get the following output:

```
% gco zsh:12: command not found: __git-checkout_main
extegco
file
MIT-LICENSE.txt  custom/          log/             plugins/         themes/
README.textile   lib/             oh-my-zsh.sh     templates/       tools/
```

I've found the culprit to be the option `complete_aliases`. Once I turn it off, everything works as expected.

What gives? Is there any option clash? I haven't changed my `.zshrc` in ages, and I've always had `complete_aliases` on.

I don't particularly need this option but I guess there's some bug here.

**Comment by jessrosenfield** [comment]
Can anyone help me debug why I'm getting this issue? It happens with and without `complete_aliases` set. Also, removing `.zcompdump*` files doesn't fix it. My plugins are just set to `plugins=(git gitfast)`, however I get these issues with function completions (which is frustrating because I'd ideally use my own customized `gco` function instead of the git plugin's `gco` alias).
`ggl _git:12: command not found: __git-checkout_main`
`gdv _git:12: command not found: __git-diff_main`

I'm using Powerlevel10k on oh-my-zsh 173d4ca68f1ff4b04e9f3fd783244c309d848092, with zsh 5.8 (x86_64-apple-darwin19.3.0) and git version 2.26.1. Unfortunately ```brew uninstall --force git && brew install git --without-completions
``` is no longer an option with git.

Here is my definition of `_git`.
```❯ which _git
_git () {
	local _ret=1
	local cur cword prev
	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1
	if (( $+functions[__${service}_zsh_main] ))
	then
		__${service}_zsh_main
	else
		emulate ksh -c __${service}_main
	fi
	let _ret && _default && _ret=0
	return _ret
}```

**Comment by felipec** [comment]
@jessrosenfield It's because you are missing a patch. I'm not sure if you are using the latest ohmyzsh, but there was some mismatch and my patch got reverted:

[completion: zsh: improve main function selection](https://github.com/felipec/git-completion/commit/453c793c215ed1541caf94e48ff73ecd946d673f)

**Comment by jessrosenfield** [comment]
@felipec I updated but things still aren't working (my current issue #9018 is slightly different though)
