### ISSUE TITLE
Up-arrow search stopped working in OS X

### ISSUE THREAD

**Issue by EspadaV8** [ohmyzsh/ohmyzsh#2614]
Just performed the weekly update and it seems that 7adf66f9 has broken fuzzy searching using the up arrow. It looks like the other bindkeys are working though. Reverting the change re-enables fuzzy searching.

Without knowing anything about ZSH plugins and randomly removing lines, I tracked it down to line 15

`zle -N zle-line-init`

Removing that lets me fuzzy search again.

**Comment by joeyhoer** [comment]
I ran into this issue while attempting to enable `history-beginning-search-backward` or `up-line-or-beginning-search`.

This is directly related to the `zle -N zle-line-init` declaration in the `lib/key-bindings.zsh` file. Enabling the `safe-paste` plugin does resolve the issue, but only because it redeclares/overrides the `zle-line-init` keybinding with `zle -N zle-line-init _zle_line_init`.

It turns out that I was attempting to set key binding with `bindkey '^[[A'` and `bindkey '^[[B'`, but because of the `zle-line-init` declaration in `key-bindings.zsh`, the terminal was expecting a `terminfo` "capability". I found information on that in the [terminfo man pages](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man5/terminfo.5?query=terminfo&sec=5) and [ZSH FAQ](http://zsh.sourceforge.net/FAQ/zshfaq03.html).
