### ISSUE TITLE
Numeric PAD is not usable anymore on MAC OS X

### ISSUE THREAD

**Issue by remy-theroux** [ohmyzsh/ohmyzsh#2654]
Since last update of yesterday 24th March my numerical pad is not usable anymore in my shell.
All our team developers are in the same situation.

**Comment by leoderbois** [comment]
Hi ! This post fix the problem ! 
http://superuser.com/questions/742171/zsh-z-shell-numpad-numlock-doesnt-work

**Comment by castortech** [comment]
The solution from @philfreo worked for me, thanks

**Comment by volure** [comment]
I am on the macintosh. 
This worked for me
http://superuser.com/questions/449378/how-to-bindkey-altkey-in-osx

**Comment by koorb** [comment]
+1 for Unchecking VT100 in advanced preferences. 

Had the key mapping working for a bit but it caused strange issues in `vi` read about unchecking the "Allow VT100 application keypad mode" now keypad sanity is restored.

**Comment by doomsbuster** [comment]
I was wondering why the Num Pad wasnt working and i ran into this issue. The problem still persists.

**Comment by doomsbuster** [comment]
@volure you saved my day. Thank you very much. I mapped the following keys in my `.zshrc` and the numpad is active again.
```
# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[On" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * / =
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"
bindkey -s "^[OX" "="
```

**Comment by apjanke** [comment]
We should probably add these bindings by default in OMZ if we are going to be using `smkx` in `zle-line-init`. Otherwise, the numeric keypad is going to be broken by default on the command line. And going back to the numbers seems like the default most users would want.

We may not have a great way of doing this portably, though. The [`terminfo.src` file from ncurses](http://www.opensource.apple.com/source/ncurses/ncurses-42/ncurses/misc/terminfo.src) describes a couple layouts for the numeric keypad, with character sequences and capability names.

```
#   _______________________________________
#  |   PF1   |   PF2   |   PF3   |   PF4   |
#  |   $OP   |   $OQ   |   $OR   |   $OS   |
#  |_kf1__k1_|_kf2__k2_|_kf3__k3_|_kf4__k4_|
#  |    7         8         9         -    |
#  |   $Ow   |   $Ox   |   $Oy   |   $Om   |
#  |_kf9__k9_|_kf10_k;_|_kf0__k0_|_________|
#  |    4    |    5    |    6    |    ,    |
#  |   $Ot   |   $Ou   |   $Ov   |   $Ol   |
#  |_kf5__k5_|_kf6__k6_|_kf7__k7_|_kf8__k8_|
#  |    1    |    2    |    3    |         |
#  |   $Oq   |   $Or   |   $Os   |  enter  |
#  |_ka1__K1_|_kb2__K2_|_ka3__K3_|  $OM    |
#  |         0         |   .     |         |
#  |        $Op        |  $On    |         |
#  |___kc1_______K4____|_kc3__K5_|_kent_@8_|
```

However, I tried out a few terminal emulators, and there was some minor variation in the sequences they issued. And the terminfo entries on OS X don't have those capabilities defined; they may be missing elsewhere. So we couldn't use terminfo to do it portably.

We could just hardcode it, and live with a couple keys not working right in some terminals, leaving it up to users to tweak it if they really wanted to. Or start including supplemental terminal info in OMZ to patch up those discrepancies.

We might even want to rethink the whole `smkx` thing. It could be less work to handle the edge cases in cursor mode than to get everything working right in application mode.

Is there any interest in binding the numeric keypad keys to something besides numeric character entry?

**Comment by jklemm** [comment]
I'm have the same problem, but I'm using OS X El Capitan 10.11.3.

To solve, open the Terminal, and press `Cmd + ,`
Select `Profiles > Advanced Tab` and unmark the `something VT100` option.
Restart Terminal, and test it.

**Comment by shaharmor** [comment]
This should definitely be default

**Comment by kachkaev** [comment]
Surprising that this issue is still open after 2 years. Any plans on fixing it in one of the next updates?

What is the benefit of keeping the num pad not working? Or is this simply a bug that has not been looked at?

**Comment by christoga** [comment]
Yeah, I'm suprised. @kachkaev

**Comment by apjanke** [comment]
> What is the benefit of keeping the num pad not working?

It's tied in to the `smkx`/`rmkx` stuff that allows OMZ to use `terminfo` to do portable key mappings, instead of hardcoded key sequences (which don't work in all terminals) or maintaining OMZ's own terminal key mapping database. An unfortunate side effect due to terminfo's coarse granularity for keypad mode controls.

At this point I'm thinking the solution is to ditch smkx/rmkx.

**Comment by robbyrussell** [comment]
With these bigger changes, it's not straightforward to patch for everyone (without a lot of testing). Until we have a nice PR to go along with this, am going to close this and suggest folks refer to suggested solution:

https://github.com/ohmyzsh/ohmyzsh/issues/2654#issuecomment-217397498

**Comment by f-ricchiuto** [comment]
I don't know if it's the case to open a new issue, but I'd just like to point out that I'm using a cheap laptop which seems to have the enter key mapped as the numpad enter key. 

It taken a lot of time to me, to figure it out, as I noticed the problem after doing a lot of changes to the machine (fresh linux install). 

Idk why the manufacturer did this, and I've fixed the problem with this
``` bindkey -s "^[OM" "^M" ```

Anyway I've tried the #2654 fix, numpad keys are not working, but that's fine, mine is not a Mac. 

The most annoying thing of this problem is that's impossible to confirm while reconfiguring the kernel with ```make menuconfig```.

Yeah, I know, is not an operation that one does everyday. I wanted just to tell that there are pc manufacturers that are making weird keyboards out there, consider it :-)
