### ISSUE TITLE
Introducing "What's new" after upgrade

### ISSUE THREAD

**Issue by hfossli** [ohmyzsh/ohmyzsh#2971]
Upgrades happens quite frequently, but to the end user it is very unclear what actually changed and why one should upgrade. Having a changelog or a "what's new" chunk of text would be awesome.

**Comment by mcornella** [comment]
I agree with this, can somebody work on a proof of concept?

**Comment by Kriechi** [comment]
Somebody has to maintain this Changelog - and as it is there is plenty of other work already.
Reading through the git log should yield the same result.

**Comment by hfossli** [comment]
I'm just telling how I experience this from an end user perspective. I love oh-my-zsh and would love to get to know what's changed since last version. I see updates frequently, but I have no clue what's new. :) I don't think I would investing my time right if I were to browse git log each time.

**Comment by Kriechi** [comment]
Whats the difference between reading a changelog and reading the git log?
Its the same thing.

The only point I was trying to make is:
maintaining and collecting changelog entries is a lot of work - especially since Robby is the only one merging and actually committing. And since there are no real "versions" which get released it is hard to publish a list of changes.

Which again leads to the git log - everything is in there.

**Comment by hfossli** [comment]
There are currently 3019 commits and counting. All I'm asking for is a couple of headlines. If this feature request if it is not possible or not wanted you may close it. :)

**Comment by hfossli** [comment]
I think this project has some very valid points about changelogs https://github.com/olivierlacan/keep-a-changelog

**Comment by admpsktt** [comment]
@Kriechi I agree with your argument. I just want to note: [this post](http://keepachangelog.com/#why-can-t-people-just-use-a-code-git-log-code-diff-) makes some extremely good points in favour of keeping a Changelog. That said, this should definitely not be a priority for anyone capable of fixing other issues.

**Comment by hfossli** [comment]
We are not talking about opening a news apartment with 50 employees. Once a bugfix is done or a feature is added which you think people would love to know about – just add a line in the changelog.

**Comment by Kriechi** [comment]
You only have to read the last few commits - which are displayed after each update...
Keeping a changelog is always a good idea - don't get me wrong here.
But OMZ is a rolling release, no release cycle, no maintenance branches, no hotfixes.
Everything is just committed to master. And all of this by a single person (with help from the community to prepare PRs and stuff).

@hfossli:
> just add a line in the changelog

just read the git log line then - same thing.
And if you are really interested in something checkout the merged PR on GitHub.

If you, or anybody else, is willing to maintain a changelog - and Robby finds time or a different workflow to add this somehow - go ahead! I'm sure I would read it - if it provides a benefit over `git log`.

Most of the time after an update I look at the list of changed files - and see if something is of importance to me (plugins I am using)...

(everything is IMHO - maybe the rest of the OMZ community thinks completely different...)

**Comment by hfossli** [comment]
> just read the git log line then - same thing.
It is not the same thing.

I just don't see how this is that much work, 
but as stated earlier: if this is not possible or not wanted then just close this issue.

**Comment by admpsktt** [comment]
Let's leave this issue open; it should be 'on the radar'.

**Comment by robbyrussell** [comment]
"I just don't see how this is that much work"

It would require someone to keep track of what has been merged, keep some notes somewhere and then publish that on a regular basis. Since we haven't done it... I don't know think any of us knows how much time this would take. 

I'm not opposed to the idea, but this isn't something we can just get for free. Someone is going to have to invest time to maintain that. My plan has been to send out updates on new features/plugins through a mailing list, which you can sign up for here:

* http://ohmyz.sh/#mailing-list

My plan was to call out people who had made significant contributions there and encourage folks to thank them via that medium.

**Comment by hfossli** [comment]
Awesome. That is sufficient for me (as enduser). Some curated content wether it is in the form of mail or echo in terminal is both great. Two thumbs up.
