### ISSUE TITLE
Random theme picker should skip themes that rely on uninstalled commands

### ISSUE THREAD

**Issue by drielsma** [ohmyzsh/ohmyzsh#3036]
Feature request: The random theme picker should do some sort of check to determine whether a given theme has all the dependencies it needs, and skip themes for which this is not the case.

It's annoying to open a new shell and see something like
`Can't open perl script "/home/scp1/bin/foopath": No such file or directory`
or 
`prompt_jnrowe_precmd:3: command not found: zsh_path`

**Comment by apjanke** [comment]
I can't auto-detect which themes depend on uninstalled functions, but #3743 (and/or #3703) implements a user-defined "blacklist" which excludes themes from the `random` and `next` selection methods. That could fix this if you're willing to do some manual configuration.

Automatically detecting dependencies would take some sort of expansion of the theme definition format so the themes themselves can declare their dependencies. Naming them wouldn't be that hard: a couple array variables for command and plugin dependencies. But getting the theme loading code to be aware of them would be harder, since themes are designed to just be sourced in order to load in the theme. So you can't introspect them without loading them first.

There's also a dummy-function mechanism that a lot of themes use to get no-op implementations for plugins or commands that aren't present, so these become soft dependencies and the themes degrade gracefully when those are absent. If it's only a few themes with the bad behavior, maybe we could stub those out, too.

**Comment by apjanke** [comment]
The big offender here seems to be `rvm-prompt` and related Ruby versioning stuff. I put in #4588 which will clean most of those up.

If there are any other themes that have hard dependencies on optional programs, let me know, and we'll fix those too.
