### ISSUE TITLE
jump completion does not work on yosemite aka 10.10

### ISSUE THREAD

**Issue by bitboxer** [ohmyzsh/ohmyzsh#3235]
Somehow the completion for the jump command stopped working on yosemite aka 10.10 .

I tried to fix it and removing the `-e` in line 44 helps. But I have no clue what that thing did.

**Comment by wrecklass** [comment]
Well, it appears this may be because you are on OS X and not using homebrew. In GNU and on Linux readlink -e concanocalizes every link in the path, which may not mean much to most. The built in Mac version of readlink returns an error when -e is included. The authors may want to make sure which version of readlink is available in the plugin.
