### ISSUE TITLE
Screenshots for each theme

### ISSUE THREAD

**Issue by Mgldvd** [ohmyzsh/ohmyzsh#3267]
I took screenshots of each theme using the same image size and running the same commands, so you can actually see each theme.

Here the link

https://github.com/Mayccoll-Forks/oh-my-zsh

The command i use to open the terminal was:

``` bash
    gnome-terminal  --geometry=60x15
```

Here is an example

![](https://github.com/Mayccoll-Forks/oh-my-zsh/raw/themes/img/aussiegeek.png)

and the script i use for that:

``` bash
#!/bin/bash

THEMES=(
  af-magic
  afowler
  [......]
)

for ix in ${!THEMES[*]}
do
    echo "${THEMES[$ix]}"
    cd /home/uu
    sed -e "s/.*ZSH_THEME.*/ZSH_THEME=\"${THEMES[$ix]}\"/g" .zshrc > temp
    cd /home/uu
    cp temp .zshrc
    wait
    cd /home/uu
    gnome-terminal ~/.bashrc  --geometry=60x15
    sleep 4
    gnome-screenshot -w -f /home/uu/Pictures/"${THEMES[$ix]}"
    read -p "Press [Enter]"
done
```

I hope that is helpful

**Comment by andyfleming** [comment]
It would be nice to also include an example of a dirty git repo in the screenshot. A number of themes highlight when the repo has changes which is nice (and important to see in the screenshot, IMO).

**Comment by apjanke** [comment]
Nice! Let's pull these in.

We could put this up as another themes gallery on the Wiki, like https://github.com/robbyrussell/oh-my-zsh/wiki/Themes. But it might make more sense to add it to a `doc/` section in the main repo. That way the script to regenerate the screenshots could be included, and the screenshots for themes could be versioned along with the theme code, and be managed via PRs.

Downside would be increasing the installation size. Right now, `~/.oh-my-zsh` is a 4 KB installation. This change would make it about 9 MB (and that would go up as screenshots changed). That's a bit of a bummer, since there's no distinction between the OMZ repo and distribution.

Maybe just the script should be pulled in to OMZ, and then people can manually update the gallery? (Lame; should be completely automated.)
