### ISSUE TITLE
vi-mode plugin must be loaded first or it wipes out custom keybindings in other plugins

### ISSUE THREAD

**Issue by andrewferrier** [ohmyzsh/ohmyzsh#3435]
It would appear that if the vi-mode plugin appears in the list of plugins _after_ another plugin which defines a keybinding using `bindkey`, that keybinding is removed. Specifically, the keybindings I've observed this with are:

```
bindkey "^[[1;6D" insert-cycledleft
bindkey "^[[1;6C" insert-cycledright
```

(from https://github.com/mcornella/oh-my-zsh/commit/383ae2d4aa1c4fa90bf35cdd6e13598dacafa5b1).

This isn't documented anywhere (I believe), and isn't obvious. Perhaps there's a way to always logically sort vi-mode to the head of the list of plugins, irrespective of where it's defined? Or emit a warning if it isn't first?

**Comment by apjanke** [comment]
There's an attempt in #1629 to do this by defining a set of "special" keys which take precedence over other key bindings, and having `vi-mode` re-bind them. I'm not endorsing its approach, just putting an issue link here.

**Comment by apjanke** [comment]
Part of the issue may be that the `bindkey -e` and `bindkey -v` commands that `lib/key-bindings.zsh` and the `vi-mode` plugin use don't just set up key bindings. They set up links between *keymaps* and change which one is linked to `main` and thus the default.

From the [ZLE Builtins](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Builtins) section of the manual:

> bindkey’s options can be divided into three categories: keymap selection for the current command, operation selection, and others. The keymap selection options are:
>
>-e
>
>    Selects keymap ‘emacs’ for any operations by the current command, and also links ‘emacs’ to ‘main’ so that it is selected by default the next time the editor starts.
>-v
>
>    Selects keymap ‘viins’ for any operations by the current command, and also links ‘viins’ to ‘main’ so that it is selected by default the next time the editor starts.
>

This means that `lib` files, user custom files, and plugins loaded before `vi-mode` are modifying the `emacs` keymap, and plugins loaded after `vi-mode` (and the rest of your `.zshrc`) are modifying the `viins` keymap, which is now the default. You can observe this by looking at `bindkey -lL`

```
# Normal:
➜  .oh-my-zsh git:(master) bindkey -lL | grep main
bindkey -A emacs main

# With vi-mode loaded:
➜  ~  bindkey -lL | grep main
bindkey -A viins main
```

And then you have to consider the specific key bindings that `vi-mode` makes inside the `viins` keymap.

If you want all the various files that set key bindings to play nicer with each other, you might add a `$ZSH_INITIAL_KEYMAP` option to let the user select whether `bindkey -e` or `bindkey -v` is done initially in `lib/key-bindings.sh`. But that begs the question of whether those various files would work well with the `viins` keymap, or if they're just made to work with the current behavior of always starting with the `emacs` keymap. And it would impair the ability of the user to switch between the two at runtime. (Not a common case, surely, but it's something that's at least not actively interfered with now.) Most of the existing bindings look emacs-y.

**Comment by andrewferrier** [comment]
@mcornella @apjanke OK, thanks for the responses. I'm a little out of my depth on the keymap vs. keybindings issue, I have to admit. I was merely observing that as-is, it does look as if dircycle doesn't work if it is loaded in the "wrong" order w.r.t. vi-mode. How to fix this - well, I'm not sure.

**Comment by apjanke** [comment]
A "keymap" is a named set of key bindings. `zsh` maintains a few of them to switch between, depending on what you're doing.

I don't think there's an easy fix for this, because `vi-mode` and the other key binding stuff in OMZ grew kind of organically. Best you can do in the short term is have plugins that know they don't want to be clobbered by `vi-mode` check the `$plugins` list to see if `vi-mode` is being loaded after them. We could supply a function in `lib` that made that easy for the plugins to do. (And it could be added to later if other plugins were created that switched or clobbered the keymap like `vi-mode` did and needed to be checked similarly.)

Some other plugins add key bindings; they'd probably want to check for it, too.

```
➜  .oh-my-zsh git:(master) grep -rl bindkey *
lib/completion.zsh
lib/key-bindings.zsh
plugins/colemak/colemak.plugin.zsh
plugins/dircycle/dircycle.plugin.zsh
plugins/dirhistory/dirhistory.plugin.zsh
plugins/history-substring-search/history-substring-search.zsh
plugins/jump/jump.plugin.zsh
plugins/per-directory-history/per-directory-history.plugin.zsh
plugins/per-directory-history/per-directory-history.zsh
plugins/safe-paste/safe-paste.plugin.zsh
plugins/sudo/sudo.plugin.zsh
plugins/vi-mode/vi-mode.plugin.zsh
themes/dieter.zsh-theme
➜  .oh-my-zsh git:(master)
```

Alternately, we could just put the check in `vi-mode` itself, and have it check for a list of plugins known to add key bindings, and issue a single warning.

**Comment by billcarroll** [comment]
This apparently happens with plugins listed after vi-mode. I had to remove "vi-mode" from plugins in ~/.zshrc to get "history-substring-search" working again.

**Comment by apjanke** [comment]
`vi-mode` breaks `history-substring-search` for a different reason, the overriding of `zle-line-init`/`zle-line-finish`, which interferes with terminfo-based bindings for arrow keys; see #2735.

**Comment by Konfekt** [comment]
Had the same problem using either the vi-mode plugin or a snippet that changes the cursor shape according to the vi-mode on https://bbs.archlinux.org/viewtopic.php?id=95078 and does so by overriding `zle-line-init`. This pull-request fixes the issue and be merged without further hesitation.

**Comment by mcornella** [comment]
We have applied a number of changes lately, let me know if any issue you had is still present.

**Comment by Konfekt** [comment]
Ok, will do so as soon as the arrow keys (and not only that of the keypad) are taken into account (as discussed on https://github.com/robbyrussell/oh-my-zsh/issues/2735#issuecomment-164411323)

**Comment by mcornella** [comment]
:+1:

**Comment by varcharlez** [comment]
:) `plugins(vi-mode)` vs `set -o vi`

**Comment by mcornella** [comment]
@varcharlez can you specify? I interpret that means all works both with the `vi-mode` plugin and `set -o vi`, is that correct?

**Comment by Konfekt** [comment]
So I guess this pull request can be closed as it is my idiosyncratic `zle-line-init` that's causing the trouble? Maybe guard this as a work around for others that want a cursor shape indicating the vi-mode.

**Comment by apjanke** [comment]
No, I think this should stay open. It's an outstanding bug with our design. I don't think the recent fixes have changed this.

Konfekt - Your particular issue may have been about `zle-line-init`, but the original poster's underlying problem here remains: core OMZ switches to the `emacs` keymap when it starts up (with `bindkey -e`) and the `vi-mode` plugin switches to the `viins` keymap (with `bindkey -v`). So all bindings defined by the `lib/*` files (starting with `lib/key-bindings.zsh`) and by any plugin loaded before the `vi-mode` plugin get inserted in the `emacs` keymap, which is not what ends up as the user's default keymap, so they're effectively lost.

**Comment by varcharlez** [comment]
I can't decide whether to go with vi-mode or just regular set -o vi...

**Comment by apjanke** [comment]
Read through the `vi-mode` plugin (including its README) and see if you want the other stuff it supplies. In addition to doing `bindkey -v` (which is the same as `set -o vi` in `zsh`), it defines a few useful key bindings, adds a visual indicator for insert/command mode, and does a couple things to get vi mode to play well with advanced themes. If you use the `vi-mode` plugin, then you can also put it at the front of your plugins list if you want to use key bindings defined by other plugins. And you'll pick up other improvements that eventually get checked in to it.

On the other hand, `set -o vi` is simpler and fully under your control.

For most OMZ users, I think the `vi-mode` plugin would be the way to go.

**Comment by apjanke** [comment]
(Speaking of which, doing `set -o vi` yourself has the same "wipes out other keybindings" problem this issue is talking about in the first place, because you have to do it after OMZ is loaded, effectively at the end of the plugin loading sequence, and you get the exact same behavior of switching away from the `emacs` keymap after OMZ has added bindings to it.)

**Comment by vtronko** [comment]
What's the status of this?

**Comment by robbyrussell** [comment]
⌛️  Given how long this has been an issue with the design of Oh My Zsh, I don't see a clear path forward. We would welcome a refactoring approach for a future version of design that wouldn't make it so brittle with the ordering of plugins listed.

In the meantime, it seems like we just need to keep this topic around for people to know to experiment with reordering the plugins.
