### ISSUE TITLE
Option to ignore specific git repos for prompt

### ISSUE THREAD

**Issue by reacocard** [ohmyzsh/ohmyzsh#357]
I have my $HOME under git, for managing my various dotfiles.  However this means that the git status in oh-my-zsh's prompt displays for EVERY path in my home directory and all subdirectories thereof, which is quite silly.  Therefore I'd like an option to specify paths for the prompting to ignore, so that if the git repo happens to be at (not _under_, it needs to work for repos in subdirs of $HOME!) one of those paths, it will not be displayed in the prompt.

**Comment by kritzikratzi** [comment]
i _think_ this wasn't actually fixed. 

it seems this was marked as fixed, because the change was pulled in from this bug mentioned 
here https://github.com/sorin-ionescu/prezto/issues/357 which references the same commit https://github.com/sorin-ionescu/prezto/commit/1d0b0e2e9bfb7702c307c5e95b50f5b43d7ac380

https://github.com/robbyrussell/oh-my-zsh/issues/377#issuecomment-3671956
it seems this was a bigger change set overall, possible more bugs on this list didn't reference the correct numbers:

**Comment by mcornella** [comment]
@kritzikratzi it's actually implemented already: https://github.com/robbyrussell/oh-my-zsh/blob/192de6bcffb0294e19f4203f6f7dc1a7f3e427be/lib/git.zsh#L3

You have to `git config oh-my-zsh.hide-status 1` in each repository you want to hide.

**Comment by kritzikratzi** [comment]
oooh, sorry for the bother. never mind then :)

**Comment by niij** [comment]
@mcornella Marc, thank you for posting this here.  I've been looking for a while, and this is exactly the fix I was looking for!

**Comment by kevinquillen** [comment]
I had this same issue, after doing:

`git config --add oh-my-zsh.hide-dirty 1` it fixed it for me.
