### ISSUE TITLE
virtualenvwrapper get stuck in project root

### ISSUE THREAD

**Issue by domibarton** [ohmyzsh/ohmyzsh#4255]
Hi

When I enable the `virtualwrapper` plugin, I can no longer `cd` into subdirectories of my virtualenv-based project directories.

Here are my plugins:

```
plugins=(osx vi-mode tmux z sudo cp docker git python virtualenv virtualenvwrapper django web-search)
```

Now let's say I `cd` into my project root:

``` bash
cd ~/Documents/git/my-project/
```

The `virtualenvwrapper` plugin will automatically load my virtualenv, which is fine. But from now on, I can't change into subdirectories:

``` bash
cd ~/Documents/git/my-project/
pwd
# OUTPUT: /Users/dbarton/Documents/git/my-project/ 

cd some-subdir/

pwd
# OUTPUT: /Users/dbarton/Documents/git/my-project/ 
```

I'm stuck in the project root dir. When I disable the `virtualenvwrapper` plugin, everything seems to be working fine (except of loading the virtualenv automatically of course).

I'm working with Mac OS X and using the latest oh-my-zsh version (just updated it).

**Comment by domibarton** [comment]
I found the commit (f73e642e2265601b705b6aa9d9f71878ca98644a) which apparently breaks everything:

```
f73e642e2265601b705b6aa9d9f71878ca98644a is the first bad commit
commit f73e642e2265601b705b6aa9d9f71878ca98644a
Author: Andrew Janke <andrew@apjanke.net>
Date:   Thu Jul 2 21:42:32 2015 -0400

    virtualenvwrapper: treat git repos as project roots again (instead of requiring a .venv customization directory)
    Change error output to more conventional OMZ format, so it's clear the plugin is for oh-my-zsh and not base zsh.
    Use `local` variables instead of manual unsetting.

:040000 040000 aaff606436564cc39d54243f68b14eb1ebe807d6 c15af76eabd5075ac651e7dfca724ea267ec9993 M	plugins
```

**Comment by domibarton** [comment]
Here's how I can reproduce this issue:

```bash
mkproject foobar
# New python executable in foobar/bin/python
# Installing setuptools, pip...done.
# Creating /Users/dbarton/Documents/git//foobar
# Setting project for foobar to /Users/dbarton/Documents/git/foobar

git init .
# Initialized empty Git repository in /Users/dbarton/Documents/git/foobar/.git/

pwd
# /Users/dbarton/Documents/git/foobar

mkdir test
cd test
pwd
# /Users/dbarton/Documents/git/foobar

**Comment by domibarton** [comment]
I found the problem, so here's a more detailed description.

There's some logic in the ```virtualenvwrapper``` plugin, which will activate the virtualenv when it isn't activated so far:

```bash
        # Activate the environment only if it is not already active
        if [[ "$VIRTUAL_ENV" != "$WORKON_HOME/$ENV_NAME" ]]; then
          if [[ -e "$WORKON_HOME/$ENV_NAME/bin/activate" ]]; then
            workon "$ENV_NAME" && export CD_VIRTUAL_ENV="$ENV_NAME"
          elif [[ -e "$ENV_NAME/bin/activate" ]]; then
            source $ENV_NAME/bin/activate && export CD_VIRTUAL_ENV="$ENV_NAME"
          fi
        fi
```

The problem is within the first condition:

```bash
if [[ "$VIRTUAL_ENV" != "$WORKON_HOME/$ENV_NAME" ]]; then
```

The problem is the comparison is only working when ```$WORKON_HOME``` is defined without a trailing slash. If the user has defined ```$WORKON_HOME``` with a trailing slash (in fact this is what I did), then the comparison fails, because there's something like this:

```bash
if [[ "/some/special/path/to/.venv/foobar" != "/some/special/path/to/.venv//foobar" ]]
```

So I made a change that the trailing slash will be removed before the comparison. Please see the pull request #4258.

Cheers
Domi

**Comment by apjanke** [comment]
I can partially reproduce. When `$WORKON_HOME` has a trailing slash, it does redundant environment activations on every `cd`. However, I don't get "stuck" in the project root. (Here's my output with debugging code I threw in.)

```
➜  ~  echo $WORKON_HOME
/Users/janke/.virtualenvs/
➜  ~  cd tmp/test-venv
➜  test-venv  cd foobar
ENV_NAME = foobar
Activating environment
(foobar)➜  foobar git:(master) cd test
ENV_NAME = foobar
Activating environment
(foobar)➜  test git:(master)
```

Do you have some additional setup in your venvs or virtualenvwrapper configuration that affects cd'ing after a `workon` call?

That test you found with the slash-doubling problem looks like this issue. Maybe we need to go one step further, even: should the plugin maybe be calling `workon --no-cd` instead of plain `workon`? It seems like you wouldn't want to be re-cd'ed by a chpwd hook, regardless of the venv setup.

**Comment by apjanke** [comment]
(This might be breakage in my own `virtualenvwrapper` setup; `workon --cd` doesn't seem to work for me at all.)

**Comment by apjanke** [comment]
What version of virtualenvwrapper are you running?

```
➜  ~  pip list | grep virtualenv
virtualenv (13.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.6.0)
```

Looks like the `workon` cd behavior may have changed recently-ish: https://bitbucket.org/dhellmann/virtualenvwrapper/issues/246/project-dir-is-not-the-cwd-when

**Comment by domibarton** [comment]
Same `virtualenvwrapper` version, but an older `virtualenv`!

```
virtualenv (12.1.1)
virtualenv-clone (0.2.5)
virtualenvwrapper (4.6.0)
```

**Comment by mcornella** [comment]
Try enabling verbose and xtrace mode ("set -xv") and reproducing the same
behavior, that way you'll capture the running code that triggers it and
we'll be able to see it. To disable, use "set +xv".
—
Marc

**Comment by domibarton** [comment]
@mcornella have fun ;) https://gist.github.com/domibarton/4a43aed8d7aaf4401403

**Comment by apjanke** [comment]
Looks like [this](https://gist.github.com/domibarton/4a43aed8d7aaf4401403#file-changing-to-temp-subdir-L416-L436) is where it's happening. It's from the `post_activate_source` template in `project.py`, and is conditional on `$VIRTUALENVWRAPPER_PROJECT_CD`, which is supposed to be overridden on a per-call basis by `--no-cd`. I don't know why it's not showing up in the virtualenvs I create myself. (Maybe this is a venv created from an older version of virtualenvwrapper, so it's made from older templates or creation scripts?) But it looks like `--no-cd` is the right thing for the `workon` calls in the virtualenvwrapper plugin, otherwise, cd-ing from a dir outside a venv to a subdir under one would "bounce" you up to the project root.

@domibarton can you test that - try `cd /` and then `cd` directly to a dir a couple levels under a project root or venv?

**Comment by domibarton** [comment]
It can't be an older venv, because for the demo case I created a new venv with the `virtualenvwrapper` you see above.

I just tried to `cd /` and made sure no venv is loaded then `cd` directly into a subdir of my project root. No success :-1:

**Comment by rh0dium** [comment]
Yup I'm seeing this as well.  If there is anything I can do to help out or test let me know.

**Comment by apjanke** [comment]
I've put up a branch [venvw-fix-extra-cd](https://github.com/apjanke/oh-my-zsh/tree/venvw-fix-extra-cd) that includes @domibarton's fix for the trailing slash, and a couple of my own modifications:
* Uses `VIRTUALENVWRAPPER_WORKON_CD=0` to suppress the automatic extra `cd` that `workon` does
* Checks `$DISABLE_VENV_CD` on each chpwd, so you can turn it on or off during a session, instead of only during OMZ initialization
* Prints debugging output if you set `OMZ_VENVW_DEBUG=1`
* Refactors, mostly to separate the project-root/venvw detection from the actual chpwd hook, for easier interactive debugging and study. Run `_omz_venvw_locate_project_debug` to see what the plugin thinks the project and venv for your current directory should be.
* Adds a README

I think this change plus @domibarton's slash fix will be enough to fix the cd behavior. You guys want to check it out and test it? I can't fully verify it myself because I can't reproduce the original cd-bouncing behavior in my own venv setup.

The debug output also showed another weird behavior: if you are in a project dir and have the venv for it activated, and then you cd to another directory which is a project dir (a git repo, or a dir with `./.venv` present), but the virtualenv for that project is not defined (e.g. there's no venv with the same name as the git repo directory), then it will leave the old virtualenv active, not deactivating it or attempting to activate the new one. Seems like an oversight.
