### ISSUE TITLE
node version stucked at the terminal even after nvm deactivate

### ISSUE THREAD

**Issue by ayr-ton** [ohmyzsh/ohmyzsh#4336]
I'm using nvm at my system.

If I run `nvm deactivate` and `which node` for confirming I'm using the system node, the node version keep stucked in my terminal. For exemple:

```
ayrton@localhost ~/workspace/whatever/something-ng                      [14:27:12] 
> $                                                                ⬡ 0.12.7 [±develop]
```

Also, if I open a new terminal, this information keep stucked forever in my terminal:

```
ayrton@localhost ~/workspace/whatever/something-ng                      [14:30:07] 
> $                                                                ⬡ 0.12.7 
```

**Comment by apjanke** [comment]
What theme and plugins are you using? And what OS is this on?

**Comment by apjanke** [comment]
This appears to be by design, at least with the `bureau` and `mira` themes: the `nvm_prompt_info` function will always display the current `node` version if you have `nvm` installed for your user, even if no nvm is activated. The test it does is [just whether `~/.nvm/nvm.sh` exists, not whether nvm has activated anything](https://github.com/robbyrussell/oh-my-zsh/blob/9c08641d7c2aae0c82fa5ad91f94c67b70115ba5/lib/nvm.zsh#L3).

Wouldn't be hard to change it to only output the version info if you have a non-default `node` activated, and maybe additional nvm info. Thoughts? /cc @isqua (original author of `lib/nvm.zsh` and `bureau` theme).

**Comment by isqua** [comment]
Try fix from pull request “Changed determination nvm in system #2312”

**Comment by apjanke** [comment]
The new code in PR #2312 looks like it will still output the node version at every prompt, regardless of whether an `nvm` is active or not.

**Comment by apjanke** [comment]
Have a look at PR #4338. With that, you can now distinguish the default `node` from NVM-managed `node`s because it'll say "system" (or "none" if you don't have one installed) instead of the specific version number. Would that work for you?

![screen shot 2015-09-10 at 5 10 41 am](https://cloud.githubusercontent.com/assets/2618447/9784654/88ca2cc2-577a-11e5-8a45-a3a60e846cf2.png)

**Comment by ayr-ton** [comment]
I'm using bureau theme.

I will test the PRs, just a sec.
