### ISSUE TITLE
virtualenvwrapper plugin fail to deactivate virtualenv when parent directory is a git repository

### ISSUE THREAD

**Issue by gled-rs** [ohmyzsh/ohmyzsh#4603]
Consider the following directory layout:

/home/src
/home/src/gitrepo => git repository
/home/src/gitrepo/adirwithvirtualenv => a repository with a virtualenv ( either a .venv or else ).

When going from adirwithvirtualenv to gitrepo ( cd .. ), deactivate is not called because $ENV_NAME is filled with the name of the directory, as it is a git repository.

**Comment by gled-rs** [comment]
Pull request: #4604

**Comment by apjanke** [comment]
I think this is intended behavior. Git repos, even without venv-specific customizations, are considered to be project roots, so when this happens, it should switch you from the `adirwithvirtualenv` venv to the `gitrepo` venv. I think just calling `workon` without `deactivate` first will accomplish that. This change looks like it would end up fully deactivating the venvs in the example case. (Is that what it's intended to do? Or should `deactivate` just be called before activating the new environment?)

Have a look at the discussion in #4122, #4110, and #3918. There was a while when `virtualenvwrapper` did not consider plain git repos to be project roots, but this was a behavior accidentally introduced by #3918.

Maybe you'd want to add a setting that controls whether ordinary git repos are considered project roots? At any case, we should probably run this by the other `virtualenvwrapper` users before merging, since they've already had some unexpected behavior changes this year.

**Comment by gled-rs** [comment]
In my case, gitrepo is not a virtualenv. Hence the annoying behaviour.

But yes, it may be a change for some people, thanks for the headsup !

Pull request has been updated to add an option DEACTIVATE_VENV_ASAP to control that behaviour.

Without setting that option, the behaviour is the same as previously.

**Comment by apjanke** [comment]
Cool.

Maybe name it `VENV_DEACTIVATE_ASAP` so it's prefixed with the plugin name? We're starting to get a lot of config variables floating around, and that might help keep it organized.

**Comment by jayusa123** [comment]
What's the status of this issue? It would appear that this is a problem not only when the parent directory is a git repo but any time the destination directory of the cd command is. (see referenced issue above)

**Comment by jayusa123** [comment]
I just submitted a PR with my stab at this issue. I took a different approach which also resolves another issue (#5816). Any thoughts are much appreciated.
