### ISSUE TITLE
autoenv lookup folder need update

### ISSUE THREAD

**Issue by monkeyxite** [ohmyzsh/ohmyzsh#4681]
Via pip install autoenv, the activate.sh path would be "/usr/local/bin/activate.sh" for brewed python in mac 10.11, so suggest adding /usr/local/bin into searching path.

```
  for d (~/.autoenv /usr/local/opt/autoenv /usr/local/bin); do
```

**Comment by apjanke** [comment]
Good idea. Maybe along with the `~/.local` or `site.USER_BASE` location for `pip install --user`?

Are there methods of installing `autoenv` that install directly to `/usr/local` instead of `brew --prefix`? Or will `brew --prefix` cover it?

Any other possible installation locations we should be considering? And what should be the precedence order?

**Comment by monkeyxite** [comment]
how about the path based on "which activate.sh"?

**Comment by mcornella** [comment]
We can use the path where `activate.sh` is if we can find it, otherwise use the manual approach with all these `pip` directories. The first one can be obtained with:
```zsh
(( $+commands[activate.sh] )) && autoenv_dir="${commands[activate.sh]:h}"
```
The manual check of directories should be
```zsh
for d (~/.autoenv ~/.local/bin ~/Library/Python/bin /usr/local/bin /usr/local/opt/autoenv); do
```
according to [this answer on SO](http://stackoverflow.com/a/7143496) this should cover all possible locations of `pip install --user`, pending the `site.USER_BASE` one which I didn't understand. The order should be from local installation to system-wide, I think. And between system-wide pip or homebrew I don't think it matters very much (I put the pip one first for consistency).

Any other suggestion?

**Comment by apjanke** [comment]
Cool.

I think that `(( $+commands[activate.sh] ))` test will cover the cases of `/usr/local/bin`, too, since those will be on the user's path for normal installations. And if it's not, we should maybe treat that as the user not wanting them to be considered.

Checking `site.USER_BASE` directly probably is a blunt instrument. There's probably a better way of querying Python to see if and where a package is installed; maybe a `pip` command. That could handle relocations of the pip install directory away from the defaults, too.

Hmmm... something else to consider... if we're inside a virtualenv already, and that virtualenv has autenv installed, should it load autoenv from the virtualenv? Or should it only consider non-virtualenv autoenv installs?

**Comment by apjanke** [comment]
Here's a tentative PR: #4714. It uses the paths Marc suggested, except it relies on `$PATH` for picking up `/usr/local/bin`, and does `brew --prefix` to get the Homebrew install location instead of assuming it's `/usr/local`.

**Comment by apjanke** [comment]
While we're in here, what do you folks think about removing the big warning message that gets issued if it can't find autoenv? I find it convenient to have a single `~/.zshrc` file synced across all my machines, with a consistent plugin list. It's nice to be able to include plugins for things which may or may not be installed on a given system, and just have the relevant ones load.

Yeah, I could construct the list dynamically in `~/.zshrc` based on what's installed in the current system, but that's less readable, more work, and reproduces the installation detection logic that's in the plugins themselves.
