### ISSUE TITLE
vi-mode: how to custom the hotkey to enter normal mode?

### ISSUE THREAD

**Issue by roachsinai** [ohmyzsh/ohmyzsh#6968]
As the `README.md` metioned,

Use `ESC` or `CTRL-[` to enter Normal mode.

But for me `CTRL-Alt-T`, `CTRL-Alt-O`, `CTRL-Alt-N`, all change to `Normal` mode.

And I use `Manjaro + Gnome terminal`.

What happened? Thanks.

**Comment by manasjoshi14** [comment]
Were you able to solve this? 
Any key pressed with Alt would change to normal mode

**Comment by roachsinai** [comment]
No, but I find it's OK to leave it alone.

**Comment by mcornella** [comment]
The short summary is that this is going to depend on the key sequence that the terminal emulator sends when these key combinations are pressed.

I haven't been able to reproduce your issue on Gnome Terminal, but it should be possible to change some settings at the terminal emulator level so that `^[` is not sent.

You can view the actual key sequence sent to the shell when you run `cat -v` and press the key combinations that trigger this. For future reference, the key sequence used by the Escape key is `^[`.
