### ISSUE TITLE
Oh-my-zsh rpmostree plug-ins

### ISSUE THREAD

**Issue by hhlp** [ohmyzsh/ohmyzsh#7587]
What is it about?

rpm-ostree is a hybrid image/package system.  It supports "composing" packages on a build server into an OSTree repository, which can then be replicated by client systems with atomic upgrades.
Additionally, unlike many "pure" image systems, with rpm-ostree each client system can layer on additional packages, providing a "best of both worlds" approach.

Distro like Fedora, with SilverBlue has it.

https://ostree.readthedocs.io/en/latest/
https://www.mankier.com/package/rpm-ostree

Principal commands:

### `rpm-ostree status`

Will show you your deployments in the order in which they will appear in the bootloader, the first deployment in the list being the current default one. The ● shows the currently booted deployment.

### `rpm-ostree upgrade`

Will perform a system upgrade, creating a new deployment (root filesystem) and set it as the default for the next boot. You should use systemctl reboot shortly afterwards.

### `rpm-ostree rollback`

This rolls back to the previous state, i.e. the default deployment changes places with the non-default one. By default, the rpm-ostree upgrade will keep at most two bootable "deployments", though the underlying technology supports more.

### `rpm-ostree rebase`

You can use the rebase command to switch between these; this can represent a major version upgrade, or logically switching between different "testing" streams within the same release.

### `rpm-ostree install <pkg>`

Will download the target package, its dependencies, and create a new deployment with those packages installed. It is also possible to specify a local package which is not part of a repository.

### `rpm-ostree uninstall <pkg>`

To remove layered packages installed from a repository, use . To remove layered packages installed from a local package, you must specify the full NEVRA of the package.

### `rpm-ostree override replace`

replace base packages

### `rpm-ostree override remove`

remove Remove a package from the base tree. Note that this is similar to layering in that the original base is retained.

**Comment by mcornella** [comment]
What exactly are you suggesting here? It's not clear what you'd like the plugin to do.

**Comment by deekej** [comment]
I'm guessing the OP would welcome to have zsh autocompletion supporting the `rpm-ostree` commandy family. This also includes me, and that's how I found this thread - looking for `rpm-ostree` autocompletion in ZSH. :)

**Comment by mcornella** [comment]
`rpm-ostree` provides completion for bash: https://github.com/coreos/rpm-ostree/blob/35569278cb48b640fe3bcb29cf673bd64a76a3bf/completion/rpm-ostree.

If that is distributed alongside the `rpm-ostree` command, we can source that and it'll work out of the box since we run `bashcompinit` before (this allows zsh to run bash completions).

**Comment by carlosala** [comment]
Should we create a plugin for it?

**Comment by deekej** [comment]
@carlosala - I'm not sure if that's what needed here (sorry, I'm just regular BFU regarding the ZSH 🤣 ).
@mcornella - either resolution (sourcing / plugin) would be much appreciated. I'm getting the feeling that Fedora Silverblue is getting momentum (even I jumped on the bandwagon) and more and more people will use it in the future. And in Silverblue the `rpm-ostree` is de-facto replacement for `dnf` if you wish to install any kind of package directly to your system (and not using Flatpak), because sometimes you can't avoid it (e.g. for drivers).

**Comment by carlosala** [comment]
Is mandatory autoload `bashcompinit`? It should be autoloaded in `lib/completion.zsh` file, right?

**Comment by mcornella** [comment]
Closing this issue. It isn't our responsibility to write completions for open source projects, and it doesn't make sense to build one specifically from within OMZ when it would benefit the whole zsh ecosystem. My suggestion is that you ask directly on https://github.com/coreos/rpm-ostree.
