### ISSUE TITLE
Gradle plugin completions not working

### ISSUE THREAD

**Issue by marvi** [ohmyzsh/ohmyzsh#7946]
Fresh install of omz on Fedora 30. 

**To Reproduce**
1. Enable plugin 'gradle'
2. git clone https://github.com/jitpack/gradle-simple.git 
3. cd gradle-simple
4. ./gradlew [tab]

**Expected behavior**
Show list of tasks. Nothing is shown. 

**System:**
 - OS: Fedora 30
 - Zsh version 5.0.2: (x86_64-redhat-linux-gnu)
 - Terminal emulator: iTerm2 (ssh)
 - Gradle wrapper: Gradle 5.1.1 

**Additional context**
Same issue presents itself on CentOS 7. It does work on my Mac. Same .zshrc on all hosts.

git and docker plugins work.

I deleted zcomp files and got the same result.

[zsh5038gradlew1.txt](https://github.com/robbyrussell/oh-my-zsh/files/3316791/zsh5038gradlew1.txt)

**Comment by mcornella** [comment]
As the completion trace shows:
```
+_gradlew_tasks:3> _gradle_does_task_list_need_generating
+_gradle_does_task_list_need_generating:1> [[ ! -f .gradletasknamecache ]]
+_gradle_does_task_list_need_generating:1> [[ build.gradle -nt .gradletasknamecache || build.gradle.kts -nt .gradletasknamecache ]]
+_gradlew_tasks:6> cat .gradletasknamecache
+_gradlew_tasks:6> compadd -X '==== Gradlew Tasks ===='
```
the gradle task cache (`.gradletasknamecache`) is empty, and it is not recreated because it isn't older than `build.gradle`. You should wonder why it is empty: it is created from the output of `./gradlew tasks --all`.

If this prints tasks, then removing `.gradletasknamecache` will be enough, such that in the next completion trigger it is recreated and populated with the right tasks. If it doesn't print tasks, then there is something wrong with either `gradlew` or `build.gradle`.

**Comment by marvi** [comment]
Thanks, `./gradlew [tab]` works as expected, but not `gradle [tab]`. If I comment out `alias gradle=gradle-or-gradlew;` in `plugins/gradle/gradle.plugin.zsh ` everything works.

**Comment by mcornella** [comment]
We should add a compdef so that the `gradle-or-gradlew` function gets the appropriate completion, but this requires a bit more work since we don't have a generic function. For now, this might work (run it and let me know if it works):
```zsh
_gradle-or-gradlew() {
	if [ -f ./gradlew ]; then
		_gradlew_tasks
	else
		_gradle_tasks
	fi
}
compdef _gradle-or-gradlew gradle-or-gradlew
```

**Comment by marvi** [comment]
This seems to work fine. `./gradlew [tab]` and `gradle [tab]` do the same thing. Thank you.

**Comment by mcornella** [comment]
Hi @marvi, can you check if #7987 fixes it?
