### ISSUE TITLE
Wiki: Feedback request for my big update of the themes page

### ISSUE THREAD

**Issue by Kovah** [ohmyzsh/ohmyzsh#8078]
Hi there,

the current theme overview has a lot of interesting themes but looks quite chaotic. Screenshots are available in many different sizes, some with the terminal window, some not and - most important - every one with another color scheme. This makes it very hard to compare the different features and structure of the themes.

So, I reset my Terminal to default settings, started up Automator and generated standardized screenshots for almost all of the current themes.  
5 themes had issues with missing dependencies so I left them out for now.

#### Page Preview
👉 [**Preview of the page in a fork of the wiki**](https://github.com/Kovah/oh-my-zsh-wiki/blob/master/Themes.md)

#### Preview of a screenshot
![robbyrussell](https://user-images.githubusercontent.com/1816101/62960429-ebf9c880-bdfa-11e9-9d26-193d50ea34de.jpg)

#### Screenshot setup
The screenshots were generated on macOS Mojave (10.14.5) with the macOS Terminal app. The used theme is `Basic` with the default settings and colors. The font was switched to Fira Code at 13 pt to enable some special characters in certain themes. All terminal windows have a size of 100x31. I ran two short commands in a prepared folder with a pseudo project structure and Git enabled.

If you agree with the update I will merge my changes into your wiki. :blush:

**Comment by Kovah** [comment]
Any chance for a quick Go or No Go? 😊

**Comment by mcornella** [comment]
Hi Kevin, thank you for this. The thing is that each theme needs to present the different features it has, that's why I'm hesitant to go ahead with this. I realize preserving the steps of the old screenshots is a time-consuming task but it's an important part of showcasing each theme.

As per color-scheme and window size, perhaps we could enforce a particular size but the color-scheme is also part of what each theme author wants to show as the "best" option to go with that particular theme.

The resulting wiki looks better though, don't throw it away just yet.

**Comment by Kovah** [comment]
Thank you for the feedback. Totally understand the point and will think about a possible solution for that.

**Comment by Kovah** [comment]
So, I wrote a [blog post](https://blog.kovah.de/en/2019/generating-shell-theme-screenshots/) about the process and made both the [test files](https://github.com/Kovah/oh-my-zsh-theme-test) and the Automator script available. This way anyone (with macOS) can replicate the screenshots.

**Comment by mfdorst** [comment]
I for one am really glad you made this. I've often wished there were an apples-to-apples comparison of what these themes would look like on a basic black-background terminal.

I'm not sure if this is possible on the wiki page, but if there were a way to toggle back and forth between the "basic" and "custom" version of these screenshots, that might help address the issue. I think the current version should probably be the one shown by default, simply because when scrolling through your version of the wiki, none of the themes really stand out much from each other. However, once you've narrowed it down to two or three themes you like, it could then be really helpful to look at them side-by-side with an identical color-scheme.

**Comment by larson-carter** [comment]
@Kovah 
Do you think that you could join our discord server so we could continue working on this problem?

One of the things on our agenda is updating the wiki with new consistent screenshots.

**Comment by Kovah** [comment]
Sure, I joined already.

**Comment by Kovah** [comment]
Quick update for everyone: we discussed ways to improve the screenshot generation and the last idea way to pull theme-specific details out of the theme files to generate screens based on them. This is quite difficult. I proposed to add the current screens with the same features as a new wiki page aside the current theme page.

**Comment by mcornella** [comment]
Alright I put the new themes page as the default and linked to the old one from there. Thanks for your work and patience!

**Comment by Kovah** [comment]
Awesome!
Maybe you could add my repo with the screenshot generation files and guide at the bottom so everyone knows how the screens were generated.
https://github.com/Kovah/oh-my-zsh-theme-test

**Comment by mcornella** [comment]
[Done!](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#version-2019-08) Thanks again!
