### ISSUE TITLE
How to modify this mul-lines status?

### ISSUE THREAD

**Issue by xiaoqo** [ohmyzsh/ohmyzsh#8141]
I use "ys-themes", when I activate a envs by "conda activate base",  the string "(base)" monopolize a line. As follows:
(base)
 lyd @ P100-VM in ~/.oh-my-zsh/themes git:master x [10:06:59]

How to modify these to display in a line:
 (base) lyd @ P100-VM in ~/.oh-my-zsh/themes git:master x [10:06:59]

**Comment by mcornella** [comment]
`conda` prepends the environment to the PROMPT variable, so that if PROMPT is `"<user> @ <host>$ "`, after `conda activate base` it will be `"(base) <user> @ <host>$ "`.

The `ys` theme (not `ys-themes`) has a newline at the beginning of the PROMPT, so if you want to change that, you would have to follow the [customization of themes wiki section](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes) and modify the [`PROMPT=` line of the ys theme so it begins in the first line (delete the newline)](https://github.com/ohmyzsh/ohmyzsh/blob/6bebc254e88ac9b7fdaa7491d031f82ec107e418/themes/ys.zsh-theme#L49).
