### ISSUE TITLE
ls command is not working in Visual Studio Code, different aliases are loading...

### ISSUE THREAD

**Issue by raedwa01** [ohmyzsh/ohmyzsh#8149]
What is weird is that when I run a terminal in iTerm2, everything is running fine.  I execute the ls command (according to alias it is assigned to ls-G -G) and it runs fine.

When I open a shell in the VS Code Terminal for some reason, it still loads OMZ, but now ls is aliased to gls --color=tty -G.  It won't let me do an ls for anything not in a .git repository and the color is expected to be something other than tty.  

I have no idea why some slightly different profile is loading.

**Comment by mcornella** [comment]
This is set up in `lib/theme-and-appearance.zsh`: https://github.com/robbyrussell/oh-my-zsh/blob/ba57b5c7067821f114fc2075a19e7eca8b4d6c83/lib/theme-and-appearance.zsh#L9-L40

It uses `$OSTYPE` among other things to determine the final ls alias. Play with the commands to determine why that happens. It might be doubly aliased though somewhere in your zshrc file since both aliases have `-G` at the end.
