### ISSUE TITLE
Would you consider adding tipz plugin?

### ISSUE THREAD

**Issue by jesseleite** [ohmyzsh/ohmyzsh#8178]
**Is your feature request related to a particular plugin or theme? If so, specify it.**

Would you consider adding [tipz](https://github.com/molovo/tipz) as a bundled plugin?  It's a very handy zsh plugin that automatically suggests aliases when available.

![Screen Shot on 2019-09-27 at 00-44-27](https://user-images.githubusercontent.com/5187394/65742860-009ad300-e0c0-11e9-9e17-7e86ba6255e1.png)

**Comment by robbyrussell** [comment]
@jesseleite Sorry for the delay. We'd consider it if you ended up creating one for yourself, found it to be useful, and know that others would likely benefit from it. Otherwise, we don't "need" it unless someone speaks up as having a need for it.

Will close this for now and you're welcome to pitch a working PR at your leisure
