### ISSUE TITLE
"uninstall_oh_my_zsh" command not working properly

### ISSUE THREAD

**Issue by hazarek** [ohmyzsh/ohmyzsh#8252]
`uninstall_oh_my_zsh` command returns to **bash** instead of **zsh**.

reproduce steps;
- install oh-my-zsh
- run `uninstall_oh_my_zsh`

System;
Macos Catalina 10.15 with default zsh shell

I think it's because of this part. There is no .`shell.pre-oh-my-zsh` file in the home directory;

https://github.com/robbyrussell/oh-my-zsh/blob/687c50bdf999f8efd45f3c8f578a62329b0633da/tools/uninstall.sh#L28-L32

**Comment by mcornella** [comment]
This was added recently, meaning that if you installed OMZ previous to this change, the file wasn't created and the uninstaller defaults to going back to bash. You can manually return to zsh with `chsh -s $(which zsh)`.

**Comment by hazarek** [comment]
@mcornella I didn't install before the change. The issue took place 26 days ago. I tested it a few times. How do you close it without testing or getting answers?

**Comment by mcornella** [comment]
I assumed that based on your information,

**Comment by mcornella** [comment]
I assumed that based on the information that there wasn't a `.shell.pre-oh-my-zsh` file. The commit to save the previous shell was committed on June 3rd, 2019. Here's the bit that generates that file on install:
https://github.com/robbyrussell/oh-my-zsh/blob/52f58785645c18aa88ea515d070a42bcfe97508d/tools/install.sh#L197-L202

I see now that the file is deleted on successful change to `$old_shell`, so you may have had it before the uninstall:
https://github.com/robbyrussell/oh-my-zsh/blob/52f58785645c18aa88ea515d070a42bcfe97508d/tools/uninstall.sh#L34-L37

The whole thing could be improved, but the only explanation I can see is that (1) the shell saved was bash, due to `$SHELL` or the shell in `/etc/passwd` being bash; or (2) the file was deleted or never generated in the first place, and the uninstaller defaulted to bash.

As per 

> How do you close it without testing or getting answers?

it's a habit I've developed after not receiving any answer on giving a solution, making the issue open for months without response. Once we work through the old issues we'll add a stale bot to keep that from happening.

**Comment by hazarek** [comment]
@mcornella in my opinion file is never generated in the first place.  When I tested the shell script condition separately, the file was created.
```
 if [ -n "$SHELL" ]; then 
 	echo $SHELL > ~/.shell.pre-oh-my-zsh 
```
this way the file was not created. ;
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

maybe it may be related to write permissions.

**Comment by mcornella** [comment]
Right, this is the culprit: https://github.com/robbyrussell/oh-my-zsh/blob/52f58785645c18aa88ea515d070a42bcfe97508d/tools/install.sh#L143-L146

If the current shell is already zsh do not attempt to change. Therefore the shell is never stored and when uninstalling it will switch to bash. This is indeed a bug, I'll think of a fix tomorrow.
