### ISSUE TITLE
Git-prompt appears to the right in terminal

### ISSUE THREAD

**Issue by modestotech** [ohmyzsh/ohmyzsh#8379]
I've activated the `git-prompt` plugin, but it's stuck to the right part of the terminal. I get the same problem in macOS terminal and in tmux with macOS terminal.
![image](https://user-images.githubusercontent.com/31730051/68684184-593b0800-0568-11ea-8c25-2457ccab3e71.png)
I want to have it in the prompt to the left, instead of the current git segment of the prompt, which to me seems to be the intended default behavior. How do I achieve this?

.zshrc config below
```zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git git-prompt zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
```

**Comment by mattmc3** [comment]
@modestotech [The git-prompt plugin sets RPROMPT](https://github.com/ohmyzsh/ohmyzsh/blob/664664f6cd8a1c02a38063c8f2104f0515a19399/plugins/git-prompt/git-prompt.plugin.zsh#L90) so if you don't want it you'll have to unset it. Add `RPROMPT=""` at the end of your file after sourcing omz.

**Comment by mcornella** [comment]
The `git-prompt` plugin [defines the `git_super_status` function](https://github.com/ohmyzsh/ohmyzsh/blob/1761685d3e8d0594ff580c968874665e64a9a9cb/plugins/git-prompt/git-prompt.plugin.zsh#L89-L90) which is responsible for displaying the git prompt.

If you're using the robbyrussell theme, you can [copy it and customize it](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes), such that [instead of using the `git_prompt_info` function](https://github.com/ohmyzsh/ohmyzsh/blob/1761685d3e8d0594ff580c968874665e64a9a9cb/themes/robbyrussell.zsh-theme#L2), it uses `git_super_status`.

Reply if you need more guidance.
