### ISSUE TITLE
Virtualenv name not appearing on prompt

### ISSUE THREAD

**Issue by lays147** [ohmyzsh/ohmyzsh#8488]
I have made a fresh installation of zsh and oh my zsh and when I installed virtualenvwrapper and create a fresh virtualenv, the name of virtualenv is not appearing on the prompt as is used to on other machines. 

Added the plugin (virtualenv and virtualenvwrapper) to the zsh, no fix. 
Here is my profile: https://invent.kde.org/snippets/630

```
➜  ~ workon
aws
➜  ~ workon aws
➜  ~ deactivate
➜  ~ 
```

Any tips on how to fix this?

**Comment by snugglej** [comment]
What theme are you using? 

Some themes don't have the virtualenv wrapper part configured. For example amuse theme is missing the `$(virtualenv_prompt_info)` to display which virtual environment you are running.

**Comment by lays147** [comment]
Hi, I am using the default theme `ZSH_THEME="robbyrussell"`
Until before this install of oh-my-zsh I didn't have this problem with this particular theme.

**Comment by snugglej** [comment]
The robby russel theme doesn't have the virtualenv_prompt_info variable in it.

By default now it looks like the variable to disable the prompt through the standard python activate command is set to 1. Check this on your system by running `echo $VIRTUAL_ENV_DISABLE_PROMPT` 

See this issue about VIRTUAL_ENV_DISABLE_PROMPT for robby russel - #7985

You can try two things to see if it resolves your issue
1. Set the VIRTUAL_ENV_DISABLE_PROMPT variable to 0 in your .zshrc and see if that fixes your issue. From my understanding you will want to do that at the bottom of your .zshrc file.
2. Customize the configuration string for PATH in the robbyrussel config to include the virtualenv variables specified in the virtualenv plugin

**Comment by lays147** [comment]
@snugglej I have been using oh-my-zsh since 2015 and always with robby russell theme, and the name of the venv was always shown on the console. I don't know what happened that this feature no longer exists.

Your first suggestion with the `VIRTUAL_ENV_DISABLE_PROMPT` didn't work.
Could you clarify a little bit about the second one? 
Today my PATH is the following one: `/home/lays/.nvm/versions/node/v12.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/android/sdk/tools/bin:/usr/local/android/sdk/platform-tools/bin
`

**Comment by snugglej** [comment]
@lays147 

Did you take a look at the issue that I linked to you about VIRTUAL_ENV_DISABLE_PROMPT? Also 

1. What do you get when you do `echo $VIRTUAL_ENV_DISABLE_PROMPT`?

Sorry I did not mean $PATH, I meant the PROMPT variable in the THEME file
https://github.com/ohmyzsh/ohmyzsh/blob/d6474237b823448b3a1dd176a246ed73a30494f9/themes/robbyrussell.zsh-theme#L1-L2

2. What happens if you run `$(virtualenv_prompt_info)` on your terminal when in a python virtual environment?

If this returns what you expect, then I can help you adjust your theme PROMPT to reflect the necessary changes.

**Comment by snugglej** [comment]
@lays147 

I just tested with a base install from master of oh-my-zsh with `ZSH_THEME=robbyrussell` & `plugins=(git)` to see what would happen and it worked fine with the virtualenv showing up. 

![image](https://user-images.githubusercontent.com/17776110/79035635-1f594680-7b86-11ea-8e43-f68ee722ca8c.png)

So do you have virtualenv or the virtualenv-wrapper plugin added to your plugins?

**Comment by lays147** [comment]
Yes I do `plugins=(git docker git-extras ansible pip python ssh-agent tig virtualenv virtualenvwrapper)`.
I have uninstalled oh-my-zsh and installed again, no luck in there.
Could it be a problem with Konsole (KDE terminal)? Idk where to look =/

Also your second suggestion: 
```
➜  ~ workon locust 
➜  ~ $(virtualenv_prompt_info)
zsh: command not found: [locust]
➜  ~ echo $PROMPT
%(?:%{%}➜ :%{%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)
```

**Comment by snugglej** [comment]
The reason your not seeing the prompt is because of your plugins that you have added, the virtualenv one, specifically, is causing you to not see it by default. [Readme for virtualenv](<https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/virtualenv>) specifically talks about the variables you need to set in your theme.

## Option 1: ##

If you don't want to edit the theme file you will need to remove virtualenv (_you might also have to remove virtualenvwrapper too_) from your plugins and then restart your shell session. This will just use the default {virtualenv folder}/bin/activate script properly and the python environment will show up properly in your shell

## Option 2: ##

**In the robby-russel theme if you are going to use _virtualenv plugin_ you would need to:**
edit this: `PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"`
to be this: `PROMPT="$(virtualenv_prompt_info)%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"`

Also if you want to have a space after the virtual environment in your prompt I would add above the PROMPT configuration in the theme:
`ZSH_THEME_VIRTUALENV_SUFFIX = "] "`

**Comment by lays147** [comment]
@snugglej thanks. I used the first option and now works.
```
➜  ~ workon aws
(aws) ➜  ~ 

```
Thanks for helping me =D take care!
