### ISSUE TITLE
wget Unable to establish SSL connection

### ISSUE THREAD

**Issue by pengpn** [ohmyzsh/ohmyzsh#8515]
In my mac vagrant environment

```
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

return 
--2020-01-02 02:06:07--  https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.
Unable to establish SSL connection.
```

my openssl
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

and i can wget other https url but ohmyzsh can't not

**Comment by mcornella** [comment]
Make sure you have the latest CA certificates installed.

**Comment by stefango** [comment]
GFW works!

**Comment by mcornella** [comment]
If this turns out to be a **Great Firewall of China** issue, I stronly advise against using an unknown site instead, especially if you want to download things that you're going to run later, as is the case.

Instead, given that you can visit github.com, try downloading the ZIP of the repository (press the "Clone or download" button, then "Download ZIP"). Or you can try to git-clone the repository. You can also [access the web UI of the install script](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh) and copy-paste the contents of it into an install.sh script and run that.

**Comment by mcornella** [comment]
I'm going to close this since there was no follow up in 2 weeks.

**Comment by pengpn** [comment]
> If this turns out to be a **Great Firewall of China** issue, I stronly advise against using an unknown site instead, especially if you want to download things that you're going to run later, as is the case.
> 
> Instead, given that you can visit github.com, try downloading the ZIP of the repository (press the "Clone or download" button, then "Download ZIP"). Or you can try to git-clone the repository. You can also [access the web UI of the install script](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh) and copy-paste the contents of it into an install.sh script and run that.

@mcornella yeah, i tried you way and it was work. thx so much!
However i don't know why can not wget from that url .

**Comment by singhujjwal** [comment]
I have on my centos, I can do a wget of https://google.com but `wget https://github.com` fails with Unable to establish SSL connection. error.
All https websites working fine except github.com any idea ?
