### ISSUE TITLE
Autocomplete for `gem` command is slow and ignores locally built gems

### ISSUE THREAD

**Issue by HarlemSquirrel** [ohmyzsh/ohmyzsh#8570]
**Describe the bug**
Autocomplete for `gem` command is slow and ignores locally built gems

**To Reproduce**
- Navigate to directory containing one or more `*.gem` files
- Begin typing `gem filename`
- Press tab and wait for suggestions

**Expected behavior**
Autocomplete should suggest matching files with the `.gem` extension in the current directory or when providing a file path.

**Screenshots or recordings**
```
➤  ls                                   
Appraisals               awesome_print.gemspec  CONTRIBUTING.md  Gemfile.lock  init.rb  LICENSE  Rakefile   spec
awesome_print-1.8.0.gem  CHANGELOG.md           Gemfile          gemfiles      lib      rails    README.md

➤  gem install awesome_print
awesome_print                        awesome_print_carrier_wave_uploader  awesome_print_json                   awesome_print_motion               
awesome_print-carrierwave            awesome_print_colors                 awesome_print_lite
```

**System:**
 - OS: Arch Linux
 - Zsh version 5.7.1
 - Terminal emulator gnome-terminal

**Comment by mcornella** [comment]
Is this using the `gem` plugin?

**Comment by HarlemSquirrel** [comment]
I don't have it enabled as far as I know so I don't think so.

**Comment by mcornella** [comment]
The completion you're using is the default official one. Looks like for `gem install` [only remote gems are suggested](https://github.com/zsh-users/zsh/blob/ee1d622042015d9eb56bfd616163e82ffb7e5b4f/Completion/Unix/Command/_gem#L65). This ends up calling [`gem list --remote -q --no-versions`](https://github.com/zsh-users/zsh/blob/ee1d622042015d9eb56bfd616163e82ffb7e5b4f/Completion/Unix/Command/_gem#L324), that's why you experience the slowness.

You should report this bug to the [zsh-users mailing list](https://zsh.org/mla/).
