### ISSUE TITLE
Tab breaks prompt

### ISSUE THREAD

**Issue by TheKaur** [ohmyzsh/ohmyzsh#8574]
**Describe the bug**
Lately when I use TAB to complete a command, my prompt breaks. Pressing tab replicates some chars (first 2 chars of what I already typed) and after deleting all chars, those chars still stay. Attached screenshot to better capture it. 

**To Reproduce**
1. Type `cd <dir_starting_chars>`
2. Press TAB to autocomplete `<dir_full_name>`. You might need to press TAB again if there are more choices for `<dir_starting_chars>`.
3. See `cd` replicated before `cd <dir_full)name>`

OR
1. Type any command
2. Press TAB
3. See first 2 chars of command replicated. Press DEL to delete entire command but the 2 chars stay.

If I have a multiline prompt like in the avit theme, the prompt last line is cut off and the cursor is placed at pos 0.

**Expected behavior**
Prompt remains the same.

**Screenshots or recordings**
macOS single line prompt:
![Screen Shot 2020-01-28 at 5 15 44 PM](https://user-images.githubusercontent.com/7319619/73320183-5c52a580-41f3-11ea-8842-b4abef961f31.png)

Ubuntu multiline prompt:
![Screen Shot 2020-01-28 at 5 25 02 PM](https://user-images.githubusercontent.com/7319619/73320202-670d3a80-41f3-11ea-9cb4-a96ec6629fa7.png)

**System:**
 - OS: macOS Mojave 10.14.16
 - Zsh version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Terminal emulator: iTerm2 - Build 3.3.7

**Additional context**
1. I have been able to replicate this on a Ubuntu Ubuntu 16.04.4 machine with zsh 5.1.1 (x86_64-ubuntu-linux-gnu) with a fresh oh-my-zsh install. 
2. I only have `plugins=(git)` in my `~/.zshrc` in both mac and ubuntu

**Comment by mcornella** [comment]
Maybe you're using a `locale` that doesn't support UTF-8 characters, [see the FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command).

**Comment by TheKaur** [comment]
@mcornella THANK YOU SO MUCH!!! I filed this issue as a last resort after searching for answers online!
I had to do set `LC_CTYPE=en_US.utf8` from `LC_CTYPE=C`. Solved my issue!

**Comment by MarkValadez** [comment]
I know this thread is closed, but I wanted to add something since this is the first thing that pops-up and it took me a while to figure out for my case.

Some distributions might not have all locales generate, so is not enough to add the locales. In my case with the latest Ubuntu distro, I still had to run `sudo locale-gen en_US.utf8` as well as having `export LANG="en_US.utf8"` in my `.zshenv/.zshrc`.

This might not be the case for all if using `oh-my-zsh` fully, but in my case, I am using `antigen` with some `omz` plugins for added functionality. For `zsh-autocompletions` (+ other plugins) to work as expected in that case, without the tab breaking the prompt or letter repeats freezing, it is also important to include the `ohmyzsh/ohmyzsh path:lib` plugins.

May this help anyone who stumbles here after the fact as well.
