### ISSUE TITLE
Help with vi-mode in zsh

### ISSUE THREAD

**Issue by paranoid7** [ohmyzsh/ohmyzsh#8586]
https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode Tried using this plugin for zsh. vi-mode apparently works but the indicator does not. I am not using oh-my-zsh I just downloaded the plugin and sourced it manually in my .zshrc. Instead of the '<<<' symbol indicating normal mode I just get this: $(vi_mode_prompt_info) on the right side of the terminal. I usually read the manual and fix shit myself but in this case I just gave up. No matter what I do it just wont work. My .zshrc> https://pastebin.com/gBfiBcCh (I have commented vi-mode atm). Thanks for reading, any help would be appreciated.

**Comment by mcornella** [comment]
Try running `setopt prompt_subst`. This is one of the settings OMZ sets up by default.

**Comment by paranoid7** [comment]
That solved the issue! Thank you so much!

**Comment by mcornella** [comment]
Glad to help!

**Comment by benlieb** [comment]
This didn't work for me. Can someone post a full working example?

**Comment by mcornella** [comment]
Do you get have the same issue? If so just running `setopt prompt_subst` does work. Otherwise please describe in full detail your issue and how you're using the vi-mode plugin.

**Comment by benlieb** [comment]
Thanks for reaching out. I've also tried everything I can think of. 

And as you suggest I tried putting `setopt prompt_subst` in my `.zshrc` and nothing changed. Is that what you mean by "running"? Also tried that on the command line and nothing changed. 

I've spent about an hour on this twice now and it's extremely frustrating. Looking through the issue history, I'm not the only one. 

A full working example of actual code could save lots of people a lot of time. 

@mcornella are you the maintainer of the vi-mode plugin? Just adding this to the documentation would go a long way.

**Comment by mcornella** [comment]
What is your exact terminal output when you consider this not working? Is it showing `$(vi_mode_prompt_info)`, or is something else happening? Could you post your full zshrc file?

**Comment by benlieb** [comment]
I made some progress in the intervening time, but I think my BASH knowledge is limiting me at this point. I read the source code and see that the indicator only works "out of the box" if something else hasn't overwritten the right prompt:

```bash
# define right prompt, if it wasn't defined by a theme
if [[ -z "$RPS1" && -z "$RPROMPT" ]]; then
  RPS1='$(vi_mode_prompt_info)'
fi
```

But many themes overwrite that, including `fino`:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/634562/223447892-0b7696dd-f1be-4651-a5b4-8576380b252e.png">
I've been able to effectively replace the theme's `RPROMPT` with this:

```bash
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
MODE_INDICATOR="%F{red}norm%f"
INSERT_MODE_INDICATOR="%F{yellow}ins%f"

source $ZSH/oh-my-zsh.sh
RPROMPT='$(vi_mode_prompt_info)'
```

<img width="737" alt="image" src="https://user-images.githubusercontent.com/634562/223448746-96b340c5-bfe3-4e2f-a2c9-043ea7681c95.png">

But I'd rather just "add" to the current `RPROMPT`. I can't figure out how to do that. Presumably bash single and double quotes need to be appropriate. When I use single, they change the prompt every time, but I can't figure out how to "add to" the previous `RPROMPT` properly.

This

```bash
RPROMPT='$(RPROPMT) $(vi_mode_prompt_info)'
```

Gets:

RPROMPT='$(RPROPMT) $(vi_mode_prompt_info)'

And this:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/634562/223450117-67b33b25-3c51-4cfe-93dc-8a0f894ef451.png">

This:

```bash
RPROMPT='${RPROMPT} $(vi_mode_prompt_info)'
```

Gets:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/634562/223450707-46edb3f8-30b7-459c-a0cc-189f8c200780.png">

Etc...

It would be ideal if the plugin just did the right logic in the first place and account for any pre-existing prompt. Otherwise, actual working code in the docs would have been very helpful.

**Comment by mcornella** [comment]
Check that your issue is not covered by #10915.

**Comment by benlieb** [comment]
As I mentioned "When I use single, they change the prompt every time, but I can't figure out how to "add to" the previous RPROMPT properly."

So it "works" when I replace entirely the `RPROMPT` set by the theme.

My current obstacle is trying to get them both working, i.e. adding the vi-mode bit to the `RPROMPT` defined by the them. 

Seems like it shouldn't be hard and is probably a basic thing.

**Comment by mcornella** [comment]
Yeah, I sent my reply before seeing your update.

I agree that it should be documented in the README with an example.

You are almost close to getting it: you are hitting the traditional wall of using the correct quotes.

You can use **either** of these versions:
```
RPROMPT="$RPROMPT \$(vi_mode_prompt_info)"
RPROMPT="$RPROMPT"' $(vi_mode_prompt_info)'
RPROMPT+=' $(vi_mode_prompt_info)'
```

In the first two cases we are combining double and single quotes: double quotes expand the variable/subcommand so you get the actual value of the variable or subcommand, what we want as we need to preserve the contents of $RPROMPT. 

Single quotes use the literal string without expansion (we want the vi_mode_prompt_info function to be called every time the right prompt is shown).

I'll note down that we need to add an example of this on the README, but feel free to submit a change yourself if you feel like it.

Thanks again!

**Comment by benlieb** [comment]
Done https://github.com/ohmyzsh/ohmyzsh/pull/11548
