### ISSUE TITLE
ZSH base64 encode Bug

### ISSUE THREAD

**Issue by SneakyTurt1e** [ohmyzsh/ohmyzsh#8611]
**Describe the bug**

When performing Base64 encoding, ZSH will incorrectly encode '\u' as 'AA =='

**To Reproduce**
```bash
~ root@hostname
❯ echo -n '\u' | base64
AA==
```

**Expected behavior**

```Bash
root@hostname:~# echo -n '\u' | base64
XHU=
```
**Screenshots or recordings**

Nothing Here
**System:**
 - OS: Debian
 - Zsh version : zsh 5.7.1 (x86_64-debian-linux-gnu)
 - Terminal emulator: Xfce Terminal ,GNOME Terminal

**Additional context**

**Comment by mcornella** [comment]
`bash` doesn't have an echo builtin, that's just the echo command. If we pass these commands to `xxd` we can see which code-points they output:
```
zsh$ echo -n '\u' | xxd
00000000: 00                                       .
zsh$ /bin/echo -n '\u' | xxd
00000000: 5c75                                     \u
```
Zsh treats `\u` as `\u0`, because it accepts unicode endpoints, while `/bin/echo` treats it as a literal backslash and letter u. I don't think this constitutes a bug, rather a difference in functionality. I think in bash, if you need to use a unicode endpoint you have to use `printf`. Either way, if you think this should be different you can ask in the [zsh mailing list](http://zsh.org/mla).
