### ISSUE TITLE
autocompletion not working for some commands

### ISSUE THREAD

**Issue by manfredlotz** [ohmyzsh/ohmyzsh#8643]
This is Fedora 31 and zsh 5.7.1

I have the same zsh config on 3 different systems.

On one system completion works as well for `/usr/share/zsh/site-functions`. On other two it doesn't. 

I observed that on the system where it works env var `FPATH` is defined. The others don't have `FPATH` defined.  Env var `fpath` is defined on each system.  Interestingly, `/usr/share/Modules/init/zsh-functions` is in `fpath` on the system where it works but not defined on the other systems. 

Any idea how I can debug this?

**Comment by mcornella** [comment]
When you say "env var `FPATH` is defined" or "not defined", do you check that by looking at the output of `export`? Because, even if it isn't shown in the output of `export`, it should exist anyway when doing an echo, the only difference being that it isn't exported, [because `$FPATH` is just a mirrored variable of `$fpath`](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-FPATH), only being a scalar string using colon as a separator:
> In cases where there are two parameters with an upper- and lowercase form of the same name, such as path and PATH, the lowercase form is an array and the uppercase form is a scalar with the elements of the array joined together by colons. These are similar to tied parameters created via ‘typeset -T’. The normal use for the colon-separated form is for exporting to the environment, while the array form is easier to manipulate within the shell. Note that unsetting either of the pair will unset the other; they retain their special properties when recreated, and recreating one of the pair will recreate the other.

You say these are 3 different systems, using the same config. I assume you mean they all have the same zshrc, but they're not necessarily using the same global `z*` files right? You'd find these global ones in `/etc/zsh/*`. Post the details of these 3 systems (OS, version, platform, zsh version), and whether completion does work on them or not.

Also, it's not clear what you mean by "autocompletion not working". Is it not working for all commands?

**Comment by manfredlotz** [comment]
Two of those systems are Fedora 31 and zsh 5.7.1 In /etc all three zsh related files are the same on both systems (checked by sha256sum)

```
/etc/skel/.zshrc
/etc/zshenv
/etc/zshrc
```
On one system completions works ok for everything, on the second systems all completion definitions which are located in `/usr/share/zsh/site-functions` do not work.

**Comment by manfredlotz** [comment]
I assume that this is no problem with oh-my-sh but a problem between my keyboard and chair. So, I need to get some ideas how to best debug this.

**Comment by manfredlotz** [comment]
Regarding the vars I checked like this: `env |grep -i fpath`.

Doing echo for both vars show that on both systems `fpath` and `FPATH` are defined. And on both systems `/usr/share/zsh/site-functions` is part of the given vars.

**Comment by mcornella** [comment]
If the directory is in `$fpath` in both, this is a case of the completion cache file being old. See the FAQ for [how to reset the completion cache file](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reset-the-completion-cache).

**Comment by manfredlotz** [comment]
Yes, that was it. The completion cache ( I have to admit I didn't realy know about it) was old. Thanks a lot for your help.

**Comment by mcornella** [comment]
This is another thing that should be covered by the FAQ, thank you.
