### ISSUE TITLE
Setting zsh options in plugin zsh script

### ISSUE THREAD

**Issue by rgoldberg** [ohmyzsh/ohmyzsh#8736]
I need to have the extendedglob zsh option active in a plugin zsh script.

Currently, extendedglob is already active when my zsh script runs, even though extendedglob isn't set in my zsh terminal (command line).

Does ohmyzsh set it?

Is ohmyzsh guaranteed to set it in all future versions, or should I run `setopt extendedglob` in my script to future-proof it?

If my script runs `setopt extendedglob`, should I do something to scope the setting to my script (like setting the option back to the value it had before my script ran), or does zsh / ohmyzsh ensure that my setting won't leak out to other contexts?

Thanks.

**Comment by mcornella** [comment]
It's best to set it in the script.

RE: turning it back off, if the script is executed (i.e. `./script.sh` or `zsh script.sh`) you won't mess with anything else because it will only be active within the zsh process.

If the script is sourced, you can put it inside a function and use `setopt localoptions extendedglob`, or `emulate -L zsh` and then `setopt extendedglob`. `localoptions` makes the options set only live within the function in which its run. `emulate -L zsh` does the same but also sets `setopt localtraps`.

To put it inside a function, you can do the following:
```
function {
  # this code here is running in an anonymous function, you can setopt localoptions here
}
```
See [anonymous functions](http://zsh.sourceforge.net/Doc/Release/Functions.html#Anonymous-Functions).
