### ISSUE TITLE
Documentation for writing a plugin

### ISSUE THREAD

**Issue by VladimirMikulic** [ohmyzsh/ohmyzsh#8761]
Hi!
I was planning to write a plugin that would provide autocomplete for Google's App Script CLI, but there is no documentation on how the plugins are written. Even Google is speechless!

**Comment by mcornella** [comment]
Since you're asking specifically for completion, [this is a good guide](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org) for users that know a bit more about zsh. Completion scripts in zsh are quite hard to wrap your head around, but looking at existing completion scripts might be useful.

Then, if you want to write a plugin for OMZ, the structure is the following:
```
$ZSH
\--plugins
   \--<plugin_name>
```
and then inside that plugin_name folder, either a `_<plugin_name>` file (which contains completion scripts) or a `<plugin_name>.plugin.zsh` file, which can contain anything, including a completion function.

**Comment by VladimirMikulic** [comment]
@mcornella this is very helpful. Thank you very much for this resource.

**Comment by mcornella** [comment]
Glad to be of help 👍
