### ISSUE TITLE
Breaking battery update on commit 3da469be

### ISSUE THREAD

**Issue by guydunigo** [ohmyzsh/ohmyzsh#8804]
**Describe the bug**

I just updated oh-my-zsh to the latest commit and now I experience a problem during in my prompt:
there is an added visual space at the beginning of the input (but not actually in the typed command), and when I press tab, this extra space moves from the beginning of the input to the cursor, thus shifting the display of what I type from what is actually typed.
(Sorry if that isn't really clear ;) ) 

I did some digging and the problem apparently comes from the commit 3da469be six days ago modifying the default battery charging symbol string from `'⚡'` to `'%%{%%G⚡%%}'`.
Overriding `BATTERY_CHARGING_SYMBOL` to `⚡` (the original value) fixes the bug.

**Desktop (please complete the following information):**
 - OS / Distro: Arch Linux
 - Latest ohmyzsh Update?: Yes (after commit 3da469be)
 - ZSH Version: 5.8
 - Terminal emulator : urxvt

**Additional**
My relevant part of my theme configuration for the battery module and RPROMPT:
```shell
BATTERY_GAUGE_PREFIX=%F{blue}'[';
BATTERY_GAUGE_SUFFIX=%F{blue}']';
RPROMPT=$'$(battery_level_gauge)'
```

**Comment by mcornella** [comment]
Try `upgrade_oh_my_zsh`, there was a later change.

**Comment by mcornella** [comment]
I changed that because it had the exact opposite problem as you in Microsoft Terminal, and the `%{%G%}` sequence fixed it (characters inside `%{%}` are said to occupy no space, `%G` says it will occupy exactly one character-width, see [Prompt Expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html)).

The Microsoft Terminal is still in beta, so it's possible that it doesn't correctly handle UTF-8 characters, while other terminals do. I'll revert that change for now and override `BATTERY_CHARGING_SYMBOL` in my system, hoping at some point that change isn't needed anymore.

**Comment by guydunigo** [comment]
Actually, I just noticed it was doing this bug only in tmux and screen, so it's maybe due to `TERM` being `screen-256color`, if that helps.
