### ISSUE TITLE
Oh My Zsh aliases override .profile aliases

### ISSUE THREAD

**Issue by mcandre** [ohmyzsh/ohmyzsh#8933]
**Describe the bug**

Oh My Zsh defines a bunch of aliases that I don't want, when I already define these in .profile for use with zsh, bash, sh, and ksh.

**To Reproduce**

1. Define `ll` in `$HOME/.profile`
2. Source `$HOME/.profile` from `$HOME/.zshenv`
3. Install Oh My Zsh.

**Expected behavior**

My aliases aren't messed with.

**Observed behavior**

Oh My Zsh aggressively overwrites many aliases, without bothering to check if these are already defined.

Please offer an opt-out environment variable to disable Oh My Zsh from defining these aliases. Really annoying.

**Comment by mcornella** [comment]
If you're sourcing `.profile` from `.zshenv`, you might consider doing it in the zshrc file instead. OMZ adds many aliases for environments where they don't exist, which is a common use case for users starting fresh in a new environment.

**Comment by AsyncMoksha** [comment]
Solution:

In your `.zshrc` or `.zshenv`, move the `source ~/.profile` line to the bottom of the file.

I initially had the same problem as you did until I did this.

**Comment by VProfirov** [comment]
1. General approach to a more general solution,
if you want to control the aliases globally while using zsh and .oh-my-zsh without anything else will be to create dir where your aliases' definitions are summed up into a single file (ex. aliases.sh) for which you can create symlink into **/etc/profile.d**.
 _Example:_
**$ ln -s /etc/aliases-project/aliases.sh /etc/profile.d/**
This will allow your aliases to be accessible and uniformed in bash and zsh across login users
Specific to bash or zsh aliases, potentially overriding the global ones you just set can be placed in the .*rc files (.bashrc and .zshrc) per user

2. Direct isolated solution to the **"Oh My Zsh aliases override .profile aliases"** problem:
As for .oh-my-zsh, it defines much of default behavior without any plugins as the main alias re-definition file is located at:
**/home/$USER/.oh-my-zsh/lib/directories.zsh**, where defult navigation aliases are set for the **ls** command.
So, in order to solve your problem @mcandre, you can just comment does aliases that bother you and you already defined in your config-chain regarding the zsh shell aliases, or just all ls related aliases in the above mentioned .oh-my-zsh directory.
