### ISSUE TITLE
nodename nor servname provided, or not known。

### ISSUE THREAD

**Issue by emptyglass123** [ohmyzsh/ohmyzsh#8969]
```
pactepacterara@localhost ~ % wget sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
--2020-05-28 16:21:09--  http://sh/
正在解析主机 sh (sh)... 失败：nodename nor servname provided, or not known。
wget: 无法解析主机地址 “sh”
http://: 无效的主机名.
pactepacterara@localhost ~ % $ sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
zsh: command not found: $
pactepacterara@localhost ~ %
```

**Comment by mcornella** [comment]
In the first command, you wrote `wget` before the command to install (`sh -c "$(...`). So in reality, you're running `wget` and passing in the argument `sh`, which is why you get the message `nodename nor servname provided`, because `wget` is trying to download the webpage `sh` (see `http://sh/` in the output), which doesn't exist.

In the second command, you wrote `$` before the command to install. `$` isn't a command (that's why you get `command not found`), but it's used instead to indicate a command that should be run. So if you see written in a tutorial, for example:
```
$ echo hello world
```
it's telling you to run `echo hello world`, without the `$` symbol (this is because normally, `$` is used as the symbol to separate the prompt from the actual command line, see 
![image](https://user-images.githubusercontent.com/1441704/83150928-29b2ae00-a0fc-11ea-9369-e265b6004b28.png).

There's a third problem here, which is that you can't connect to `raw.githubusercontent.com`. This is probably due to the China firewall (GFW), so look around for proxy solutions (try asking in https://github.com/ohmyzsh/ohmyzsh/pull/8692 maybe?).
