### ISSUE TITLE
pyenv plugin looks for pyenv in wrong place in Windows10 WSL2

### ISSUE THREAD

**Issue by rosensama** [ohmyzsh/ohmyzsh#9034]
**Describe the bug**
When the pyenv plugin is used in a WSL2 shell, it looks for pyenv in the Windows path instead of the linux path.

`/mnt/c/Users/username/.pyenv/pyenv-win/bin/pyenv: 3: cmd: not found`

it should be looking in 

`/home/username/.pyenv`

If you export `PYENV_ROOT` before the plugins entry in .zshrc, then it works. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'pyenv'
2. source .zshrc
3. pyenv is reported as not found

**Expected behavior**
It should detect it's in WSL, not Windows and look in the correct location for a Linux install.

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 20.04 LTS in Windows Subsystem for Linux 2, recently updated
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: default for Ubuntu WSL.  Seems to be the same as used by cmd, judging by the options shown when right clicking on the header.

**Comment by mcornella** [comment]
The probable cause here is that `pyenv` appears in `$PATH` before the WSL one, so the PYENV_ROOT lookup logic is bypassed: https://github.com/ohmyzsh/ohmyzsh/blob/aaa87063a27cd581b5f0fa1f23a0170f623686a9/plugins/pyenv/pyenv.plugin.zsh#L5-L16

A possible solution is to fix the `$PATH` order so that Windows folders are last, but I believe that is already done, so the problem is that the WSL pyenv folder doesn't appear in `$PATH`. If that is so, we should add logic to ignore the `$PATH` `pyenv` if it comes from a Windows folder inside WSL.

**Comment by marianyfs** [comment]
up

**Comment by ezhupa99** [comment]
# This is the right configuration you should add to you .zshrc or .bashrc
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

**Comment by arvinsim** [comment]
@ezhupa99 Thanks. Your solution worked for me.

**Comment by mcornella** [comment]
@arvinsim the `pyenv` plugin now checks if the found `pyenv` is part of pyenv-win: https://github.com/ohmyzsh/ohmyzsh/blob/5377cc37c0f71fe22484303a4c6f387aa339f3f5/plugins/pyenv/pyenv.plugin.zsh#L7-L8, and then tries to find the right one inside WSL.

Can you check without Emanuel's solution whether it finds it for you, and if not, open a new bug report?
