### ISSUE TITLE
Update notice problem

### ISSUE THREAD

**Issue by MtnBiker** [ohmyzsh/ohmyzsh#9051]
**Describe the solution you'd like**
Add the words "or `upgrade_oh_my_zsh` in terminal at your convenience to upgrade." to the upgrade notice.

**Describe alternatives you've considered**
I have automatic change to a particular ruby in my iTerm startup which bypasses the update Y/n as shown from iTerm start up. macOS iTerm, Mojave
```
Last login: Fri Jun 19 15:30:08 on console
[Oh My Zsh] Would you like to update? [Y/n]: chruby ruby-2.7.0

project on  git-branch-name [$!?]
```
**Additional context**
I'm calling this a feature request although to some extent it's a bug; but since it's unique to my setup with iTerm, I'm calling it a feature request.

Thank you.

**Comment by mcornella** [comment]
You can add the chruby command to your zshrc file instead of the iTerm settings.

Another option is to disable the automatic update with `DISABLE_AUTO_UPDATE=true` in your zshrc file (before OMZ is sourced), or to disable the update prompt (which will always update without asking) with `DISABLE_UPDATE_PROMPT=true` in your zshrc file (again, before OMZ is sourced).

**Comment by MtnBiker** [comment]
Thanks for the suggestion. But iTerm can use different commands depending on the project it's related to. In other words, different Rubies for different projects.
