### ISSUE TITLE
zsh_reload plugin fail on popOS 20.04

### ISSUE THREAD

**Issue by francogp** [ohmyzsh/ohmyzsh#9054]
**Describe the bug**
if you execute `src` it goes to bash instad of zsh after recompile

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'zsh_reload'
2. Run command 'src'
3. It goes to bash after compilation, instead of restarting zsh

**Expected behavior**
recompile configs and restart zsh

**Desktop (please complete the following information):**
 - OS / Distro: [popOS 20.04]
 - Latest ohmyzsh Update?: [Yes]
 - ZSH Version: [5.8]
 - Terminal emulator [tested on Tilix and default terminal]

**NOTE that this problem cannot be reproduced on ubuntu. Only popOS**

**Comment by mcornella** [comment]
The zsh_reload plugin uses `$SHELL` to reload the zsh session. If `$SHELL` is bash instead of zsh, which it would be if bash is the default shell instead of zsh, then bash will be executed.

If you change the default shell to zsh this won't happen anymore, but I can see how the plugin could be smarter. I'll change the behavior but for now you can run `chsh -s $(which zsh)` to change the default shell to zsh.

**Comment by francogp** [comment]
> The zsh_reload plugin uses `$SHELL` to reload the zsh session. If `$SHELL` is bash instead of zsh, which it would be if bash is the default shell instead of zsh, then bash will be executed.
> 
> If you change the default shell to zsh this won't happen anymore, but I can see how the plugin could be smarter. I'll change the behavior but for now you can run `chsh -s $(which zsh)` to change the default shell to zsh.

I already change using that command, it did not work

**Comment by mcornella** [comment]
Try `omz update`, I pushed a fix.
