### ISSUE TITLE
Auto assign PR reviewers

### ISSUE THREAD

**Issue by bartekpacia** [ohmyzsh/ohmyzsh#9093]
**Is your feature request related to a particular plugin or theme?**
No, it's related to the GH folder.

**Is your feature request related to a problem? Please describe.**
There's a lot of plugins, and it's time-consuming to find the person responsible for a plugin.

**Describe the solution you'd like**
Create a GitHub action that fires up when a new PR modifying some plugin is submitted. The plugin's owner is automatically asked to review the PR.

This would use the data from [the CODEOWNERS file](https://github.com/ohmyzsh/ohmyzsh/blob/master/.github/CODEOWNERS)

**Describe alternatives you've considered**
It can be done manually as well.

**Additional context**
suggested by @larson-carter

**Comment by larson-carter** [comment]
Alright, I'm going to go part by part in my response!

> There's a lot of plugins, and it's time-consuming to find the person responsible for a plugin.

This is so true, so if we could assign people per plugin/theme issue that would be amazing! It would make tracking down/remembering/tagging people here a lot easier!

> Create a GitHub action that fires up when a new PR modifying some plugin is submitted. The plugin's owner is automatically asked to review the PR.

This would certainly be the best route. I know that we could somehow parse the CODEOWNERS file and if it finds a person responsible for those themes/plugins then it would automatically assign them to the issue at hand.

> It can be done manually as well.

Automating this would be amazing since it would save us a lot of time. It would also make it more clear for who is responsible for what.

**Comment by awasum** [comment]
I am looking into this issue.

**Comment by bartekpacia** [comment]
Me too. I've never had any contact with GH Actions before tho

**Comment by awasum** [comment]
We will pair program on it and share ideas. Its OK

**Comment by mcornella** [comment]
Before you get too into GitHub Actions, note that you won't be able to call the API to assign a user because [you need an API token, and that doesn't work when the PR comes from a fork](ilds-of-forks/16166). Instead, this is something the ohmyzsh-bot needs to take care of: https://github.com/ohmyzsh/ohmyzsh-bot.

You need to modify:
1. [app.yml](https://github.com/ohmyzsh/ohmyzsh-bot/blob/master/app.yml) if there are events that need to be added.
2. [index.ts](https://github.com/ohmyzsh/ohmyzsh-bot/blob/master/src/index.ts)
3. Add an [action](https://github.com/ohmyzsh/ohmyzsh-bot/tree/master/src/actions) that parses the CODEOWNERS file and mentions/assigns/requests a review to the person responsible for the file modified.

This is not easy and there's a lot of APIs and things to learn, so I understand it if this is too difficult (I don't even know where to start).

**Comment by bartekpacia** [comment]
Thank you for so much information.
Personally I'd still like to work on this, especially that the bot is written in Node, which I like a lot. cc @awasum @larson-carter

**Comment by larson-carter** [comment]
This is a lot of information. Basically I have no useful knowledge on how to do this. I can only do basic github actions(which I hate doing) and I can do only a little bit of node. However I have the logical workflow set in stone:

1.) PR is opened
2.) Bot clones this [file](https://github.com/ohmyzsh/ohmyzsh/blob/master/.github/CODEOWNERS)
> plugins/gitfast/ @/felipec
> plugins/sdk/ @/rgoldberg

3.) It will detect all of the changes. if it is in the directory ohmyzsh/plugins/gitfast/* it will then tag the responsible CODEOWNER
4.) The bot will make a comment stating "The codeowner for {DIRECTORY} is @/username"
5.) It will do multiple comments that way we can stage who is tracked.
6.) If no code owner is found for that specific {DIRECTORY} then it will ignore it!

I think this is the proper workflow. What do you all think?

**Comment by bartekpacia** [comment]
This is a quite detailed workflow, it’ll definitely help.

**Comment by mcornella** [comment]
This was added in https://github.com/ohmyzsh/ohmyzsh-bot/pull/4 and later refined to add a comment instead of assigning PR reviewers (external contributors can't be assigned). It now remains to fill out the CODEOWNERS file with the appropriate plugin maintainers.
