### ISSUE TITLE
`omz update` without restarting zsh

### ISSUE THREAD

**Issue by strobi** [ohmyzsh/ohmyzsh#9187]
**Is your feature request related to a problem? Please describe.**
I use a script that updates several tools including ohmyzsh (and homebrew, zsh-z etc). Using a script for updating is easier than typing the update commands for each tool individually. In the script the following command is used to update ohmyzsh:

```zsh -ic "omz update"```

This is no longer working as `omz update` now restarts the zsh session and interrupts my script. Only after entering `exit`, my script is continued to be executed.

**Describe the solution you'd like**
Would it be possible to revert to the original functionality or provide a new option for `omz update` (e.g. `omz update --no-restart`) to prevent zsh from being restarted?

**Comment by dekim24** [comment]
I started experiencing this today, except I actually have `omz update` in my `~/.zshrc` file so it auto-updates every time I open a new terminal window (usually at least once a day). This has been fine for months, but starting earlier today, since it restarts the session every time `omz update` is run (even if there is seemingly no new update to capture), I was unable to open my terminal until I removed `omz update` from `~/.zshrc`.

**Comment by mcornella** [comment]
Fixed in 89400f15.

**Comment by ksze** [comment]
For some reason, this behaviour has returned since last week or so.

**Comment by mcornella** [comment]
1aa2b18e: I added an `--unattended` flag so you can use it in a script (`omz update --unattended`). This bypasses the automatic zsh reload while properly working for normal CLI usage. Sorry I forgot about why I removed it in the first place, I hadn't linked the commit to this issue.

**Comment by mcornella** [comment]
Hey @ksze, I'm thinking of removing the `--unattended` flag since it's adds complexity and is only used in scripts, which isn't the intention of the CLI. You could still update by calling `$ZSH/tools/upgrade.sh`, would that work for you?

**Comment by strobi** [comment]
I would imagine that there are quite a few people who update omz automatically in a script. Are there any drawbacks to using `$ZSH/tools/upgrade.sh` instead of `omz update --unattended` (e.g., `${ZSH_CACHE_DIR}/.zsh-update` is not updated)?

**Comment by ksze** [comment]
@mcornella Personally I don't *really* mind either way. I was just surprised by the change in behaviour. I can imagine that it is simpler and safer to always interrupt and get the user to restart zsh because omz initialization is not guaranteed to be reentrance-safe.

**Comment by mcornella** [comment]
> Are there any drawbacks to using `$ZSH/tools/upgrade.sh` instead of `omz update --unattended` (e.g., `${ZSH_CACHE_DIR}/.zsh-update` is not updated)?

There are no drawbacks as far as I'm aware, it is generally preferable to use the script directly. [I've documented this in the FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-manually-update-oh-my-zsh-from-a-script).

I'm reconsidering removing the flag though. What I don't like is that you need to run the full `zsh -i` session in order to call `omz update`, perhaps it could be reconverted into a binary.
