### ISSUE TITLE
multi-user issues on mac (/usr/local/share/zsh/)

### ISSUE THREAD

**Issue by condaatje** [ohmyzsh/ohmyzsh#9303]
**Describe the bug**
When installing oh-my-zsh on two separate user accounts in macOS, the `compaudit` issue that can usually be solved as with `compaudit | xargs chmod g-w` will only fix things for one user, leaving the other user with a failed compaudit check. I may be doing something dumb, but if anyone else is able to reproduce I think this is a reasonably main-line use case?

**To Reproduce**
1. have oh-my-zsh installed on admin macOS user
2. create second (non-admin) macOS user
3. install oh my zsh and start a new terminal session

**Expected behavior**
not sure - how is this situation supposed to be handled in an ideal case? I'd rather not use `ZSH_DISABLE_COMPFIX`

**Screenshots and/or Recordings**

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x  3 <main-user>  staff   96 Sep 30 21:09 /usr/local/share/zsh
drwxr-xr-x  5 <main-user>  staff  160 Oct  1 22:43 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

**Self Check**

was not able to find a previous issue report for this specific niche - but please feel free to link/close if this is a duplicate

**Desktop (please complete the following information):**

 - OS / Distro: [macOS]
 - Latest ohmyzsh update?: [Yes]
 - ZSH Version: [5.7.1]
 - Terminal emulator: [iTerm2]

**Comment by mcornella** [comment]
This is [partially covered in the brand-new Settings wiki section](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_disable_compfix). Basically, if you have control over the `<main-user>` there is no security risk. Zsh isn't smart enough to know that, that's why you need to ignore this message by setting `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before OMZ is sourced.

**Comment by thomas6g** [comment]
I wonder if disabling the entirely security audit by the suggested setting is a good idea?

There seems to be a reason that someone added these checks at the beginning of the Zsh execution. If the reason did not change we should make it work with suggested admin / normal user split on Mac. If the reason is not valid any more, the checks should be default disabled or entirely removed from the start script.

**Comment by yunsii** [comment]
> This is [partially covered in the brand-new Settings wiki section](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#zsh_disable_compfix). Basically, if you have control over the `<main-user>` there is no security risk. Zsh isn't smart enough to know that, that's why you need to ignore this message by setting `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before OMZ is sourced.

Still isn't smart enough?
