### ISSUE TITLE
How to change time from 12H to 24H.

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#9387]
Good morning!

I have a simple question. **Does anyone know how to change the time of zsh (or oh-my-zsh, I don't know which) from 12H to 24H?**
In the next screenshot you can see that in my computer are the 14:23 but in the terminal it shows 2:23.
Thanks!
![Captura de pantalla de 2020-10-25 14-23-42](https://user-images.githubusercontent.com/66907184/97108419-b7a3bc80-16cd-11eb-8a3a-b186b856e2b5.png)

**Comment by mcornella** [comment]
Depends on what theme you're using. Some themes allow you to configure that; if not, you have to change the `RPROMPT` variable to use the [24-hour time prompt expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time).

**Comment by carlosala** [comment]
I'm using the theme nanotech. I'll revise what you said.
Gràcies!😉

**Comment by mcornella** [comment]
Right, so the nanotech theme [changes `RPROMPT` here](https://github.com/ohmyzsh/ohmyzsh/blob/fcb6fa78a1304f9a8eff2a7563658de04a13d499/themes/nanotech.zsh-theme#L2). Instead of using `%D{%p}` you could use `%T`.

You have two options:
- Copy the theme in `$ZSH_CUSTOM` (see [overriding and adding themes](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes)) and modify the line linked above to use `%T` instead of `%D{%p}`.
- Copy only the line linked above in your zshrc file (after OMZ is sourced) and again, modify it to use `%T` instead of `%D{%p}`.

**Comment by mcornella** [comment]
> Gràcies!😉
De res! 😊
