### ISSUE TITLE
Include function in grep.zsh

### ISSUE THREAD

**Issue by ajr-dev** [ohmyzsh/ohmyzsh#9506]
I want to include this in my `custom/lib/grep.zsh` but I don't know how to do it because of the cache.

```
# Recursively search pattern, ignore case, ignore binary files,
# prefix with line number within file
function grepr() {
  grep -rIin "$1" . "$GREP_OPTIONS"
}
```

**Comment by mcornella** [comment]
You can put it in your zshrc file.

**Comment by ajr-dev** [comment]
The thing is the "$GREP_OPTIONS" aren't set outside of `lib/grep.zsh`. How could I save them in the cache too?

**Comment by mcornella** [comment]
If you write the function like above the `$GREP_OPTIONS` is already applied, since the alias is expanded. You'll see that in the body of the function if you run `which grepr`, so you can skip adding `$GREP_OPTIONS`:
```zsh
function grepr() {
  grep -rIin "$1" .
}
```
![image](https://user-images.githubusercontent.com/1441704/102015440-df251600-3d5b-11eb-9d86-c37682a9c02b.png)
