### ISSUE TITLE
Zsh function problem

### ISSUE THREAD

**Issue by carlosala** [ohmyzsh/ohmyzsh#9510]
I have a small doubt with Zsh. First of all, sorry about putting this issue here, but I don't find the solution for my problem.
I want to create a function that, depending on which terminal I'm using, returns one or other thing. This is what I have. Where is the error?
Thanks and sorry for this stupid issue :(
```
function sshCompatible {
  if [$TERM != "xterm-256color"]; then
    ssh $1
  else
    TERM=xterm-256color ssh $1
  fi
}
```

**Comment by mcornella** [comment]
`[` and `]` need to have spaces around it: `if [ $TERM != "..." ]; then`.

That said, if `$TERM` is `xterm-256color` in the else, there's no need to pass it set it when calling `ssh` since `TERM` is exported by default. This means that what the function does is essentially calling `ssh $1` in both branches of the if, so the function body can be just substituted with `ssh $1`. That's like calling ssh directly, so I think you probably want to do something else?

**Comment by carlosala** [comment]
The fact is that with Alacritty, ssh doesn't work well because in the host computer doesn't have alacritty terminfo installed. So if you type `TERM=xterm-256color ssh` alacritty connects to the host computer with the common terminal in Linux. I had an error there, the `!=` needs to be an `=`. Sorry about this silly issue, the problem were the spaces.
Gràcies!

**Comment by mcornella** [comment]
If that's the case, you can substitute the whole thing with an alias, which will also allow you to pass multiple arguments:
```zsh
alias sshCompatible='TERM=xterm256-color ssh'
```

**Comment by carlosala** [comment]
Oh, yes. It can be really interesting hehe. I just created an `alias ssh=sshCompatible`, that runs the function. Thanks, I think I'm going to change that part!
