### ISSUE TITLE
vi-mode: `vv` doesn't open editor with low `$KEYTIMEOUT` value

### ISSUE THREAD

**Issue by pentago** [ohmyzsh/ohmyzsh#9588]
**Describe the bug**
After the latest update where new sequence to open editor as line editor (double vv) is introduced, editor doesn't open. 

**To Reproduce**
Input command, enter vi-mode, press **vv**.

**Expected behavior**
$EDITOR opens to edit the line instead of editing inline.

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: Alacritty + iTerm2

**Comment by mcornella** [comment]
What does this show: `bindkey -M vicmd vv`?

**Comment by pentago** [comment]
I get `"vv" edit-command-line`.
What gives?

**Comment by mcornella** [comment]
Is `$VISUAL` or `$EDITOR` set?

**Comment by pentago** [comment]
Yes, all to `vim`:
https://i.imgur.com/y41n4kO.png

**Comment by mcornella** [comment]
Are you sure you're in `vicmd`?

**Comment by pentago** [comment]
@mcornella absolutely in vicmd. I think the issue comes from the fact that line edit is bound to **vv** where first **v** triggers the visual mode. What I think happens on **vv** is just visual mode toggle, nothing more.

Thoughts?

**Comment by stevebarreira** [comment]
I'm seeing similar behavior to @pentago and seems like it's related to the `KEYTIMEOUT` value.

My default is `5`, which I'm unable to trigger the command. However if I set it to `50`, `vv` will trigger the edit mode. Not sure the broader implications of making an adjustment like that.

**Comment by mcornella** [comment]
I can reliably trigger it on `KEYTIMEOUT=15`, and less so with `KEYTIMEOUT=10`. There are other double-char key bindings so I think raising the value to a working state would be the solution here.

Other solutions:
- Use another lowercase, single-char key binding: this would mean overriding a preexisting key binding, since all the lowercase letter key bindings are taken (see `bindkey -M vicmd`).
- Use an uppercase, single-char key binding: there are a few undefined ones, like `H` or `U` (again, see output of `bindkey -M vicmd`).

**Comment by pentago** [comment]
While not ideal, **V** would be decent workaround for me.

**Comment by mcornella** [comment]
`V` is being used by `visual-line-mode`:
```console
$ bindkey -M vicmd V
"V" visual-line-mode
```

These are the default uppercase key bindings for `vicmd`:
```
"A" vi-add-eol
"B" vi-backward-blank-word
"C" vi-change-eol
"D" vi-kill-eol
"E" vi-forward-blank-word-end
"F" vi-find-prev-char
"G" vi-fetch-history
"I" vi-insert-bol
"J" vi-join
"N" vi-rev-repeat-search
"O" vi-open-line-above
"P" vi-put-before
"R" vi-replace
"S" vi-change-whole-line
"T" vi-find-prev-char-skip
"V" visual-line-mode
"W" vi-forward-blank-word
"X" vi-backward-delete-char
"Y" vi-yank-whole-line
```

**Comment by pentago** [comment]
Hmm, I'm not big on visual-line-mode and I expect that vast majority of people isn't.
Would sacrificing V for sake of working Visual mode be a decent tradeoff until there's more complete solution available?

**Comment by mcornella** [comment]
We already had to backtrack an overriding key binding, this would be more of the same.

**Comment by japrogramer** [comment]
I have this but also ..

but i can do `:execute: edit-command-line_` in vi mode and it works ... so it is the key binding that isn't working

**Comment by mcornella** [comment]
That has been established already. You can't trigger the key binding because the `v` key binding gets triggered too soon. Try raising the `$KEYTIMEOUT` value like is said in https://github.com/ohmyzsh/ohmyzsh/issues/9588#issuecomment-758133386 and https://github.com/ohmyzsh/ohmyzsh/issues/9588#issuecomment-758150445 and you'll see that it works.

We're now debating what alternative to choose.

**Comment by mcornella** [comment]
We can also use a CTRL or ALT sequence. It's not vim-like but we already have other key bindings that use them.

**Comment by michaeltintiuc** [comment]
It should at least be mentioned that `KEYTIMEOUT` should be adjusted in the `vi-mode` README if an alternative is not agreed upon, my value was of `1`

**Comment by AckslD** [comment]
Even with `KEYTIMEOUT` set to `40` or `100` this does not work for me :( I'm really missing this feature.

**Comment by mcornella** [comment]
> Even with `KEYTIMEOUT` set to `40` or `100` this does not work for me :( I'm really missing this feature.

What's `echo $KEYTIMEOUT; bindkey -M vicmd vv` show? Are you sure you're on vicmd mode?

**Comment by AckslD** [comment]
Hmm, `bindkey -M vicmd vv` returns `"vv" undefined-key`. Do I need to set this manually?

**Comment by michaeltintiuc** [comment]
No you don't https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/vi-mode/vi-mode.plugin.zsh#L67

**Comment by AckslD** [comment]
This was my bad! I didn't realise that I actually had `zsh-vim-mode` loaded and not `vi-mode`. Sorry for the confusion!

**Comment by mcornella** [comment]
What should we do here?

**Comment by LunarWatcher** [comment]
The timeout refers to the wait time for an input sequence to complete. The equivalent in proper vim is `ttimeoutlen` (if -1, which it is by default, `timeoutlen` is the equivalent instead).

`KEYTIMEOUT=5` means you have to press v twice within 5ms for it to trigger the appropriate keybind. Simply put, you're typing too slow for that timeout to work. By the time you hit the second v, the timeout has elapsed and executed the bit you had so far. You can reproduce the exact same behavior in proper vim:

```
nnoremap vv :echoerr 'Triggered'<cr>
set timeoutlen=5
```
... and try typing vv in normal mode without triggering visual mode. It's really, really hard because of the timeout being that low.

`vv` with a that low timeout triggers visual mode precisely because it registers v, timeout elapses, it executes v (turns on visual mode), registers a new v, timeout elapses, and it executes v again (turns off visual mode). Simply put, vv won't work unless you can type v twice in under 5ms. Of course, you can hold down `v` and make the computer type it for you, but it's slower than just picking a higher timeout. 

The point being, it's not a bug. You just can't pick KEYTIMEOUT=5 and expect to type vv unless you have an extremely high typing speed and a keyboard that's capable of detecting, dispatching, and resetting the key (both physically and in the software) in under 5ms. The easiest way out is to increase your KEYTIMEOUT - for scale, I don't have any problems at 15ms. You can obviously pick another timeout, but pick one where you're actually able to type the keys you wanna type before the timeout elapses.

Or, of course, you can make a custom mapping if you need `KEYTIMEOUT=5` for whatever reason. I have no idea how, but it's documented somewhere. There's only so many keys to go around before compound keys start appearing though, so remapping vv (which works fairly well as it stands, in my opinion) is just gonna delay the problem until there aren't more single keys the terminal can detect or aren't more keys that make sense for a new keybind. 

I've also recommended documenting the problems caused by a low key timeout already, rather than remapping `vv` and potentially throwing `V` under the bus.
