### ISSUE TITLE
Why which cp outputs cp:aliased to nocorrect cp

### ISSUE THREAD

**Issue by shinokada** [ohmyzsh/ohmyzsh#9598]
When I type `which cp`, the output is `cp: aliased to nocorrect cp`.

All the commands in this [link](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/correction.zsh) return in the same manner.

Why is it?

**Comment by mcornella** [comment]
[`nocorrect`](http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html#index-nocorrect) is a zsh reserved word that means roughly "don't try to correct the command name nor the parameters passed to it". This is needed because this file sets `correct_all`, which enables correcting command names *and* arguments.

For example, if you have a file named `fileB`, and you do `cp file fileb`, zsh will prompt you to correct `fileb` to `fileB`. Normally you don't want to correct destination files, so `nocorrect` will turn off this behavior for `cp`.

**Comment by shinokada** [comment]
Thanks, that makes sense.
So how do I know the path to `cp`?

`which cp` and `type cp` outputs the same.

**Comment by mcornella** [comment]
You can use `which -a cp`.

**Comment by shinokada** [comment]
Thanks @mcornella.
