### ISSUE TITLE
Have an option to NOT display the feature adds for git commits

### ISSUE THREAD

**Issue by scott-knight** [ohmyzsh/ohmyzsh#9599]
**Is your feature request related to a problem? Please describe.**
Recently, when I run `upgrade_oh_my_zsh`, when it pulls the git updates, it shows feature adds (or fix) messages for the commits, which it didn’t used to. I would like to disable this feature as it disrupts my daily update scripts. I have to run the script twice now because this process stops my entire update process.

**Describe the solution you'd like**
I would like to have an option/setting in `.zshrc` that I can set to disable commit messages on update.

**Describe alternatives you've considered**
Haven't thought of any.

**Additional context**
If I knew how to write the code and create a PR for this, I would. I'm well versed in writing ZSH scripts to this level. I appreciate all that your guys do. Thanks for looking at this request.

**Comment by mcornella** [comment]
The latest version prints the changelog directly, without using `less`, so it shouldn't block the update process. That said, if you're using this in a script, you should run `$ZSH/tools/upgrade.sh` directly, which doesn't show the changelog, instead of using `omz update` or the deprecated `upgrade_oh_my_zsh`.

**Comment by scott-knight** [comment]
Thank you for the info, I really appreciate it.
