### ISSUE TITLE
vi-mode error when copy/paste

### ISSUE THREAD

**Issue by pepe82sh** [ohmyzsh/ohmyzsh#9605]
When using vi-mode and yanking a line, printing one, or doing anything related buffers, an error message is printed:
`clipcopy: Platform freebsd12.1 not supported or xclip/xsel not installed`. Works fine within tmux though. As it has been working in the past, I've been able to pinpoint the commit that made the problem appear: 98762faa0762e1f0ede05149c1f6b3a9db93e074

**To Reproduce**
1. Enable vi-mode
2. Change mode by pressing ESC
3. Type yy (yank line)

**Expected behavior**
In case of yy the line should be stored in the default buffer

**Recording**
[![asciicast](https://asciinema.org/a/pWGkyQ42gOhKQKXESFLUSgvsU.svg)](https://asciinema.org/a/pWGkyQ42gOhKQKXESFLUSgvsU)

 - OS / Distro: FreeBSD 12.2
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: MacOS Terminal

**Comment by mcornella** [comment]
In https://github.com/ohmyzsh/ohmyzsh/commit/98762faa0762e1f0ede05149c1f6b3a9db93e074 we added a wrapper around the yank action to redirect the buffer to `clipcopy`, which allows it to work for the rest of the system clipboard.

It works under tmux because `clipcopy` uses tmux's clipboard. Try installing [`xclip`](https://www.freebsd.org/cgi/man.cgi?query=xclip&manpath=ports&sektion=1).

I assume pasting doesn't work though right? If not, we should fix the logic to not override `$CUTBUFFER` when `clipcopy`/`clippaste` fails.

**Comment by pepe82sh** [comment]
I'm on a machine without X11. Installing xclip would mean to install X11, and all the dependencies that brings with it.

**Comment by mcornella** [comment]
Please try this patch:
```patch
diff --git a/plugins/vi-mode/vi-mode.plugin.zsh b/plugins/vi-mode/vi-mode.plugin.zsh
index 0b11a6a7..7f14961a 100644
--- a/plugins/vi-mode/vi-mode.plugin.zsh
+++ b/plugins/vi-mode/vi-mode.plugin.zsh
@@ -100,13 +100,13 @@ function wrap_clipboard_widgets() {
       eval "
         function ${wrapped_name}() {
           zle .${widget}
-          printf %s \"\${CUTBUFFER}\" | clipcopy
+          printf %s \"\${CUTBUFFER}\" | clipcopy 2>/dev/null || true
         }
       "
     else
       eval "
         function ${wrapped_name}() {
-          CUTBUFFER=\"\$(clippaste)\"
+          CUTBUFFER=\"\$(clippaste 2>/dev/null || echo \$CUTBUFFER)\"
           zle .${widget}
         }
       "
```

**Comment by pepe82sh** [comment]
Seems to work 👍
