### ISSUE TITLE
I CAN'T SHORTEN MY PATH IN VSCODE, HELP PLEASE! 

### ISSUE THREAD

**Issue by Abdelfatahh** [ohmyzsh/ohmyzsh#9614]
![image](https://user-images.githubusercontent.com/37370643/105472578-c9810580-5ca4-11eb-91a0-787401fa96bc.png)

****I want to it to show only the last two directories.. Is there anything I can do? 
Thanks in advance.****

**Comment by mcornella** [comment]
Since you're using what seems to be agnoster (Oh My Zsh's version), you can [customize it](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes) to change the [`prompt_dir` function](https://github.com/ohmyzsh/ohmyzsh/blob/e4d2d27af4ba10ae456b5676f3b70573b01d9538/themes/agnoster.zsh-theme#L199) to use `%2~` instead of `%~` (these are called prompt sequences, you can find them [documented here](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Shell-state)).

You can also just copy-paste this function to your zshrc file (after OMZ is sourced) so you don't need to override the whole agnoster theme:

```zsh
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%2~'
}
```

No need to yell though.

**Comment by Abdelfatahh** [comment]
I didn't mean to yell I just wrote the whole sentence then figured out that Caps Lock is on. Thank you for your help but I already did that but every time I start a new terminal I should
`source /home/abdelfatah/.oh-my-zsh/themes/agnoster.zsh-theme`
so it can apply the changes on the new terminal...  @mcornella Thanks in advance!

**Comment by mcornella** [comment]
What guide did you follow? It should be enough to keep `ZSH_THEME=agnoster` (without an override in the custom folder) and doing this:

> You can also just copy-paste this function to your zshrc file (after OMZ is sourced) so you don't need to override the whole agnoster theme:
> 
> ```shell
> prompt_dir() {
>   prompt_segment blue $CURRENT_FG '%2~'
> }
> ```

**Comment by Abdelfatahh** [comment]
Done... it works now. Thanks  <3 
@mcornella

**Comment by gokulkulkarni1987** [comment]
For anyone who are not using `agnoster.zsh-theme` or are not sure which one they are using. Took some help from some comments above thanks to @mcornella.
Do,

```bash
echo $ZSH_THEME
```
my theme was `robbyrussell`
so I edited,

```bash
vi ~/oh-my-zsh/themes/robbyrussell.zsh-theme
```
Changed,

```bash
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
```

to

```bash
PROMPT+=' %{$fg[cyan]%}%2~%{$reset_color%} $(git_prompt_info)'
```

taking reference from [document](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Shell-state)

Thanks @mcornella
