### ISSUE TITLE
Perform the code security audit. Is remote exploiting/command execution possible ?

### ISSUE THREAD

**Issue by antonakv** [ohmyzsh/ohmyzsh#9748]
**Is your feature request related to a particular plugin or theme? If so, specify it.**
No, It's not

**Is your feature request related to a problem? Please describe.**
Oh My Zsh used on wide range of systems and on root accounts as well. The code didn't have any automated or manual security audit to find out if remote exploiting is possible.

**Describe the solution you'd like**
Perform Ohmyzsh code security audit to find out if it's possible to: Buffer overflow, Remote code execution during Ohmyzsh updates

**Describe alternatives you've considered**
Alternative solution is stop using Ohmyzsh until security audit is performed

**Additional context**
I have concerns that OhMyZsh was used by some actors to gain systems control in terms of SolarWinds attack.

**Related Issues**
There are not. 0 issues related to security of the code. That's kind of weird I'd say.

**Comment by rwmitchell** [comment]
OMZ is just a collection of shell scripts to make zsh better. An exploit involving buffer overflows, etc, would need to be in zsh or the os.

Of course, if you’re running as root, the scripts wouldn’t need to do anything extra to become root and could compromise your system however they wanted.

**Comment by mcornella** [comment]
Oh My Zsh uses git with SSH/HTTPS protocol for installation and updates. If there's an 0-day in git that could be exploited, but so could many other projects so it's not really an OMZ vulnerability. An audit of such a thing is out of the scope of the project—the audit would need to be performed for git, curl, openssl, etc.

There is a [Security label](https://github.com/ohmyzsh/ohmyzsh/issues?q=label%3ASecurity) and since then two issues were reported and swiftly dealt with. We've also made sure that external requests use some kind of encrypted connection, mostly HTTPS.

All that said, I can't vouch for the project to be absolutely free of security holes, even though I've seen most of the codebase and found no possibilities for attack that don't involve the attacker already having access to the filesystem, in which case it's pointless to think of defenses; if the attacker can modify the filesystem you're already compromised regardless of whether you have OMZ or not.

What I can assure you though is that this was not used in any shape or form to carry out the SolarWinds attack. [Here's more info regarding that attack](https://www.csoonline.com/article/3601508/solarwinds-supply-chain-attack-explained-why-organizations-were-not-prepared.html).
