### ISSUE TITLE
No function called and no name too

### ISSUE THREAD

**Issue by giuramen** [ohmyzsh/ohmyzsh#9756]
https://github.com/ohmyzsh/ohmyzsh/blob/95a06f3927a286db257dc99791b02caba757fe33/tools/check_for_upgrade.sh#L32

**Comment by mcornella** [comment]
This is an [anonymous function](http://zsh.sourceforge.net/Doc/Release/Functions.html#Anonymous-Functions) that gets called immediately after defining it. This is done this way for the trap function that gets called to cleanup after running the upgrade.

Are you having any trouble with this?

**Comment by ehaiwag** [comment]
When I tried to run .zshrc, i got error:
.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'

I ran this because my vs code is complaining that my shell is too slow to run.
https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning

**Comment by mcornella** [comment]
You need to setup vs code to run zsh instead of bash. Zsh will automatically read the .zshrc file.
