### ISSUE TITLE
w command output is garbled under oh-my-zsh

### ISSUE THREAD

**Issue by neil-acc** [ohmyzsh/ohmyzsh#9773]
Everytime open new terminal tab, type command w looking over logged in, always garble appeared. I don't know what happened.

Current environment: (**I am sure issues occurs in any version**)
- macOS Big Sur version 11.2.3
- iTerm2 3.4.4
- Built-in Terminal
- oh-my-zsh latest version

---------------------

Phenomenon:
Built-in Terminal
![built-in-terminal](https://user-images.githubusercontent.com/75743591/113247506-c5e5ac80-92ed-11eb-9f5e-baba037a0d59.jpg)

iTerm2
![iterm2](https://user-images.githubusercontent.com/75743591/113247419-99ca2b80-92ed-11eb-9a32-1295b5db5069.jpg)

**Comment by neil-acc** [comment]
Try to install oh-my-zsh normally on another new macbook, still the same.

**Comment by mcornella** [comment]
Does this happen when running bash? I don't see what would make OMZ do that.

**Comment by neil-acc** [comment]
> Does this happen when running bash? I don't see what would make OMZ do that.

yes, same problem.

**Comment by mcornella** [comment]
Then this is not related to Oh My Zsh, it's a `w` issue where it's trying to display characters that the terminal emulator doesn't know how to display. That's why you get a question mark.

I'm not familiar with `w`, it looks like that is shown in the WHAT column which tells the command line call of the process that started the tty. But I don't know. Try asking on stackoverflow or other sites specialized on macOS.
