### ISSUE TITLE
Can not assign value to $token variable name

### ISSUE THREAD

**Issue by sirio3mil** [ohmyzsh/ohmyzsh#9918]
**Describe the bug**
I have some shell scripts that are using $token and after install and configure ohmyzsh this variable never take a value again

**To Reproduce**
1. Install and configure ohmyzsh
2. Run command

```
❯ export bla=bli
❯ echo $bla
bli
❯ export token=ble
❯ echo $token
$token
```
3. See error

**Expected behavior**
echo $token must output ble instead of $token.

**Desktop (please complete the following information):**

 - OS / Distro: macOS Big Sur 11.3.1
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8 (x86_64-apple-darwin20.0)
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment]
This is not an OMZ issue, and I can't reproduce it either.

I suggest you verify that the variable has been correctly set after the `export` command by running `export` without arguments, which will print the exported variables and their values, or by running `typeset -p token`.

It's also weird that you get the exact typed argument back (`$token`) instead of its value substituted. That tells me either the dollar sign is quoted or parameter expansion is disabled, but I have no idea how that would happen.

**Comment by kasunt-nixdev** [comment]
I too am running into this very issue.
```
zsh 5.8 (x86_64-apple-darwin20.0)
```

works fine for anything other than `token` as an environment variable.

**Comment by kasunt-nixdev** [comment]
@sirio3mil are you using `powerlevel10k` by any chance ? it appears to be using it internally https://github.com/romkatv/powerlevel10k/blob/master/internal/parser.zsh.
So i raised https://github.com/romkatv/powerlevel10k/issues/1407

**Comment by mcornella** [comment]
[Confirmed P10K bug](https://github.com/romkatv/powerlevel10k/issues/1407#issuecomment-846825706).
